Repository openshift/console, pull requests merged in 2018-09, with the labels that each got.

#459 Add/Remove image secret entries
  frontend/integration-tests/views/catalog.view.ts
  frontend/integration-tests/views/search.view.ts
  frontend/public/components/RBAC/_rbac.scss
  frontend/public/components/_dropdown.scss
  frontend/public/components/cluster-settings/_cluster-updates.scss
  frontend/public/components/secrets/_create-secret.scss
  frontend/public/components/secrets/create-secret.tsx
  frontend/public/components/utils/_value-from-pair.scss
  frontend/public/components/utils/dropdown.jsx
  frontend/public/style/_common.scss
Labels: lgtm, size/L

#402 Creating secret with 'all projects' selected uses project 'undefined'
  frontend/public/components/secret.jsx
Labels: lgtm, size/XS

#483 Fix monitoring alerts list page header area layout
  frontend/public/components/_alert.scss
  frontend/public/components/alert.tsx
Labels: lgtm, size/S

#488 Bug 1624748 - Don't show pods for service with no selector
  frontend/public/components/utils/vertnav.jsx
Labels: lgtm, size/XS

#436 Delete confirmation dialogs match the PatternFly recommendation
  frontend/public/components/factory/modal.tsx
  frontend/public/components/modals/_modals.scss
  frontend/public/components/modals/delete-modal.jsx
  frontend/public/components/modals/delete-namespace-modal.jsx
Labels: lgtm, size/M

#490 Fix Link to CatalogSource on Subscription Detail View
  frontend/public/components/cloud-services/index.tsx
  frontend/public/components/cloud-services/subscription.tsx
Labels: lgtm, size/XS

#491 Fix Text Filter for OLM Packages
  frontend/public/components/cloud-services/catalog-source.tsx
Labels: lgtm, size/XS

#494 Merge master into master-next
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/__tests__/components/modals/disable-application-modal.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/subscription.spec.tsx
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/integration-tests/views/app-list.view.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/modals/disable-application-modal.tsx
  frontend/public/components/operator-lifecycle-manager/_operator-lifecycle-manager.scss
  frontend/public/components/operator-lifecycle-manager/catalog-source.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
  frontend/public/components/operator-lifecycle-manager/k8s-resource.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/components/pod.jsx
  frontend/public/components/secret.jsx
  frontend/public/components/utils/nav-title.tsx
  frontend/public/components/utils/vertnav.jsx
  frontend/public/imgs/apps-logo-active.svg
  frontend/public/imgs/apps-logo.svg
Labels: lgtm, size/XL

#393 Implement project overview page
  frontend/package.json
  frontend/public/components/_overview.scss
  frontend/public/components/_project-overview.scss
  frontend/public/components/app.jsx
  frontend/public/components/overview.jsx
  frontend/public/components/project-overview.jsx
  frontend/public/components/utils/link.jsx
  frontend/public/components/utils/resource-icon.tsx
  frontend/public/components/utils/status-box.jsx
  frontend/public/style.scss
  frontend/public/style/_common.scss
  frontend/public/style/_overrides.scss
  frontend/public/vendor.scss
  frontend/yarn.lock
Labels: lgtm, size/XXL

#472 Add envFrom to Environment Editor
  frontend/__tests__/components/utils/name-value-editor.spec.tsx
  frontend/public/components/build.tsx
  frontend/public/components/daemonset.jsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.jsx
  frontend/public/components/environment.jsx
  frontend/public/components/pod.jsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/replication-controller.jsx
  frontend/public/components/stateful-set.jsx
  frontend/public/components/utils/_value-from-pair.scss
  frontend/public/components/utils/draggable-item-types.js
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/name-value-editor.jsx
  frontend/public/components/utils/value-from-pair.jsx
  frontend/public/style/_common.scss
Labels: lgtm, size/L

#495 Remove colons from form labels
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/edit-rule.jsx
  frontend/public/components/cluster-settings/certs-info.jsx
  frontend/public/components/cluster-settings/ldap.jsx
  frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
  frontend/public/components/modals/configure-update-strategy-modal.jsx
Labels: lgtm, size/M

#349 Add metrics to build page
  frontend/public/components/build.tsx
Labels: lgtm, size/S

#500 Add `btn` class back to modal buttons for proper spacing
  frontend/public/components/factory/modal.tsx
Labels: lgtm, size/XS

#502 Tidy up <label> usage and add missing htmlFor attributes where needed
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/edit-rule.jsx
  frontend/public/components/cluster-settings/cluster-settings.jsx
  frontend/public/components/modals/create-namespace-modal.jsx
  frontend/public/components/modals/labels-modal.jsx
  frontend/public/components/utils/selector-input.jsx
Labels: lgtm, size/M

#503 Fix dropdown width on create service instance page
  frontend/public/components/_cluster-service-instance.scss
Labels: lgtm, size/XS

#504 Temporarily disable add / edit rule page
  frontend/public/components/RBAC/index.js
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/RBAC/rules.jsx
  frontend/public/components/app.jsx
Labels: lgtm, size/M

#506 Bug 1625776 - Fix OAuth error handling during discovery
  auth/auth.go
Labels: lgtm, size/XS

#508 Show Correct Provider for Catalog Source View
  frontend/public/components/cloud-services/catalog-source.tsx
Labels: lgtm, priority/critical-urgent, size/XS

#511 Correctly sort service classes by external name
  frontend/public/components/cluster-service-class.tsx
Labels: lgtm, size/XS

#513 Uppercase "YAML" in sidebar download link
  frontend/public/components/sidebars/resource-sidebar.jsx
Labels: lgtm, size/XS

#492 Added siderbar help for resource quota
  frontend/public/components/sidebars/resource-quota-sidebar.jsx
  frontend/public/components/sidebars/resource-sidebars.ts
  frontend/public/models/yaml-templates.ts
Labels: lgtm, size/M

#509 Project overview tweaks to font sizes of names and headings.
  frontend/public/components/_list-view.scss
  frontend/public/components/_project-overview.scss
  frontend/public/components/_resource.scss
  frontend/public/components/project-overview.jsx
  frontend/public/style.scss
  frontend/public/style/coreos.css
Labels: lgtm, size/M

#516 update downstream build to use yarn offline
  Dockerfile.product
  sources
Labels: lgtm, size/M

#517 Fix OLM Feature Detection
  frontend/__tests__/features.spec.tsx
  frontend/public/components/nav.jsx
  frontend/public/features.ts
Labels: lgtm, size/S

#515 Fix Row Filters for Operator Custom Resources
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
Labels: lgtm, size/XS

#518 [release-3.11] change OLM feature detection to look for 'operators.coreos.com' apigroup
  frontend/__tests__/features.spec.tsx
  frontend/public/components/nav.jsx
  frontend/public/features.ts
Labels: lgtm, size/S

#512 Uploading file should check for file size
  frontend/public/components/utils/file-input.tsx
Labels: lgtm, size/M

#522 Fix operators.md link
  docs-internal/operators.md
Labels: lgtm, size/XS

#521 Bug 1624773 - fix CatalogSource and ClusterServiceVersion link on InstallPlans page
  frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
  frontend/public/components/operator-lifecycle-manager/install-plan.tsx
Labels: lgtm, size/S

#523 downstream builds sass from source; rh-manifest.txt
  Dockerfile.product
  bill-of-materials.json
  rh-manifest.txt
  sources
Labels: lgtm, size/XXL

#514 Add ux changes to env editor.
  frontend/__tests__/components/environment.spec.tsx
  frontend/public/components/_environment.scss
  frontend/public/components/environment.jsx
  frontend/public/components/utils/dropdown.jsx
  frontend/public/components/utils/name-value-editor.jsx
  frontend/public/style/_common.scss
  frontend/public/vendor.scss
Labels: lgtm, size/L

#487 Create/Edit generic secret
  frontend/public/components/secret.jsx
  frontend/public/components/secrets/_create-secret.scss
  frontend/public/components/secrets/create-secret.tsx
  frontend/public/components/utils/file-input.tsx
Labels: lgtm, size/L

#525 Only add x-csrf-token query param if set
  frontend/public/module/ws-factory.js
Labels: lgtm, size/XS

#526 Only show broker relist duration with duration relist behavior
  frontend/public/components/cluster-service-broker.tsx
Labels: lgtm, size/XS

#527 downstream install uses yarn deps from sources
  Dockerfile.product
  sources
Labels: lgtm, size/M

#529 Update title and help text for generic secret form
  frontend/public/components/secrets/create-secret.tsx
Labels: lgtm, size/S

#531 Add missing classes for CRD links
  frontend/public/components/custom-resource-definition.tsx
Labels: lgtm, size/XS

#481 Support service binding parameters
  frontend/package.json
  frontend/public/components/_cluster-service-instance.scss
  frontend/public/components/app.jsx
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/service-binding.tsx
  frontend/public/components/service-catalog/create-binding.tsx
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/components/service-catalog/schema-form.tsx
  frontend/public/components/service-catalog/shema-form.tsx
  frontend/yarn.lock
Labels: lgtm, size/L

#497 Better API Discovery
  frontend/__tests__/module/k8s/k8s-actions.spec.ts
  frontend/public/components/app.jsx
  frontend/public/components/error.tsx
  frontend/public/components/resource-list.tsx
  frontend/public/models/index.ts
  frontend/public/module/k8s/k8s-actions.ts
  frontend/public/module/k8s/k8s-reducers.ts
Labels: lgtm, size/L

#533 Add README note about fs.inotify.max_user_watches
  README.md
Labels: lgtm, size/XS

#535 tests: Use projects to create and delete test namespace on OpenShift clusters
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/base.scenario.ts
Labels: lgtm, size/S

#519 Changes to move overview toolbar actions to be aligned with the heading, as well as behave better at responsive viewport widths
  frontend/public/components/_nav-title.scss
  frontend/public/components/_overview.scss
  frontend/public/components/_project-overview.scss
  frontend/public/components/overview.jsx
  frontend/public/style/_common.scss
  frontend/public/style/_overrides.scss
Labels: lgtm, size/M

#537 Fix OLM Protractor Tests for Multiple CatalogSources
  frontend/integration-tests/tests/olm/catalog.scenario.ts
  frontend/integration-tests/tests/olm/descriptors.scenario.ts
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/integration-tests/views/catalog.view.ts
Labels: lgtm, size/S

#539 Remove unnecessary `bind` calls for create instance/binding pages
  frontend/public/components/service-catalog/create-binding.tsx
  frontend/public/components/service-catalog/create-instance.tsx
Labels: lgtm, size/XS

#528 Initial cut of Deploy Image page
  frontend/public/components/_deploy-image.scss
  frontend/public/components/app.jsx
  frontend/public/components/deploy-image.tsx
  frontend/public/components/deployment-config.tsx
  frontend/public/models/index.ts
  frontend/public/style.scss
Labels: lgtm, size/L

#545 Remove unnecessary pane body class from source-to-image page
  frontend/public/components/source-to-image.tsx
Labels: lgtm, size/L

#544 Sort image stream tags by semver
  frontend/package.json
  frontend/public/components/image-stream.tsx
  frontend/public/components/source-to-image.tsx
  frontend/yarn.lock
Labels: lgtm, size/M

#543 Remove hash link to "Software Info" as lazy loading routes broke it
  frontend/package.json
  frontend/public/components/cluster-overview.jsx
  frontend/yarn.lock
Labels: lgtm, size/S

#546 Move Deploy Image to non-namespaced route and auto-select namespace
  frontend/public/components/app.jsx
  frontend/public/components/deploy-image.tsx
  frontend/public/components/deployment-config.tsx
Labels: lgtm, size/S

#547 Redirect to creates resource instead of list page
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/secrets/create-secret.tsx
Labels: lgtm, size/M

#549 Fix username masthead bugs
  frontend/public/components/masthead.scss
Labels: lgtm, size/XS

#550 Remove "View All" link from Events box on Status page
  frontend/public/components/cluster-overview.jsx
Labels: lgtm, size/XS

#530 Initial Catalog View
  frontend/package.json
  frontend/public/components/_catalog-item.scss
  frontend/public/components/app.jsx
  frontend/public/components/catalog-item-icon.tsx
  frontend/public/components/catalog-items.jsx
  frontend/public/components/catalog.jsx
  frontend/public/components/image-stream.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/components/source-to-image.tsx
  frontend/public/components/utils/link.jsx
  frontend/public/style.scss
  frontend/yarn.lock
Labels: lgtm, size/L

#548 Fix bug where OCP logo abutted right edge of masthead
  frontend/public/components/masthead.scss
Labels: lgtm

#485 Empty value secret not displayed properly
  frontend/public/components/configmap-and-secret-data.jsx
Labels: lgtm, size/XS

#556 Change service catalog status "Pending" to "Not Ready"
  frontend/public/components/service-instance.tsx
  frontend/public/components/utils/service-catalog-status.tsx
  frontend/public/module/k8s/service-catalog.ts
Labels: lgtm, size/S

#524 Implement basic overview details panel
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/public/components/_overview.scss
  frontend/public/components/_project-overview.scss
  frontend/public/components/default-resource.jsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.jsx
  frontend/public/components/overview.jsx
  frontend/public/components/project-overview.jsx
  frontend/public/components/resource-list.tsx
  frontend/public/components/resource-pages.ts
  frontend/public/components/stateful-set.jsx
  frontend/public/components/utils/close-button.jsx
  frontend/public/components/utils/firehose.jsx
  frontend/public/components/utils/index.tsx
Labels: lgtm, size/XL

#557 Add instance and binding parameter ordering and types
  frontend/public/components/service-catalog/create-binding.tsx
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/components/service-catalog/schema-form.tsx
Labels: lgtm, size/M

#551 Rename vert-nav to horizontal-nav
  frontend/public/components/_horizontal-nav.scss
  frontend/public/components/_vert-nav.scss
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/cluster-service-plan.tsx
  frontend/public/components/container.jsx
  frontend/public/components/factory/details.tsx
  frontend/public/components/utils/_status-box.scss
  frontend/public/components/utils/horizontal-nav.jsx
  frontend/public/components/utils/index.tsx
  frontend/public/style.scss
Labels: lgtm, size/L

#558 Clear filter when reopening dropdown
  frontend/public/components/utils/dropdown.jsx
Labels: lgtm, size/XS

#554 e2e test for create secret form
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/secrets.scenario.ts
  frontend/integration-tests/views/secrets.view.ts
Labels: lgtm, size/M

#553 Fixing typos
  README.md
  STYLEGUIDE.md
Labels: lgtm, retest-not-required-docs-only, size/S

#458 Show both ClusterResourceQuotas and ResourceQuotas
  frontend/public/components/resource-quota.jsx
  frontend/public/models/index.ts
Labels: lgtm, size/M

#552 Add helpText option to filter bar
  frontend/public/components/_alert.scss
  frontend/public/components/alert.tsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/operator-lifecycle-manager/catalog-source.tsx
  frontend/public/style/_common.scss
Labels: lgtm, size/M

#565 Add basic source-to-image integration tests
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/source-to-image.scenario.ts
  frontend/integration-tests/views/source-to-image.view.ts
  jenkins.sh
Labels: lgtm, size/L

#561 Fix checkboxes in service catalog forms
  frontend/public/components/service-catalog/schema-form.tsx
Labels: lgtm, size/S

#567 Update package.json
  frontend/package.json
Labels: lgtm, size/XS

#562 Bump patternfly-react-extensions@2.5.1
  frontend/package.json
  frontend/yarn.lock
Labels: lgtm, size/XS

#559 Add daemon sets to project overview page
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/public/components/daemon-set.jsx
  frontend/public/components/overview.jsx
  frontend/public/components/project-overview.jsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/resource-pages.ts
Labels: lgtm, size/L

#571 Highlight Resource Quotas nav item when viewing ClusterResourceQuota
  frontend/public/components/nav.jsx
Labels: lgtm, size/XS

#536 tests: Use deployments, not daemon sets, for filter, annotation, and env scenarios
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/environment.scenario.ts
  frontend/integration-tests/tests/filter.scenario.ts
  frontend/integration-tests/tests/modal-annotations.scenario.ts
  frontend/integration-tests/views/crud.view.ts
Labels: lgtm, size/M

#570 Don't use `undefined` ns creating quota from all projects list
  frontend/public/components/resource-quota.jsx
Labels: lgtm, size/XS

#572 Replace selectbox with Dropdown component in create secret form
  frontend/public/components/secrets/create-secret.tsx
Labels: lgtm, size/S

#573 Default to current namespace when clicking catalog items
  frontend/public/components/catalog.jsx
  frontend/public/components/deploy-image.tsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/image-stream.tsx
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/components/source-to-image.tsx
Labels: lgtm, size/M

#575 Update openshift-logos-icon to v1.7.0 so Jaeger icon is available
  frontend/package.json
  frontend/yarn.lock
Labels: lgtm, size/XS

#582 Use active namespace by default if non specified in YAML
  frontend/public/components/edit-yaml.jsx
Labels: lgtm, size/XS

#583 Immediately update FLAGS.PROJECTS_AVAILABLE after creating project
  frontend/public/components/modals/create-namespace-modal.jsx
Labels: lgtm, size/S

#580 Use secret model directly
  frontend/public/components/secrets/create-secret.tsx
Labels: lgtm, size/S

#486 Add monitoring list and details pages for Alertmanager silences
  frontend/public/components/_monitoring.scss
  frontend/public/components/alert.tsx
  frontend/public/components/app.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/silence.tsx
  frontend/public/components/utils/link.jsx
  frontend/public/module/monitoring.js
  frontend/public/style.scss
  frontend/public/style/_icons.scss
  frontend/public/ui/ui-actions.js
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/L

#574 Catalog: Categorize Items, Vertical Tabs
  frontend/public/components/_catalog-item.scss
  frontend/public/components/catalog-items.jsx
  frontend/public/components/catalog.jsx
  frontend/public/components/utils/categorize-catalog-items.ts
Labels: lgtm, size/L

#560 Add overview to nav
  frontend/public/components/app.jsx
  frontend/public/components/nav.jsx
  frontend/public/components/overview.jsx
Labels: lgtm, size/L

#569 Refactor overview component
  frontend/public/components/daemon-set.jsx
  frontend/public/components/overview.jsx
  frontend/public/components/project-overview.jsx
Labels: lgtm, size/L

#586 Add catalog styling per mocks
  frontend/public/components/_catalog-item.scss
  frontend/public/components/_catalog.scss
  frontend/public/components/catalog.jsx
  frontend/public/style.scss
Labels: lgtm, size/L

#587 Update selected item when overview items change
  frontend/public/components/overview.jsx
Labels: lgtm, size/S

#566 Changes to overview with sidebar details view
  frontend/public/components/_detail-table.scss
  frontend/public/components/_overview.scss
  frontend/public/components/_project-overview.scss
  frontend/public/components/app.jsx
  frontend/public/components/default-resource.jsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.jsx
  frontend/public/components/overview.jsx
  frontend/public/components/stateful-set.jsx
  frontend/public/components/utils/deployment-pod-counts.tsx
  frontend/public/style/_layout.scss
Labels: lgtm, size/L

#577 Deploy Image integration test
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/deploy-image.scenario.ts
  frontend/integration-tests/tests/source-to-image.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/public/components/deploy-image.tsx
  jenkins.sh
Labels: lgtm, size/L

#589 Adjust spacing below heading and item count
  frontend/public/components/_catalog.scss
Labels: lgtm, size/XS

#579 Refactor menuActions
  frontend/public/components/chargeback.tsx
  frontend/public/components/clusters.tsx
  frontend/public/components/cron-job.jsx
  frontend/public/components/custom-resource-definition.tsx
  frontend/public/components/default-resource.jsx
  frontend/public/components/hpa.tsx
  frontend/public/components/image-stream-tag.tsx
  frontend/public/components/image-stream.tsx
  frontend/public/components/limit-range.tsx
  frontend/public/components/network-policy.jsx
  frontend/public/components/node.tsx
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/persistent-volume.jsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/resource-quota.jsx
  frontend/public/components/service-account.jsx
  frontend/public/components/service-binding.tsx
  frontend/public/components/storage-class.tsx
  frontend/public/components/utils/nav-title.tsx
Labels: lgtm, size/M

#592 Add OpenShift Dedicated logo option
  cmd/bridge/main.go
  frontend/public/components/masthead.tsx
  frontend/public/imgs/openshift-dedicated-logo.svg
  frontend/public/index.html
  frontend/public/tokener.html
Labels: lgtm, size/S

#597 Add `PackageManifest` Model
  frontend/public/components/operator-lifecycle-manager/index.tsx
  frontend/public/models/index.ts
Labels: lgtm, size/M

#599 updated downstream sources
  sources
Labels: lgtm, size/XS

#598 Clean up monitoring page help text code
  frontend/public/components/alert.tsx
  frontend/public/components/silence.tsx
Labels: lgtm, size/S

#602 Remove breadcrumb from Create Instance; Highlight nav for S2I
  frontend/public/components/nav.jsx
  frontend/public/components/service-catalog/create-instance.tsx
Labels: lgtm, size/S

#605 For monitoring Silences with no alertname, use the other matchers
  frontend/public/components/alert.tsx
Labels: lgtm, size/XS
