Repository openshift/console, pull requests merged in 2018-05, with the labels that each got.

#1 Rename for packaging: coreos-inc/bridge -> openshift/console.
  .gitignore
  README.md
  auth/auth.go
  build-backend
  builder-run
  cmd/bridge/main.go
  docs-internal/operators.md
  docs-internal/releases.md
  frontend/package.json
  glide.yaml
  jenkins
  server/middleware.go
  server/server.go
  test-backend
  version/version.go
Labels: size/M

#6 update version on OpenShift cluster
  frontend/public/components/software-details.jsx
Labels: lgtm, size/L

#4 Update some references to Tectonic in README
  README.md
Labels: size/XS

#13 Add read/only env tab viewer for builds.
  frontend/public/components/build.tsx
Labels: size/S

#15 Fix YAML Autocomplete
  frontend/public/components/edit-yaml.jsx
Labels: kind/bug, size/XS

#11 Fix bug where .co-sysevent-stream__timeline__end-message results in h…
  frontend/public/components/_sysevent-stream.scss
Labels: size/S

#10 Tidy up .co-m-nav-title
  frontend/__tests__/components/utils/nav-title.spec.tsx
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/edit-rule.jsx
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/_cluster-overview.scss
  frontend/public/components/_edit-yaml.scss
  frontend/public/components/_nav-title.scss
  frontend/public/components/_resource.scss
  frontend/public/components/_vert-nav.scss
  frontend/public/components/chargeback.tsx
  frontend/public/components/client-tokens.jsx
  frontend/public/components/cloud-services/_cloud-services.scss
  frontend/public/components/clusters.tsx
  frontend/public/components/default-resource.jsx
  frontend/public/components/error.jsx
  frontend/public/components/events.jsx
  frontend/public/components/ingress.jsx
  frontend/public/components/network-policy.jsx
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/persistent-volume.jsx
  frontend/public/components/pod-logs.jsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/replication-controller.jsx
  frontend/public/components/resource-quota.jsx
  frontend/public/components/service-account.jsx
  frontend/public/components/stateful-set.jsx
  frontend/public/components/storage-class.tsx
  frontend/public/components/utils/details-page.tsx
  frontend/public/components/utils/nav-title.tsx
  frontend/public/components/utils/status-box.jsx
  frontend/public/style/_common.scss
  frontend/public/style/_overrides.scss
  frontend/public/style/coreos.css
Labels: lgtm, size/L

#9 Accept client secret from a file
  cmd/bridge/main.go
Labels: lgtm, size/M

#16 Port OpenShift log viewer styles to Tectonic log window
  frontend/public/components/_log-window.scss
  frontend/public/components/_pod-logs.scss
  frontend/public/components/utils/log-window.jsx
  frontend/public/style/_vars.scss
Labels: lgtm, size/L

#18 Fix padding on .co-clusterserviceversion-list__title at mobile
  frontend/public/components/cloud-services/_cloud-services.scss
Labels: lgtm, size/XS

#20 Improve vertical alignment of .rbac-rule__actions cog and text
  frontend/public/components/RBAC/_rbac.scss
Labels: lgtm, size/XS

#22 Fix bug where timeline border appeared when empty
  frontend/public/components/_sysevent-stream.scss
Labels: lgtm, size/S

#28 Openssl base64 won't work on long strings without the -A flag...
  README.md
Labels: lgtm, size/XS

#29 YAML editor: enable word wrap
  frontend/integration-tests/protractor.conf.ts
  frontend/public/components/edit-yaml.jsx
Labels: lgtm, size/XS

#32 Tidying up SCSS for masthead
  frontend/public/components/masthead.scss
  frontend/public/style/_layout.scss
  frontend/public/style/_vars.scss
Labels: lgtm, size/XS

#35 frontend: Fixes bug where userID was used to display the user name
  frontend/public/components/masthead.tsx
Labels: lgtm, size/XS

#34 Terminals for Pods (like kubectl exec)...
  frontend/package.json
  frontend/public/components/_terminal.scss
  frontend/public/components/pod-exec.jsx
  frontend/public/components/pod.jsx
  frontend/public/components/terminal.jsx
  frontend/public/module/ws-factory.js
  frontend/public/style.scss
  frontend/yarn.lock
  pkg/proxy/proxy.go
Labels: size/L

#38 Do not outline events on focus.
  frontend/public/style/_overrides.scss
Labels: lgtm, size/XS

#36 Show Active Nav Link for GroupVersionKind URLs
  frontend/public/components/nav.jsx
Labels: size/S

#41 Remove tab index from react-virtualized list
  frontend/public/components/events.jsx
  frontend/public/style/_overrides.scss
Labels: size/XS

#43 Decrease flush interval from 500ms to 100ms.
  pkg/proxy/proxy.go
Labels: size/XS

#39 Some containers can not run our command (/bin/sh)...
  frontend/public/components/pod-exec.jsx
  frontend/public/components/terminal.jsx
Labels: size/M

#23 Toggle between secret's data visibility
  frontend/public/components/configmap-and-secret-data.jsx
  frontend/public/components/configmap.jsx
  frontend/public/components/secret.jsx
Labels: lgtm, size/M

#47 frontend build: support node.js v10.x
  frontend/package.json
  frontend/yarn.lock
Labels: size/L

#52 Fix GroupVersionKind Active NavLink
  frontend/public/components/nav.jsx
Labels: lgtm, size/XS

#51 Include grid col-xs for mobile support
  frontend/public/components/cloud-services/catalog-source.tsx
Labels: size/S

#45 Remove unnecessary commands from README
  README.md
Labels: lgtm, size/XS

#37 Upload Jenkins logs to S3
  jenkins
Labels: size/L

#27 Route Status and Warnings
  frontend/__tests__/components/route-pages.spec.tsx
  frontend/public/components/_route.scss
  frontend/public/components/routes.tsx
  frontend/public/style.scss
Labels: lgtm, size/L

#55 Switch to two-column layout for route details
  frontend/public/components/routes.tsx
Labels: lgtm, size/M

#54 Wrap location with block element <div> so they don't word-break awkwardly in co-m-grid-table
  frontend/public/components/service.jsx
Labels: lgtm, size/XS

#59 Updates SS details:
  frontend/public/components/stateful-set.jsx
Labels: size/XS

#56 Route Namespace column and Traffic Table
  frontend/public/components/routes.tsx
Labels: lgtm, size/M

#5 Use Kubernetes Pagination for Lists
  frontend/__tests__/module/k8s/k8s-actions.spec.ts
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/utils/firehose.jsx
  frontend/public/module/k8s/k8s-actions.js
  frontend/public/module/k8s/k8s-reducers.ts
  frontend/public/module/k8s/k8s.js
  frontend/public/module/k8s/k8s.ts
Labels: size/L

#49 proxy: Add pings to websockets.
  pkg/proxy/proxy.go
Labels: lgtm, size/M

#60 State token in callback query is checked against state token in cookie
  auth/auth.go
  frontend/public/components/error.jsx
Labels: lgtm, size/M

#46 Prevent long resource names from causing layout to break
  frontend/public/components/_list.scss
  frontend/public/components/_resource.scss
  frontend/public/components/_sysevent-stream.scss
  frontend/public/components/pod.jsx
  frontend/public/components/utils/_selector.scss
  frontend/public/components/utils/nav-title.tsx
  frontend/public/style.scss
  frontend/public/style/_common.scss
  frontend/public/style/coreos.css
  frontend/public/style/mixin/_break-word.scss
Labels: lgtm, size/M

#44 Cleans up impersonation handling ...
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/impersonate-notifier.jsx
  frontend/public/module/k8s/k8s-actions.js
  frontend/public/ui/ui-actions.js
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/L

#48 frontend: Changes image for creation templates for openshift resources
  frontend/integration-tests/tests/filter.scenario.ts
  frontend/public/components/daemonset.jsx
  frontend/public/components/deployment.jsx
  frontend/public/components/pod.jsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/replication-controller.jsx
Labels: do-not-merge/hold, lgtm, size/M

#50 Copy to clipboard for secret and configMap data
  frontend/package.json
  frontend/public/components/configmap-and-secret-data.jsx
  frontend/public/components/utils/_copy-to-clipboard.scss
  frontend/public/components/utils/copy-to-clipboard.jsx
  frontend/public/components/utils/index.tsx
  frontend/public/style.scss
  frontend/yarn.lock
Labels: lgtm, size/M

#61 Rename all shell files to have .sh extensions.
  Dockerfile-builder
  README.md
  build
  build-backend.sh
  build-frontend.sh
  build.sh
  builder-run.sh
  clean
  clean-backend.sh
  clean-frontend.sh
  clean.sh
  git-version.sh
  jenkins
  jenkins.sh
  push-builder.sh
  push.sh
  revendor.sh
  test
  test-backend.sh
  test-frontend.sh
  test-gui.sh
  test.sh
Labels: size/L

#67 Move line-height:1 to .co-m-table-grid .row so that it doesn't effect .alert icon position
  frontend/public/components/_list.scss
  frontend/public/style/coreos.css
Labels: lgtm, size/XS

#66 Fixes a redirect bug that occurs after the user authenticates
  frontend/public/tokener.html
Labels: lgtm, size/XS

#69 Fixes race condition in watchK8sList...
  frontend/public/module/k8s/k8s-actions.js
Labels: lgtm, size/M

#70 Favor async/await over promise chains.
  frontend/public/module/k8s/k8s-actions.js
Labels: lgtm, size/M

#68 Routes List Status Filter
  frontend/__tests__/components/route-pages.spec.tsx
  frontend/public/components/factory/list.jsx
  frontend/public/components/routes.tsx
Labels: lgtm, size/M

#58 Load Testing ServiceWorker with Pagination
  cmd/bridge/main.go
  frontend/public/components/app.jsx
  frontend/public/load-test.sw.js
  server/server.go
Labels: lgtm, size/M

#71 Oops. Missed a .sh rename.
  push.sh
Labels: size/XS

#30 Implement build logs
  frontend/__tests__/line-buffer.js
  frontend/public/components/_pod-logs.scss
  frontend/public/components/_toggle-play.scss
  frontend/public/components/build-logs.jsx
  frontend/public/components/build.tsx
  frontend/public/components/pod-logs.jsx
  frontend/public/components/utils/_log-window.scss
  frontend/public/components/utils/_resource-log.scss
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/line-buffer.js
  frontend/public/components/utils/log-window.jsx
  frontend/public/components/utils/resource-log.jsx
  frontend/public/style.scss
Labels: lgtm, size/XL

#73 Fix Node Link on Container Detail View
  frontend/public/components/container.jsx
Labels: lgtm, size/XS

#74 Fix Broken Public Path for Fonts and Images in CSS
  frontend/webpack.config.ts
Labels: kind/bug, size/S

#80 Import Patternfly variables before Bootstrap
  frontend/public/style.scss
Labels: lgtm, size/XS

#82 Pin chrome driver version to fix GUI tests.
  Dockerfile-builder
  frontend/package.json
  test-gui.sh
Labels: size/S

#81 MultiDetailsPage
  frontend/__tests__/components/factory/details.spec.tsx
  frontend/public/components/factory/details.tsx
Labels: size/M

#26 OLM Subscription Manual Approval Flow
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/__tests__/components/cloud-services/install-plan.spec.tsx
  frontend/__tests__/components/cloud-services/subscription.spec.tsx
  frontend/__tests__/components/modals/installplan-approval-modal.spec.tsx
  frontend/__tests__/components/modals/subscription-channel-modal.spec.tsx
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/alm/update-channel-approval.scenario.ts
  frontend/public/components/cloud-services/index.tsx
  frontend/public/components/cloud-services/install-plan.tsx
  frontend/public/components/cloud-services/subscription.tsx
  frontend/public/components/factory/details.tsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/modals/installplan-approval-modal.tsx
  frontend/public/components/modals/subscription-channel-modal.tsx
  frontend/public/components/resource-pages.ts
Labels: size/XL

#85 Add HPA list and detail pages
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/public/components/hpa.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/resource-dropdown.tsx
  frontend/public/components/resource-pages.ts
  frontend/public/models/index.ts
Labels: lgtm, size/L

#86 Don't wrap ResourceLog in two co-m-pane__body divs.
  frontend/public/components/utils/resource-log.jsx
Labels: lgtm, size/XS
