Repository openshift/console, pull requests merged in 2018-11, with the labels that each got.

#719 Add labels list to Alert details and Silence details pages
  frontend/public/components/_monitoring.scss
  frontend/public/components/monitoring.tsx
  frontend/public/style/_text.scss
Labels: lgtm, size/S

#718 Fix for catalog tile text overflow, tree shaking pf react extensions
  frontend/package.json
  frontend/public/style/_overrides.scss
  frontend/yarn.lock
  sources
Labels: lgtm, size/M

#728 Disable overview tooltips on mobile
  frontend/public/components/overview/project-overview.tsx
  frontend/public/components/utils/tooltip.tsx
Labels: lgtm, size/S

#724 Move catalog content to its own folder
  frontend/public/components/app.jsx
  frontend/public/components/catalog/_catalog.scss
  frontend/public/components/catalog/catalog-item-details.jsx
  frontend/public/components/catalog/catalog-item-icon.tsx
  frontend/public/components/catalog/catalog-items.jsx
  frontend/public/components/catalog/catalog-page.jsx
  frontend/public/components/cluster-service-class-info.tsx
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
  frontend/public/components/source-to-image.tsx
  frontend/public/style.scss
Labels: lgtm, size/L

#731 Correct the sidebar tab alignment with edge of content
  frontend/public/components/_horizontal-nav.scss
Labels: lgtm, size/XS

#730 Fix bug where itemIconClass wasn't passed to <CatalogItemHeader>
  frontend/public/components/marketplace/marketplace-item-modal.jsx
Labels: lgtm, size/XS

#729 Bug 1644972: Go to the service binding page after creation
  frontend/public/components/service-catalog/create-binding.tsx
Labels: lgtm, size/XS

#732 Integration tests: wait for "Reveal Values" button
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/secrets.scenario.ts
  frontend/integration-tests/views/secrets.view.ts
Labels: lgtm, size/S

#643 Kubernetes Marketplace - FilterSidePanel
  frontend/public/components/marketplace/kubernetes-marketplace-items.jsx
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
Labels: lgtm, size/L

#733 Allow clicking overlay to close Marketplace modal
  frontend/public/components/marketplace/marketplace-item-modal.jsx
Labels: lgtm, size/XS

#736 Fix bug where uid was set to non-existent value
  frontend/public/components/marketplace/kubernetes-marketplace-items.jsx
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
  frontend/public/components/marketplace/marketplace-item-modal.jsx
Labels: lgtm, size/S

#739 Monitoring: Fix missing Actions menu on firing Alert details page
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#741 Monitoring: Correction for Create / Edit Silence page description text
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#735 Monitoring: Use "Not Firing" text instead of "Inactive"
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/S

#742 Monitoring: Remove unnecessary check for Silence state "inactive"
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#740 Monitoring: Change list header areas to better match non-Monitoring list pages
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/S

#684 OLM ClusterServiceVersion View Improvements
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/integration-tests/tests/olm/descriptors.scenario.ts
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/public/components/_horizontal-nav.scss
  frontend/public/components/conditions.tsx
  frontend/public/components/create-yaml.tsx
  frontend/public/components/factory/details.tsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/operator-lifecycle-manager/_operator-lifecycle-manager.scss
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
  frontend/public/components/utils/horizontal-nav.tsx
Labels: lgtm, size/XL

#654 Create PVC Form - Add form to Attach Storage
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/app.jsx
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/radio.jsx
  frontend/public/components/storage/attach-storage.tsx
  frontend/public/components/storage/create-pvc.tsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/request-size-input.tsx
Labels: lgtm, size/XL

#738 Monitoring: Prevent excess API calls on page transitions
  frontend/public/components/app.jsx
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/L

#721 Removing duplicate k8s-watcher
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/utils/firehose.jsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/k8s-watcher.js
Labels: lgtm, size/M

#613 Catalog unit and integration tests
  frontend/__mocks__/catalogItemsMocks.ts
  frontend/__tests__/components/catalog.spec.tsx
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/catalog.scenario.ts
  frontend/integration-tests/tests/olm/catalog.scenario.ts
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/integration-tests/tests/olm/update-channel-approval.scenario.ts
  frontend/integration-tests/views/catalog-page.view.ts
  frontend/integration-tests/views/catalog.view.ts
  frontend/integration-tests/views/olm-catalog.view.ts
  frontend/public/components/catalog/catalog-item-details.jsx
  frontend/public/components/catalog/catalog-items.jsx
  frontend/public/components/catalog/catalog-page.jsx
Labels: lgtm, size/XXL

#737 Add build configs/builds to overview details.
  frontend/public/components/build.tsx
  frontend/public/components/overview/_build-configs-overview.scss
  frontend/public/components/overview/build-configs-overview.tsx
  frontend/public/components/overview/daemon-set-overview.tsx
  frontend/public/components/overview/deployment-config-overview.tsx
  frontend/public/components/overview/deployment-overview.tsx
  frontend/public/components/overview/index.tsx
  frontend/public/components/overview/networking-overview.tsx
  frontend/public/components/overview/stateful-set-overview.tsx
  frontend/public/components/search.jsx
  frontend/public/components/utils/resource-link.jsx
  frontend/public/module/k8s/builds.ts
  frontend/public/style.scss
Labels: lgtm, size/L

#747 "Add to Workload" for secrets
  frontend/public/components/RBAC/_rbac.scss
  frontend/public/components/modals/add-secret-to-workload.tsx
  frontend/public/components/radio.jsx
  frontend/public/components/secret.jsx
  frontend/public/components/service-binding.tsx
  frontend/public/components/service-instance.tsx
  frontend/public/style/_common.scss
  frontend/public/style/_forms.scss
Labels: lgtm, size/L

#748 Design Fixes for ClusterServiceVersion Detail View
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/public/components/operator-lifecycle-manager/_operator-lifecycle-manager.scss
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
Labels: lgtm

#750 Remove 'zone' and 'zones' fields from aws-ebs storage class provisioner
  frontend/public/components/storage-class-form.tsx
Labels: lgtm, size/S

#753 Kubernetes Marketplace - Fix default logo to match OLM
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
Labels: lgtm, size/XS

#752 Add details about resources created for source-to-image
  frontend/public/components/catalog/_catalog.scss
  frontend/public/components/catalog/catalog-item-details.jsx
  frontend/public/components/source-to-image.tsx
Labels: lgtm, size/S

#749 Monitoring: Use the text "Expire Silence" instead of "Cancel Silence"
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#755 Remove _color-pallette.scss and replace those vars with PatternFly eq…
  frontend/public/components/_deploy-image.scss
  frontend/public/components/_dropdown.scss
  frontend/public/components/catalog/_catalog.scss
  frontend/public/components/factory/_modal-wrapper.scss
  frontend/public/components/utils/_status-box.scss
  frontend/public/style.scss
  frontend/public/style/_color-pallette.scss
  frontend/public/style/_common.scss
  frontend/public/style/_overrides.scss
  frontend/public/style/_status.scss
  frontend/public/style/_vars.scss
  frontend/public/style/coreos.css
  frontend/public/vendor.scss
Labels: lgtm, size/M

#432 Update cog menu
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/subscription.spec.tsx
  frontend/integration-tests/views/crud.view.ts
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/_list.scss
  frontend/public/components/_resource.scss
  frontend/public/components/build-config.tsx
  frontend/public/components/build.tsx
  frontend/public/components/chargeback.tsx
  frontend/public/components/client-tokens.jsx
  frontend/public/components/cluster-service-broker.tsx
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/cluster-service-plan.tsx
  frontend/public/components/clusters.tsx
  frontend/public/components/configmap.jsx
  frontend/public/components/cron-job.jsx
  frontend/public/components/custom-resource-definition.tsx
  frontend/public/components/daemon-set.jsx
  frontend/public/components/default-resource.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/hpa.tsx
  frontend/public/components/image-stream.tsx
  frontend/public/components/ingress.jsx
  frontend/public/components/job.jsx
  frontend/public/components/limit-range.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/network-policy.jsx
  frontend/public/components/node.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/install-plan.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/persistent-volume.jsx
  frontend/public/components/pod.jsx
  frontend/public/components/prometheus.jsx
  frontend/public/components/resource-quota.jsx
  frontend/public/components/routes.tsx
  frontend/public/components/secret.jsx
  frontend/public/components/service-account.jsx
  frontend/public/components/service-binding.tsx
  frontend/public/components/service-instance.tsx
  frontend/public/components/service-monitor.jsx
  frontend/public/components/service.jsx
  frontend/public/components/storage-class.tsx
  frontend/public/components/storage/attach-storage.tsx
  frontend/public/components/utils/cog.tsx
  frontend/public/style/coreos.css
Labels: lgtm, size/L

#765 Allow any decimal number in request size input component
  frontend/public/components/utils/request-size-input.tsx
Labels: lgtm, size/XS

#751 Bug 1646832 - Fix PVC creation selectors
  frontend/public/components/checkbox.tsx
  frontend/public/components/storage/create-pvc.tsx
Labels: lgtm, size/M

#776 Remove Check for OLM Enabled in a Given Namespace
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
Labels: lgtm, size/M

#772 Monitoring: Remove some redundant wrapping divs
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/S

#758 Replace custom color vars with PatternFly equivalents
  frontend/public/components/_cluster-overview.scss
  frontend/public/components/_dropdown.scss
  frontend/public/components/_horizontal-nav.scss
  frontend/public/components/_list.scss
  frontend/public/components/_nav-title.scss
  frontend/public/components/_row-filter.scss
  frontend/public/components/_sysevent-icon.scss
  frontend/public/components/_sysevent-stream.scss
  frontend/public/components/_toggle-play.scss
  frontend/public/components/catalog/_catalog.scss
  frontend/public/components/chargeback.tsx
  frontend/public/components/cluster-settings/_cluster-updates.scss
  frontend/public/components/operator-lifecycle-manager/_operator-lifecycle-manager.scss
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/components/overview/_overview.scss
  frontend/public/components/secrets/_create-secret.scss
  frontend/public/components/utils/_label.scss
  frontend/public/style/_common.scss
  frontend/public/style/_icons.scss
  frontend/public/style/_vars.scss
Labels: lgtm, size/L

#770 Fix pvc to only have storageClass property if not null
  frontend/public/components/storage/create-pvc.tsx
Labels: lgtm, size/XS

#773 Monitoring: After expiring a Silence, immediately refresh Silence data
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#768 Fix for Pod Log Fullscreen, toolbar has black background color
  frontend/public/components/utils/_resource-log.scss
Labels: lgtm, size/XS

#761 Var organization
  frontend/public/style.scss
  frontend/public/style/_config.scss
  frontend/public/style/_vars.scss
  frontend/public/vendor.scss
Labels: lgtm, size/L

#764 Changes from UX for attach-storage
  frontend/public/components/_storage-class-form.scss
  frontend/public/components/storage-class-form.tsx
  frontend/public/components/storage/attach-storage.tsx
  frontend/public/style/_forms.scss
Labels: lgtm, size/M

#771 Monitoring: Remove left margin on list row descriptions
  frontend/public/components/_monitoring.scss
Labels: lgtm, size/XS

#757 Revisions to overview-sidebar transition
  frontend/public/components/overview/_overview.scss
  frontend/public/components/overview/index.tsx
Labels: lgtm, size/S

#743 Monitoring: Change some state icons
  frontend/public/components/monitoring.tsx
  frontend/public/style/_icons.scss
Labels: lgtm, size/S

#778 Monitoring: Remove breadcrumbs from Alert Rule details page
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#780 Monitoring: Use "=~" instead of "=" for regex in Silence name
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#781 Monitoring: Fix identifying Alerts that are silenced by regex matchers
  frontend/public/components/monitoring.tsx
  frontend/public/monitoring.ts
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/S

#762 Remove coreos.css
  frontend/public/components/_list.scss
  frontend/public/components/_users.scss
  frontend/public/style.scss
  frontend/public/style/_base.scss
  frontend/public/style/_common.scss
  frontend/public/style/_overrides.scss
  frontend/public/style/coreos.css
Labels: lgtm, size/XL

#779 Monitoring: Update list page descriptions
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/S

#782 Monitoring: Minor refactor of alertURL() to just take an alert param
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#769 Cleanup overrides
  frontend/public/style/_common.scss
  frontend/public/style/_overrides.scss
  frontend/public/style/_vars.scss
Labels: lgtm, size/M

#767 Improve type specificity for overview related components
  frontend/public/components/overview/build-configs-overview.tsx
  frontend/public/components/overview/daemon-set-overview.tsx
  frontend/public/components/overview/deployment-config-overview.tsx
  frontend/public/components/overview/deployment-overview.tsx
  frontend/public/components/overview/index.tsx
  frontend/public/components/overview/networking-overview.tsx
  frontend/public/components/overview/project-overview.tsx
  frontend/public/components/overview/resource-overview-details.tsx
  frontend/public/components/overview/resource-overview-page.tsx
  frontend/public/components/overview/resource-overview-pages.tsx
  frontend/public/components/overview/stateful-set-overview.tsx
Labels: lgtm, size/L

#784 Fix bugs related to co-m-cog changes
  frontend/public/components/RBAC/_rbac.scss
  frontend/public/components/RBAC/rules.jsx
  frontend/public/components/_list.scss
  frontend/public/components/utils/cog.tsx
  frontend/public/style/_common.scss
Labels: lgtm, size/M

#785 Update PVC YAML template
  frontend/public/models/yaml-templates.ts
Labels: lgtm, size/XS

#759 Reset overview detail tab selection when details pane is dismissed
  frontend/public/components/overview/index.tsx
  frontend/public/components/overview/project-overview.tsx
  frontend/public/ui/ui-actions.js
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/L

#794 Monitoring: Link directly to Alertmanager UI's Silences page
  frontend/public/components/_monitoring.scss
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/S

#787 Allow Non-Virtualized Lists
  frontend/public/components/factory/list.tsx
  frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
Labels: lgtm, size/M

#791 Monitoring: Change sort by state to sort logically instead of alphabetically
  frontend/public/components/factory/list.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/monitoring.ts
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/M

#796 Jenkins: always exit on error
  jenkins.sh
Labels: lgtm, size/S

#793 Move ListDropdown into separate module
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/deploy-image.tsx
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/components/source-to-image.tsx
  frontend/public/components/storage/attach-storage.tsx
  frontend/public/components/storage/create-pvc.tsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/list-dropdown.jsx
Labels: lgtm, size/L

#797 Remove misnamed file
  frontend/public/components/service-catalog/shema-form.tsx
Labels: lgtm, size/M

#745 Add project details view toggle to overview
  frontend/integration-tests/tests/deploy-image.scenario.ts
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/public/components/_cluster-overview.scss
  frontend/public/components/app.jsx
  frontend/public/components/cluster-overview.jsx
  frontend/public/components/graphs/health.jsx
  frontend/public/components/namespace.jsx
  frontend/public/components/nav.jsx
  frontend/public/components/overview/_overview.scss
  frontend/public/components/overview/index.tsx
  frontend/public/components/overview/namespace-overview.tsx
  frontend/public/style/_common.scss
  frontend/public/ui/ui-actions.js
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/XL

#798 Monitoring: Refactor away asRules and asAlerts for storing alerts
  frontend/public/components/monitoring.tsx
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/S

#713 Persisting Catalog category and filter selections in url
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/catalog.scenario.ts
  frontend/integration-tests/views/catalog.view.ts
  frontend/package.json
  frontend/public/components/app.jsx
  frontend/public/components/catalog/catalog-items.jsx
  frontend/yarn.lock
  sources
Labels: lgtm, size/L

#800 Upgrade to React 16.6.3
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/package-manifest.spec.tsx
  frontend/package.json
  frontend/public/components/factory/list.tsx
  frontend/public/components/factory/modal.tsx
  frontend/yarn.lock
  sources
Labels: lgtm, size/M

#760 Investigate adding ErrorBoundry to ListView
  frontend/public/components/error.tsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/utils/_copy-to-clipboard.scss
  frontend/public/components/utils/error-boundary.tsx
  frontend/public/vendor.scss
Labels: lgtm, size/M

#799 Rework overview-tool bar so it remains a single row.
  frontend/public/components/_nav-title.scss
  frontend/public/components/overview/_overview.scss
  frontend/public/components/overview/index.tsx
  frontend/public/style/_overrides.scss
Labels: lgtm, size/M

#810 Add "Application" and "Resource" overview groups
  frontend/public/components/overview/index.tsx
  frontend/public/components/overview/project-overview.tsx
Labels: lgtm, size/L

#818 Only show Builds nav section on OpenShift
  frontend/public/components/nav.jsx
Labels: lgtm, size/XS

#816 Don't open overview sidebar when clicking link inside list
  frontend/public/components/overview/project-overview.tsx
Labels: lgtm, size/S

#809 container section alignment issue in demon-sets workload
  frontend/public/components/daemon-set.jsx
Labels: lgtm, size/S

#815 Monitoring: Remove Runbook links
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#795 Monitoring: Store which Silences affect which Alerts in Redux
  frontend/public/components/factory/list.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/M

#806 Correctly patch existing arrays when adding secret to workload
  frontend/public/components/modals/add-secret-to-workload.tsx
Labels: lgtm, size/M

#827 Set CatalogSource Namespace Correctly when Creating OLM Subscription
  frontend/__tests__/components/operator-lifecycle-manager/catalog-source.spec.tsx
  frontend/public/components/operator-lifecycle-manager/catalog-source.tsx
Labels: lgtm, size/S

#825 Fix bug where bottom margin was missing from nav sections
  frontend/public/components/_nav.scss
  frontend/public/components/nav.jsx
Labels: lgtm, size/S

#789 Remove Tectonic Settings Components
  frontend/__tests__/cluster-settings.js
  frontend/__tests__/features.spec.tsx
  frontend/public/components/alert-manager.tsx
  frontend/public/components/app.jsx
  frontend/public/components/cluster-settings/_cluster-settings.scss
  frontend/public/components/cluster-settings/_cluster-updates.scss
  frontend/public/components/cluster-settings/certs-info.jsx
  frontend/public/components/cluster-settings/cluster-monitoring.jsx
  frontend/public/components/cluster-settings/cluster-settings.jsx
  frontend/public/components/cluster-settings/ldap.jsx
  frontend/public/components/cluster-settings/settings-modal-link.jsx
  frontend/public/features.ts
  frontend/public/style.scss
  server/server.go
Labels: lgtm, size/XXL

#830 Monitoring: Fix layout of Silence form start / end time inputs
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/S

#722 Add help menu and PF About Modal
  frontend/public/components/_masthead.scss
  frontend/public/components/masthead.tsx
  frontend/public/components/utils/about-modal.tsx
  frontend/public/components/utils/dropdown.jsx
  frontend/public/imgs/bg-modal-about.png
  frontend/public/imgs/okd-logo-modal.svg
  frontend/public/imgs/redhat-logo-modal.svg
  frontend/public/style/_vars.scss
  frontend/public/vendor.scss
Labels: lgtm, size/L

#829 Monitoring: Improve Alert and Silence state descriptions
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/M

#820 Add exit code to container state in pod detail/pod container detail pages.
  frontend/public/components/container.jsx
  frontend/public/components/pod.jsx
  frontend/public/module/k8s/docker.js
Labels: lgtm, size/S

#835 Monitoring: Fix sidebar "Alerts" entry to be highlighted on Rule page
  frontend/public/components/nav.jsx
Labels: lgtm, size/XS

#804 Add Error Boundary for details pages
  frontend/__tests__/components/factory/details.spec.tsx
  frontend/public/components/error.tsx
  frontend/public/components/factory/details.tsx
Labels: lgtm, size/S

#834 Monitoring: Improve object not found error messages
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/M

#822 Monitoring: Fix alignment of Create Silence form's "Value" heading
  frontend/public/components/_monitoring.scss
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#814 Add log snippets and status message to failed/errored builds in overview
  frontend/public/components/_build-pipeline.scss
  frontend/public/components/build-logs.jsx
  frontend/public/components/build-pipeline.tsx
  frontend/public/components/build.tsx
  frontend/public/components/overview/_build-configs-overview.scss
  frontend/public/components/overview/_build-overview.scss
  frontend/public/components/overview/build-configs-overview.tsx
  frontend/public/components/overview/build-overview.tsx
  frontend/public/components/overview/resource-overview-page.tsx
  frontend/public/module/k8s/builds.ts
  frontend/public/style.scss
  frontend/public/style/_vars.scss
Labels: lgtm, size/L

#821 Remove noButton option from dropdown to fix accessibility issue
  frontend/integration-tests/views/namespace.view.ts
  frontend/integration-tests/views/search.view.ts
  frontend/public/components/_cluster-picker.scss
  frontend/public/components/_dropdown.scss
  frontend/public/components/_masthead.scss
  frontend/public/components/cluster-picker.tsx
  frontend/public/components/masthead.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/utils/dropdown.jsx
Labels: lgtm, size/L

#836 Remove top border inherited from PatternFly from masthead
  frontend/public/style/_overrides.scss
  frontend/public/style/_vars.scss
Labels: lgtm, size/XS

#819 Fix preselected items in ListDropdown
  frontend/public/components/utils/list-dropdown.jsx
Labels: lgtm, size/XS

#807 Redirect to project overview when creating a project
  frontend/integration-tests/tests/base.scenario.ts
  frontend/public/components/modals/create-namespace-modal.jsx
Labels: lgtm, size/S

#841 Monitoring: Fix Silence form error catch to not assume a JSON response
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#746 Indicate deployments/deployment configs are paused
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.jsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/workload-pause.tsx
Labels: lgtm, size/M

#837 Bump chromedriver to version 2.43.3
  Dockerfile.product
  frontend/package.json
  frontend/yarn.lock
  sources
Labels: lgtm, size/L

#842 eslint: enforce prefer-const
  frontend/.eslintrc
  frontend/__tests__/components/create-yaml.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/create-crd-yaml.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/package-manifest.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/subscription.spec.tsx
  frontend/integration-tests/protractor.conf.ts
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/app.jsx
  frontend/public/components/catalog/catalog-items.jsx
  frontend/public/components/channel-operators/app-version.jsx
  frontend/public/components/container.jsx
  frontend/public/components/environment.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
  frontend/public/components/modals/installplan-approval-modal.tsx
  frontend/public/components/modals/subscription-channel-modal.tsx
  frontend/public/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.tsx
  frontend/public/components/resource-quota.jsx
  frontend/public/components/routes.tsx
  frontend/public/components/secrets/create-secret.tsx
  frontend/public/components/sidebars/resource-sidebar.jsx
  frontend/public/components/storage-class-form.tsx
  frontend/public/components/utils/container-linux-update-operator.js
  frontend/public/components/utils/firehose.jsx
  frontend/public/components/utils/line-buffer.ts
  frontend/public/components/utils/link.jsx
  frontend/public/components/utils/operator-states.jsx
  frontend/public/components/utils/resource-log.jsx
  frontend/public/components/utils/timestamp.jsx
  frontend/public/components/utils/units.js
  frontend/public/features.ts
  frontend/public/module/k8s/k8s-reducers.ts
  frontend/public/module/k8s/label-selector.js
  frontend/public/module/k8s/pods.ts
  frontend/public/module/k8s/probe.js
  frontend/public/module/k8s/selector-requirement.js
  frontend/webpack.config.ts
Labels: lgtm, size/L

#843 Remove contextselector
  cmd/bridge/config.go
  cmd/bridge/main.go
  frontend/public/components/_masthead.scss
  frontend/public/components/masthead.tsx
  frontend/public/components/utils/dropdown.jsx
  frontend/public/style/_layout.scss
  frontend/public/style/_vars.scss
  frontend/public/vendor.scss
  server/server.go
Labels: lgtm, size/M

#844 Accept any node for ActionsMenu label
  frontend/public/components/utils/dropdown.jsx
Labels: lgtm, size/XS

#831 Remove obsolete cluster picker
  frontend/__tests__/features.spec.tsx
  frontend/integration-tests/views/sidenav.view.ts
  frontend/public/components/_cluster-picker.scss
  frontend/public/components/cluster-picker.tsx
  frontend/public/components/clusters.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/resource-pages.ts
  frontend/public/features.ts
  frontend/public/models/index.ts
  frontend/public/models/yaml-templates.ts
  frontend/public/style.scss
Labels: lgtm, size/L

#839 Only add 'open' to .dropdown className if 'nav-item-iconic'
  frontend/public/components/utils/dropdown.jsx
Labels: lgtm, size/XS

#832 Add list and details pages for machines and machine sets
  frontend/__tests__/features.spec.tsx
  frontend/public/components/_resource.scss
  frontend/public/components/machine-set.tsx
  frontend/public/components/machine.tsx
  frontend/public/components/modals/configure-count-modal.jsx
  frontend/public/components/nav.jsx
  frontend/public/components/node.tsx
  frontend/public/components/resource-pages.ts
  frontend/public/components/utils/details-page.tsx
  frontend/public/components/utils/horizontal-nav.tsx
  frontend/public/features.ts
  frontend/public/models/index.ts
  frontend/public/module/k8s/index.ts
  frontend/public/style/_text.scss
Labels: lgtm, size/L

#848 [release-3.11] Downstream build updates
  Dockerfile.product
  Dockerfile.product.nodejs
  frontend/package.json
  frontend/yarn.lock
  sources
Labels: lgtm, size/L

#850 Remove sources file
  sources
Labels: lgtm, size/XS

#846 Fix bug where very long usernames did not truncate
  frontend/public/components/_masthead.scss
Labels: lgtm, size/S

#852 Add units utilities for comparing resource quota values
  frontend/__tests__/units.js
  frontend/public/components/cluster-health.jsx
  frontend/public/components/utils/units.js
Labels: lgtm, size/L

#824 Remove user input for Volume Name and auto generate instead
  frontend/public/components/storage/attach-storage.tsx
Labels: lgtm, size/M

#853 Improve Overview types
  frontend/public/components/overview/index.tsx
  frontend/public/components/overview/project-overview.tsx
Labels: lgtm, size/L

#854 Adjust kebab and dropdown menu to align with PF kebab dropdowns
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/RBAC/rules.jsx
  frontend/public/components/_list.scss
  frontend/public/components/build-config.tsx
  frontend/public/components/build.tsx
  frontend/public/components/chargeback.tsx
  frontend/public/components/cluster-service-broker.tsx
  frontend/public/components/configmap.jsx
  frontend/public/components/cron-job.jsx
  frontend/public/components/custom-resource-definition.tsx
  frontend/public/components/daemon-set.jsx
  frontend/public/components/default-resource.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/hpa.tsx
  frontend/public/components/image-stream.tsx
  frontend/public/components/ingress.jsx
  frontend/public/components/job.jsx
  frontend/public/components/limit-range.tsx
  frontend/public/components/machine-set.tsx
  frontend/public/components/machine.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/network-policy.jsx
  frontend/public/components/node.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/install-plan.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/persistent-volume.jsx
  frontend/public/components/pod.jsx
  frontend/public/components/prometheus.jsx
  frontend/public/components/resource-quota.jsx
  frontend/public/components/routes.tsx
  frontend/public/components/secret.jsx
  frontend/public/components/service-account.jsx
  frontend/public/components/service-binding.tsx
  frontend/public/components/service-instance.tsx
  frontend/public/components/service-monitor.jsx
  frontend/public/components/service.jsx
  frontend/public/components/storage-class.tsx
  frontend/public/components/utils/kebab.tsx
  frontend/public/style/_common.scss
Labels: lgtm, size/L

#856 Monitoring: Fix key attribute for Silence matchers
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#855 Store overview metrics in Redux
  frontend/public/components/overview/index.tsx
  frontend/public/components/overview/project-overview.tsx
  frontend/public/ui/ui-actions.js
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/M

#864 Fix Unmounting Lazy Routes when Query Params Change
  .gitignore
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/public/components/app.jsx
Labels: lgtm, size/M

#860 Fix error handling in storage class creation
  frontend/public/components/storage-class-form.tsx
Labels: lgtm, size/XS

#828 Added Resource Usage section to Resource Quota Details page
  frontend/public/components/_quota.scss
  frontend/public/components/resource-quota.jsx
  frontend/public/style.scss
Labels: lgtm, size/M

#863 Add wrapping class to so that resource icon and link wrapping behavior is the same as <ResourceLink>
  frontend/public/components/custom-resource-definition.tsx
  frontend/public/components/namespace.jsx
Labels: lgtm, size/S

#867 Add attach storage to daemon set and stateful set
  frontend/public/components/daemon-set.jsx
  frontend/public/components/stateful-set.jsx
  frontend/public/components/storage/attach-storage.tsx
Labels: lgtm, size/XS

#858 Fix StorageClass default status under cluster-console overview
  frontend/public/components/storage-class.tsx
Labels: lgtm, size/XS

#861 Avoid unnecessary project lists for cluster readers
  frontend/public/components/modals/create-namespace-modal.jsx
  frontend/public/components/namespace.jsx
  frontend/public/components/nav.jsx
  frontend/public/components/search.jsx
  frontend/public/components/start-guide.tsx
  frontend/public/features.ts
Labels: lgtm, size/L

#862 Add Label Selector for "Hiding" Certain OLM Packages
  frontend/__tests__/components/operator-lifecycle-manager/catalog-source.spec.tsx
  frontend/public/components/factory/details.tsx
  frontend/public/components/operator-lifecycle-manager/catalog-source.tsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
  frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
  frontend/public/module/k8s/index.ts
  frontend/public/module/k8s/selector.ts
Labels: lgtm, size/M

#805 Add categorization to marketplace page
  frontend/__mocks__/catalogItemsMocks.ts
  frontend/__tests__/components/catalog.spec.tsx
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/public/components/catalog/catalog-item-details.jsx
  frontend/public/components/catalog/catalog-items.jsx
  frontend/public/components/marketplace/kubernetes-marketplace-items.jsx
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
  frontend/public/components/marketplace/marketplace-item-modal.jsx
  frontend/public/components/nav.jsx
  frontend/public/components/utils/categorize-catalog-items.ts
  frontend/public/components/utils/tile-view-page.jsx
Labels: lgtm, size/XXL

#873 Remove unused CALICO flag
  frontend/public/features.ts
Labels: lgtm, size/S

#872 Monitoring: Fix handling of Alert state changes on details page & refactoring
  frontend/public/components/monitoring.tsx
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/M

#868 Monitoring: Get monitoring UI URLs from ConfigMap
  frontend/public/components/app.jsx
  frontend/public/features.ts
  frontend/public/monitoring.ts
Labels: lgtm, size/M

#878 Show only necessary columns for NetworkPolicy and LimitRange lists on mobile
  frontend/public/components/limit-range.tsx
  frontend/public/components/network-policy.jsx
Labels: lgtm, size/S

#876 Monitoring: Small clean up of poller code
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/M

#877 Monitoring: Fix "Silenced" state not being shown in Active Alerts list
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/XS

#823 Monitoring e2e tests
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/monitoring.scenario.ts
  frontend/integration-tests/views/monitoring.view.ts
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/L

#880 Use `lodash-es` instead of `lodash` for storage class form
  frontend/public/components/storage-class-form.tsx
Labels: lgtm, size/XS

#881 eslint: disallow lodash imports (use lodash-es instead)
  frontend/public/.eslintrc
Labels: lgtm, size/S

#879 Address filter bar usability issues
  frontend/public/components/_row-filter.scss
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/row-filter.jsx
Labels: lgtm, size/M

#884 Reduce tile view pages chunk size, fix minor display issues
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/package.json
  frontend/public/components/catalog/_catalog.scss
  frontend/public/components/catalog/catalog-page.jsx
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
  frontend/public/components/utils/firehose.jsx
  frontend/public/components/utils/tile-view-page.jsx
  frontend/public/style/_overrides.scss
  frontend/yarn.lock
Labels: lgtm, size/L

#887 Correctly set default alignment of css grid elements within project-overview__additional-info
  frontend/public/components/overview/_project-overview.scss
Labels: lgtm, size/XS

#885 Load name value editor as an async component
  frontend/public/components/environment.jsx
  frontend/public/components/modals/tags.jsx
  frontend/public/components/storage-class-form.tsx
  frontend/public/components/storage/create-pvc.tsx
  frontend/public/components/utils/index.tsx
Labels: lgtm, size/M

#866 Add initial cluster settings page for OpenShift
  frontend/public/components/_masthead.scss
  frontend/public/components/app.jsx
  frontend/public/components/cluster-settings/cluster-operator.tsx
  frontend/public/components/cluster-settings/cluster-settings.tsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/masthead.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/resource-pages.ts
  frontend/public/components/utils/horizontal-nav.tsx
  frontend/public/features.ts
  frontend/public/models/index.ts
Labels: lgtm, size/L
