Repository openshift/console, pull requests merged in 2018-12, with the labels that each got.

#711 Bug 1605136 - Let users clear default fields with template service broker
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/components/service-catalog/schema-form.tsx
Labels: lgtm, size/M

#891 Remove stray semicolon from cluster settings page
  frontend/public/components/cluster-settings/cluster-settings.tsx
Labels: lgtm, size/XS

#890 Fix "Select All Filters" link jump when disabled
  frontend/public/components/_row-filter.scss
Labels: lgtm, size/XS

#811 Fixed alignment of container and pod Volumes in pods page
  frontend/public/components/pod.jsx
Labels: lgtm, size/M

#895 Warn when logged in as temporary admin user
  frontend/public/components/_global-notification.scss
  frontend/public/components/global-notifications.jsx
  frontend/public/components/kube-admin-notifier.jsx
  frontend/public/components/masthead.tsx
  frontend/public/const.js
  frontend/public/features.ts
  frontend/public/ui/ui-actions.js
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/M

#900 Validate that OAuth URLs are absolute
  auth/auth_openshift.go
Labels: lgtm, size/S

#902 Change events messages from headline style to sentence style
  frontend/public/components/events.jsx
Labels: lgtm, size/XS

#899 Update filter background color
  frontend/public/components/_row-filter.scss
Labels: lgtm, size/XS

#671 Kubernetes Marketplace - Integration and unit tests for Marketplace UI
  frontend/__mocks__/marketplaceItemsMocks.ts
  frontend/__tests__/components/marketplace/kubernetes-marketplace.spec.tsx
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/catalog.scenario.ts
  frontend/integration-tests/tests/marketplace/kubernetes-marketplace.scenario.ts
  frontend/integration-tests/views/catalog-page.view.ts
  frontend/integration-tests/views/kubernetes-marketplace.view.ts
  frontend/public/components/marketplace/kubernetes-marketplace-items.jsx
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
  frontend/public/components/marketplace/marketplace-item-modal.jsx
Labels: lgtm, size/XL

#904 Bug 1656743 - ResourceQuota and LimitRange pages should remove the 'Pod Selector' on the detail page.
  frontend/public/components/limit-range.tsx
  frontend/public/components/resource-quota.jsx
Labels: lgtm, size/XS

#893 Update create flow for pvc, routes, storage classes.
  frontend/__tests__/components/storage-class-form.spec.tsx
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/routes.tsx
  frontend/public/components/routes/create-route.tsx
  frontend/public/components/storage-class-form.tsx
  frontend/public/components/storage-class.tsx
  frontend/public/components/storage/create-pvc.tsx
Labels: lgtm, size/M

#897 Implement cluster update workflow
  frontend/public/components/_masthead.scss
  frontend/public/components/cluster-settings/cluster-settings.tsx
  frontend/public/components/masthead.tsx
  frontend/public/components/modals/_modals.scss
  frontend/public/components/modals/cluster-update-modal.tsx
  frontend/public/components/modals/index.ts
  frontend/public/features.ts
  frontend/public/style/_vars.scss
Labels: lgtm, size/L

#903 Add generic "OpenShift" branding option and make it default
  cmd/bridge/main.go
  frontend/public/branding.ts
  frontend/public/components/masthead.tsx
  frontend/public/imgs/openshift-logo.svg
  frontend/public/index.html
  frontend/public/tokener.html
Labels: lgtm, size/L

#906 Tighten the validation around OAuth URLs
  auth/auth_openshift.go
Labels: lgtm, size/S

#912 Kubernetes Marketplace - fix to only display operators in the openshift-marketplace namespace
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
Labels: lgtm, size/XS

#908 Bug 1656704 - Fix edit annotations dialog for CRDs
  frontend/public/components/utils/details-page.tsx
Labels: lgtm, size/S

#913 Add basic support for cluster autoscaler
  frontend/public/components/cluster-settings/cluster-settings.tsx
  frontend/public/models/index.ts
  frontend/public/models/yaml-templates.ts
Labels: lgtm, size/M

#907 Monitoring: Fix Pending / Silenced state display in Active Alerts list
  frontend/public/components/monitoring.tsx
  frontend/public/ui/ui-reducers.js
Labels: lgtm

#910 Fix temporary admin message
  frontend/public/components/kube-admin-notifier.jsx
Labels: lgtm

#923 Monitoring: Allow single digit months, days and hours in Silence times
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/S

#882 Adjustments to project status filters for improved display at responsive sizes and sidebar open.
  frontend/public/components/_nav-title.scss
  frontend/public/components/overview/_overview.scss
  frontend/public/components/overview/index.tsx
  frontend/public/style/_overrides.scss
Labels: lgtm, size/L

#918 Lightly Expose OLM Operator Groups
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/__tests__/components/operator-lifecycle-manager/catalog-source.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/operator-group.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/package-manifest.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/subscription.spec.tsx
  frontend/integration-tests/tests/base.scenario.ts
  frontend/integration-tests/tests/olm/catalog.scenario.ts
  frontend/public/components/conditions.tsx
  frontend/public/components/operator-lifecycle-manager/catalog-source.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
  frontend/public/components/operator-lifecycle-manager/install-plan.tsx
  frontend/public/components/operator-lifecycle-manager/operator-group.tsx
  frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/components/utils/status-box.jsx
  frontend/public/models/index.ts
Labels: lgtm, size/L

#927 Fix bug where .co-m-overflow__gradient is the wrong color
  frontend/public/components/_overflow.scss
  frontend/public/style/_common.scss
  frontend/public/style/_vars.scss
Labels: lgtm, size/XS

#928 Fix bug where Pod Volumes table rows were busted
  frontend/public/components/pod.jsx
Labels: lgtm, size/XS

#929 Fix bug where probe URLs may lack `/`
  frontend/public/module/k8s/probe.js
Labels: lgtm, size/XS

#931 Monitoring: Guard against undefined Monitoring data in Redux
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#930 Fix type of currentSortFunc (it's actually a string, not a function)
  frontend/public/components/factory/list.tsx
Labels: lgtm, size/XS

#925 Bug 1656719 - Correctly handle machine set count of zero
  frontend/public/components/machine-set.tsx
Labels: lgtm, size/S

#898 Add Cluster Settings > Global Config page
  frontend/public/components/cluster-settings/cluster-settings.tsx
  frontend/public/components/cluster-settings/global-config.tsx
  frontend/public/module/k8s/get-resources.ts
  frontend/public/module/k8s/k8s-reducers.ts
Labels: lgtm, size/M

#935 Ensure OLM CatalogSource View Requires OperatorGroup
  frontend/__tests__/components/operator-lifecycle-manager/catalog-source.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
  frontend/public/components/custom-resource-definition.tsx
  frontend/public/components/operator-lifecycle-manager/catalog-source.tsx
  frontend/public/components/operator-lifecycle-manager/install-plan.tsx
  frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
Labels: lgtm, size/M

#924 Kubernetes Marketplace - disable marketplace nav and route
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/public/components/app.jsx
  frontend/public/components/nav.jsx
Labels: lgtm, size/S

#892 Resource Quota Details: Charts, Scopes, Quota Help InfoTip
  frontend/public/components/_quota.scss
  frontend/public/components/graphs/base.jsx
  frontend/public/components/graphs/gauge.jsx
  frontend/public/components/resource-quota.jsx
  frontend/public/components/utils/documentation.tsx
Labels: lgtm, size/L

#917 Monitoring: Show matching alerts for all silences & improve UX when API calls have not all completed
  frontend/public/components/factory/list.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/monitoring.ts
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/M

#934 Pod status links on overview page now link to RC/RS pod tab
  frontend/public/components/overview/project-overview.tsx
Labels: lgtm, size/XS

#937 Fix the Cluster Status page's Health links to use Link
  frontend/public/components/graphs/health.jsx
  frontend/public/components/graphs/status.jsx
Labels: lgtm, size/XS

#938 Monitoring: Fix sidebar external links when -base-path is set
  frontend/public/components/nav.jsx
Labels: lgtm, size/S

#941 Bug 1656730 - Remove `customresourcedefinitions` from CRD paths
  frontend/public/components/app.jsx
  frontend/public/components/custom-resource-definition.tsx
  frontend/public/components/resource-list.tsx
Labels: lgtm, size/XS

#942 Filter Marketplace CatalogSources from OLM View
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
  frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
Labels: lgtm, size/XS

#940 Monitoring: Change Edit action to Recreate for expired Silences
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#949 Disable `gecko` for webdriver update to avoid Github rate limit errors
  frontend/package.json
Labels: lgtm, size/XS

#950 Reduce main bundle size
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
  frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
  frontend/public/const.js
Labels: lgtm, size/S

#946 Monitoring: Use LazyRoute for all monitoring pages
  frontend/public/components/app.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/monitoring.ts
Labels: lgtm, size/S

#875 Kubernetes Marketplace - Add subscribe page (take 2)
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/public/components/app.jsx
  frontend/public/components/marketplace/kubernetes-marketplace-items.jsx
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
  frontend/public/components/marketplace/marketplace-item-modal.jsx
  frontend/public/components/nav.jsx
  frontend/public/features.ts
  frontend/public/models/index.ts
Labels: lgtm, size/L

#954 Bug fix - use functions not function calls in .then()
  frontend/public/components/marketplace/marketplace-item-modal.jsx
Labels: lgtm, size/XS

#955 Monitoring: Improve sort by state column on list pages
  frontend/public/components/factory/list.tsx
  frontend/public/monitoring.ts
Labels: lgtm, size/S

#944 Implement e2e tests for Overview
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/overview/overview.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/integration-tests/views/overview.view.ts
Labels: lgtm, size/M

#951 Implement more useful empty state for overview page
  frontend/public/components/catalog/_catalog.scss
  frontend/public/components/overview/index.tsx
  frontend/public/style/_overrides.scss
Labels: lgtm, size/M

#952 Fix ListDropdown selection bug
  frontend/public/components/utils/list-dropdown.jsx
Labels: lgtm, size/M

#959 Fix CRD links where kind matches a different static model
  frontend/public/module/k8s/k8s-models.ts
Labels: lgtm, size/XS

#943 Firehose resources are considered loaded only once all optional resources have either loaded or errored.
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/utils/firehose.jsx
Labels: lgtm, size/XS

#966 Enable gzip compression of static files
  server/middleware.go
  server/server.go
Labels: lgtm, size/M

#961 Form consistency changes per Form Guidelines design doc.
  frontend/public/components/RBAC/_rbac.scss
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/_dropdown.scss
  frontend/public/components/deploy-image.tsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/modals/create-namespace-modal.jsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/routes/create-route.tsx
  frontend/public/components/secrets/create-secret.tsx
  frontend/public/components/service-catalog/create-binding.tsx
  frontend/public/components/storage-class-form.tsx
  frontend/public/components/storage/attach-storage.tsx
  frontend/public/components/storage/create-pvc.tsx
  frontend/public/components/utils/dropdown.jsx
  frontend/public/components/utils/list-dropdown.jsx
  frontend/public/style/_common.scss
  frontend/public/style/_forms.scss
Labels: lgtm, size/L

#969 Keep sidebar dropshadow at mobile
  frontend/public/style/_overrides.scss
Labels: lgtm, size/XS

#980 Avoid StaleElementReferenceError in OLM e2e tests
  frontend/integration-tests/tests/olm/descriptors.scenario.ts
  frontend/integration-tests/views/olm-catalog.view.ts
Labels: lgtm, size/XS

#982 Add object-shorthand to linter
  STYLEGUIDE.md
  frontend/.eslintrc
  frontend/__tests__/components/factory/list-page.spec.tsx
  frontend/integration-tests/tests/secrets.scenario.ts
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/channel-operators/app-version.jsx
  frontend/public/components/channel-operators/detail-status.jsx
  frontend/public/components/channel-operators/tectonic-channel.jsx
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
  frontend/public/components/modals/configure-operator-modal.jsx
  frontend/public/components/operator-lifecycle-manager/descriptors/spec/configure-size.tsx
  frontend/public/components/secrets/create-secret.tsx
  frontend/public/components/service-account.jsx
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/components/sidebars/resource-sidebar.jsx
  frontend/public/components/source-to-image.tsx
  frontend/public/components/storage-class-form.tsx
  frontend/public/components/storage/attach-storage.tsx
  frontend/public/components/utils/dropdown.jsx
  frontend/public/components/utils/horizontal-nav.tsx
  frontend/public/components/utils/kebab.tsx
  frontend/public/components/utils/log-window.jsx
  frontend/public/components/utils/value-from-pair.jsx
  frontend/public/module/analytics.js
  frontend/public/module/k8s/label-selector.js
  frontend/public/module/k8s/probe.js
  frontend/public/module/k8s/selector-requirement.js
  frontend/public/module/k8s/service-catalog.ts
Labels: lgtm, size/L

#968 Remove :hover from active nav item
  frontend/public/style/_overrides.scss
Labels: lgtm, size/XS

#970 Remove separators from button styled secondary actions in EmptyState component
  frontend/public/components/overview/index.tsx
  frontend/public/style/_overrides.scss
Labels: lgtm, size/S

#971 Fix bug where mobile dropdown menu items were missing
  frontend/public/components/masthead-toolbar.jsx
Labels: lgtm, size/XS

#965 Bump webpack-bundle-analyzer
  frontend/package.json
  frontend/yarn.lock
Labels: lgtm, size/L

#967 Don't show overview empty state message for system namespaces
  frontend/public/components/overview/index.tsx
Labels: lgtm, size/XS

#939 Add logging URL to console nav
  frontend/public/components/nav.jsx
  frontend/public/features.ts
  frontend/public/monitoring.ts
Labels: lgtm, size/S

#979 remove unnecesary passing of resources in Firehose
  frontend/public/components/utils/firehose.jsx
Labels: lgtm, ok-to-test, size/XS

#870 Update status icons & labels as specified by Patternfly recommendations
  frontend/__tests__/components/route-pages.spec.tsx
  frontend/public/components/build-pipeline.tsx
  frontend/public/components/build.tsx
  frontend/public/components/container.jsx
  frontend/public/components/custom-resource-definition.tsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.jsx
  frontend/public/components/job.jsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/node.tsx
  frontend/public/components/operator-lifecycle-manager/install-plan.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/pod.jsx
  frontend/public/components/routes.tsx
  frontend/public/components/software-details.jsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/service-catalog-status.tsx
  frontend/public/components/utils/status-icon.tsx
  frontend/public/style/_icons.scss
Labels: lgtm, size/L

#988 Bug 1661086 - Don't set empty storage class description annotation
  frontend/public/components/storage-class-form.tsx
Labels: lgtm, size/S

#987 Bug 1661099 - Fix fullscreen terminal
  frontend/public/style/_overrides.scss
Labels: lgtm, size/XS

#973 Add Operator-Provided APIs to Uber Catalog
  frontend/public/components/catalog/catalog-item-details.jsx
  frontend/public/components/catalog/catalog-items.jsx
  frontend/public/components/catalog/catalog-page.jsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
Labels: lgtm, size/M

#986 Bug 1661145 - Make insecure termination policy optional for routes
  frontend/public/components/routes/create-route.tsx
Labels: lgtm, size/XS

#984 Kubernetes Marketplace - Add subscribe page flow
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/__mocks__/marketplaceItemsMocks.ts
  frontend/__tests__/components/marketplace/kubernetes-marketplace.spec.tsx
  frontend/__tests__/components/modals/subscription-channel-modal.spec.tsx
  frontend/public/components/app.jsx
  frontend/public/components/marketplace/index.ts
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
  frontend/public/components/marketplace/marketplace-item-modal.jsx
  frontend/public/components/marketplace/marketplace-item-modal.tsx
  frontend/public/components/marketplace/marketplace-items.tsx
  frontend/public/components/marketplace/marketplace-page.tsx
  frontend/public/components/marketplace/marketplace-subscribe.tsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
  frontend/public/components/operator-lifecycle-manager/operator-group.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
Labels: lgtm, size/XXL

#992 Add 'Enabled' indicator to marketplace items
  frontend/package.json
  frontend/public/components/marketplace/marketplace-items.tsx
  frontend/yarn.lock
Labels: lgtm, size/M

#956 Monitoring: Hide kebab menu for silenced alerts in Active Alerts list
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/XS

#993 Monitoring: Add info alert to explain how editing a silence works
  frontend/public/components/monitoring.tsx
Labels: lgtm, size/S

#948 Update Nav to avoid confusion between Catalog and Service Catalog
  frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/subscription.spec.tsx
  frontend/integration-tests/tests/marketplace/kubernetes-marketplace.scenario.ts
  frontend/integration-tests/tests/olm/catalog.scenario.ts
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-binding.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-broker.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-catalog.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-class.scenario.ts
  frontend/integration-tests/views/horizontal-nav.view.ts
  frontend/public/components/app.jsx
  frontend/public/components/broker-management.tsx
  frontend/public/components/catalog/catalog-items.jsx
  frontend/public/components/catalog/catalog-page.jsx
  frontend/public/components/cluster-service-broker.tsx
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/marketplace/marketplace-page.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/operator-lifecycle-manager/install-plan.tsx
  frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/components/operator-management.tsx
  frontend/public/components/provisioned-services.tsx
  frontend/public/components/service-binding.tsx
  frontend/public/components/service-instance.tsx
  frontend/public/components/utils/horizontal-nav.tsx
  frontend/public/components/utils/link.jsx
Labels: lgtm, size/L
