Repository openshift/console, pull requests merged in 2018-08, with the labels that each got.

#351 Add namespace to pod metrics queries
  frontend/public/components/pod.jsx
Labels: lgtm, size/XS

#293 Adjust Namespace dropdown to ensure `All Projects` link is listed first
  frontend/public/components/namespace.jsx
  frontend/public/components/utils/dropdown.jsx
Labels: lgtm, size/M

#353 frontend: fix null when CatalogSource not available
  frontend/public/components/cloud-services/catalog-source.tsx
Labels: lgtm, size/XS

#348 Display custom message when self provisioning is disabled on cluster
  frontend/public/components/namespace.jsx
  frontend/public/components/start-guide.jsx
  frontend/public/features.ts
  frontend/public/ui/ui-actions.js
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/M

#344 add title attribute to resource badges
  frontend/public/components/utils/resource-icon.tsx
Labels: lgtm, size/XS

#360 Replace logo and favicon
  frontend/public/components/masthead.tsx
  frontend/public/imgs/favicon.ico
  frontend/public/imgs/favicon.png
  frontend/public/imgs/okd-logo.svg
  frontend/public/imgs/openshift-origin-logo.svg
Labels: lgtm, size/M

#363 Fix env var bug adding a new config map or secret value to container with index > 1.
  frontend/public/components/utils/name-value-editor.jsx
Labels: lgtm, size/XS

#361 Open context selector over left sidebar
  frontend/public/components/masthead.scss
Labels: lgtm, size/XS

#359 Update Kubernetes Models for OLM
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/__tests__/components/cloud-services/clusterserviceversion.spec.tsx
  frontend/__tests__/components/cloud-services/install-plan.spec.tsx
  frontend/__tests__/components/cloud-services/subscription.spec.tsx
  frontend/__tests__/module/k8s/k8s-models.spec.ts
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/olm/catalog.scenario.ts
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/integration-tests/tests/olm/update-channel-approval.scenario.ts
  frontend/public/components/cloud-services/clusterserviceversion.tsx
  frontend/public/components/cloud-services/index.tsx
  frontend/public/models/index.ts
  jenkins.sh
Labels: lgtm, size/L

#364 BZ1610244: The statement should be 'Project Overview' in project overview page
  frontend/public/components/namespace.jsx
Labels: lgtm, size/XS

#367 Purge all podvuln/security scan related features and components
  frontend/public/components/app.jsx
  frontend/public/components/cluster-overview-container.jsx
  frontend/public/components/cluster-overview.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/pod.jsx
  frontend/public/components/resource-pages.ts
  frontend/public/components/secscan/_secscan.scss
  frontend/public/components/secscan/donut-chart/donut-chart.jsx
  frontend/public/components/secscan/pod-vuln.jsx
  frontend/public/components/secscan/security-scan-overview.jsx
  frontend/public/features.ts
  frontend/public/models/index.ts
  frontend/public/module/k8s/podvulns.jsx
  frontend/public/style.scss
Labels: lgtm, size/XL

#368 Switch to rbac.authorization.k8s.io/v1
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/sidebars/role-sidebar.jsx
  frontend/public/models/index.ts
Labels: lgtm, size/S

#369 Update CI tests to run against OpenShift cluster
  frontend/public/components/app.jsx
  test-gui.sh
Labels: lgtm, size/S

#373 Better Types for Redux Helper Functions
  frontend/__tests__/features.spec.tsx
  frontend/public/components/resource-list.tsx
  frontend/public/features.ts
  frontend/public/kinds.ts
Labels: lgtm, size/M

#374 Disable Prometheus OCS GUI Test
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
Labels: lgtm, size/XS

#354 Update build strategy descriptions
  frontend/public/components/sidebars/build-config-sidebar.jsx
Labels: lgtm, size/XS

#378 Fix Catalog Source Name
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/__tests__/components/cloud-services/catalog-source.spec.tsx
  frontend/__tests__/components/cloud-services/clusterserviceversion.spec.tsx
  frontend/__tests__/components/cloud-services/subscription.spec.tsx
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/public/components/cloud-services/catalog-source.tsx
  frontend/public/components/cloud-services/clusterserviceversion.tsx
  frontend/public/components/cloud-services/index.tsx
  frontend/public/components/cloud-services/subscription.tsx
Labels: bug, lgtm, size/S

#377 Fix breadcrumb links when owner ref points to a CR
  frontend/__tests__/components/cloud-services/install-plan.spec.tsx
  frontend/public/components/utils/breadcrumbs.ts
  frontend/public/components/utils/resource-link.jsx
Labels: lgtm, size/M

#379 Various OLM Fixes
  frontend/__tests__/components/modals/disable-application-modal.spec.tsx
  frontend/public/components/cloud-services/clusterserviceversion.tsx
  frontend/public/components/modals/disable-application-modal.tsx
Labels: lgtm, size/S

#376 Bug 1613166 - Hide items filtered from the dropdown list
  frontend/public/components/utils/dropdown.jsx
Labels: lgtm, size/XS

#370 Fix mobile navbar menu
  frontend/public/components/masthead.scss
  frontend/public/style/_layout.scss
  frontend/public/style/_vars.scss
Labels: lgtm, size/S

#380 Bug 1612656 - fix 'View Log' url for Jenkins Pipeline build
  frontend/public/components/build-pipeline.tsx
Labels: lgtm, size/XS

#375 Updating favicon images to better quality.
  frontend/public/imgs/favicon.ico
  frontend/public/imgs/favicon.png
  frontend/public/imgs/mask-icon.svg
  frontend/public/imgs/ocp/apple-touch-icon-precomposed.png
  frontend/public/imgs/ocp/favicon.ico
  frontend/public/imgs/ocp/favicon.png
  frontend/public/imgs/ocp/mask-icon.svg
  frontend/public/imgs/ocp/mstile-144x144.png
  frontend/public/imgs/okd/apple-touch-icon-precomposed.png
  frontend/public/imgs/okd/favicon.ico
  frontend/public/imgs/okd/favicon.png
  frontend/public/imgs/okd/mask-icon.svg
  frontend/public/imgs/okd/mstile-144x144.png
  frontend/public/index.html
Labels: lgtm, size/M

#372 Change labels to use "Edit"
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/public/components/deployment.jsx
  frontend/public/components/job.jsx
  frontend/public/components/modals/configure-count-modal.jsx
  frontend/public/components/modals/configure-revision-history-limit-modal.jsx
  frontend/public/components/modals/configure-unschedulable-modal.jsx
  frontend/public/components/modals/configure-update-strategy-modal.jsx
  frontend/public/components/modals/labels-modal.jsx
  frontend/public/components/modals/tags.jsx
  frontend/public/components/node.tsx
  frontend/public/components/utils/cog.tsx
  frontend/public/components/utils/dropdown.jsx
Labels: lgtm, size/M

#331 Align event timestamps and fix resource name overflow
  frontend/public/components/_sysevent-stream.scss
  frontend/public/components/events.jsx
  frontend/public/components/utils/resource-link.jsx
Labels: lgtm, size/M

#381 change Rollout action on deployment config to Start Rollout
  frontend/public/components/deployment-config.tsx
Labels: lgtm, size/XS

#301 Make Dropdown keyboard accessible
  frontend/public/components/_dropdown.scss
  frontend/public/components/utils/dropdown.jsx
Labels: lgtm, size/M

#371 Additional branding updates
  cmd/bridge/main.go
  examples/config.yaml
  frontend/public/branding.ts
  frontend/public/components/app.jsx
  frontend/public/components/cluster-overview.jsx
  frontend/public/components/software-details.jsx
  frontend/public/components/utils/documentation.tsx
  frontend/public/index.html
  frontend/public/tokener.html
Labels: size/M

#387 Bug 1614266 - Add host to ingress example
  frontend/public/components/ingress.jsx
Labels: lgtm

#358 Lazy Loading for All App Routes
  frontend/__tests__/components/resource-pages.spec.ts
  frontend/__tests__/components/resource-pages.spec.tsx
  frontend/__tests__/components/utils/async.spec.tsx
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/app.jsx
  frontend/public/components/resource-list.tsx
  frontend/public/components/resource-pages.ts
  frontend/public/components/search.jsx
  frontend/public/components/utils/async.tsx
  frontend/webpack.config.ts
Labels: lgtm, size/XL

#383 Bug 1614213 - Unable to create Source type secret without Username set
  frontend/public/components/secrets/create-secret.tsx
Labels: lgtm

#388 CI: test OpenShift resources in crud scenario
  test-gui.sh
Labels: lgtm, size/XS

#385 Fix favicon
  frontend/public/imgs/okd-apple-touch-icon-precomposed.png
  frontend/public/imgs/okd-favicon.ico
  frontend/public/imgs/okd-favicon.png
  frontend/public/imgs/okd-mask-icon.svg
  frontend/public/imgs/okd-mstile-144x144.png
  frontend/public/imgs/openshift-apple-touch-icon-precomposed.png
  frontend/public/imgs/openshift-favicon.ico
  frontend/public/imgs/openshift-favicon.png
  frontend/public/imgs/openshift-mask-icon.svg
  frontend/public/imgs/openshift-mstile-144x144.png
  frontend/public/index.html
  frontend/public/tokener.html
Labels: lgtm, size/M

#391 Bug 1614728 - Fix redirect after deleting custom resource
  frontend/public/components/modals/delete-modal.jsx
  frontend/public/components/utils/resource-link.jsx
Labels: lgtm, size/S

#390 Bug 1610602 - Handle different service types and port mappings
  frontend/public/components/service.jsx
Labels: lgtm, size/S

#392 Do not add active class to dropdown item if noSelection is true
  frontend/public/components/utils/dropdown.jsx
Labels: lgtm, size/S

#396 Bug 16113185, console-331: handle the case where an env var is set without a value
  frontend/public/components/environment.jsx
Labels: lgtm, size/XS

#382 Nav updates
  frontend/__tests__/ui-actions.js
  frontend/integration-tests/tests/olm/catalog.scenario.ts
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/integration-tests/tests/olm/update-channel-approval.scenario.ts
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/public/components/app.jsx
  frontend/public/components/nav.jsx
  frontend/public/components/utils/link.jsx
Labels: lgtm, size/M

#398 Include system roots in cert pool when talking to OAuth server
  Dockerfile
  Dockerfile.product
  auth/auth.go
  etc/ssl/certs/ca-certificates.crt
Labels: lgtm, size/M

#394 Add mobile support for table views of the Subscription and Install plans
  frontend/public/components/cloud-services/install-plan.tsx
  frontend/public/components/cloud-services/subscription.tsx
Labels: lgtm, size/M

#400 Fix YAML Templates to Work with Code Split Routes
  frontend/__tests__/components/cloud-services/catalog-source.spec.tsx
  frontend/__tests__/components/cloud-services/create-crd-yaml.spec.tsx
  frontend/__tests__/components/create-yaml.spec.tsx
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/build-config.tsx
  frontend/public/components/chargeback.tsx
  frontend/public/components/cloud-services/catalog-source.tsx
  frontend/public/components/cloud-services/create-crd-yaml.tsx
  frontend/public/components/cloud-services/ocs-templates.ts
  frontend/public/components/clusters.tsx
  frontend/public/components/configmap.jsx
  frontend/public/components/create-yaml.tsx
  frontend/public/components/cron-job.jsx
  frontend/public/components/custom-resource-definition.jsx
  frontend/public/components/daemonset.jsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.jsx
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/hpa.tsx
  frontend/public/components/image-stream.tsx
  frontend/public/components/ingress.jsx
  frontend/public/components/job.jsx
  frontend/public/components/network-policy.jsx
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/persistent-volume.jsx
  frontend/public/components/pod.jsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/replication-controller.jsx
  frontend/public/components/resource-quota.jsx
  frontend/public/components/routes.tsx
  frontend/public/components/secret.jsx
  frontend/public/components/service-account.jsx
  frontend/public/components/service.jsx
  frontend/public/components/sidebars/build-config-sidebar.jsx
  frontend/public/components/sidebars/network-policy-sidebar.jsx
  frontend/public/components/sidebars/role-sidebar.jsx
  frontend/public/components/stateful-set.jsx
  frontend/public/components/storage-class.tsx
  frontend/public/models/yaml-templates.ts
  frontend/public/yaml-templates.js
Labels: lgtm, size/XXL

#389 Bug 1608315 - Use correct model for group/version/kind in YAML
  frontend/public/components/create-yaml.tsx
  frontend/public/components/edit-yaml.jsx
Labels: lgtm, size/M

#399 Remove Edit Revision History & Edit Node Selector actions
  frontend/integration-tests/views/crud.view.ts
  frontend/public/components/daemonset.jsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.jsx
  frontend/public/components/modals/configure-revision-history-limit-modal.jsx
  frontend/public/components/modals/index.ts
  frontend/public/components/modals/labels-modal.jsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/utils/cog.tsx
Labels: lgtm, size/L

#397 Resource kind not passed to the loaded component
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/app.jsx
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/secrets/create-secret.tsx
Labels: lgtm, size/M

#409 Rename modal primary button id to 'confirm-action'
  frontend/integration-tests/tests/base.scenario.ts
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/integration-tests/tests/modal-annotations.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/integration-tests/views/modal-annotations.view.ts
  frontend/public/components/factory/modal.jsx
Labels: lgtm, size/S

#407 Bug 1609204 - Add namespace to pod selector in workload list pages
  frontend/public/components/daemonset.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/stateful-set.jsx
Labels: lgtm, size/S

#306 Add Alert Manager proxy
  cmd/bridge/main.go
  frontend/public/components/graphs/index.jsx
  server/server.go
Labels: lgtm, size/M

#418 Bug 1618670 - Could not update deployment strategy from Recreate to Rolling from console
  frontend/public/components/modals/configure-update-strategy-modal.jsx
Labels: lgtm, size/S

#417 Build strategy enum
  frontend/public/components/build-config.tsx
  frontend/public/components/build-logs.jsx
  frontend/public/components/build.tsx
  frontend/public/components/utils/build-strategy.tsx
Labels: lgtm, size/M

#410 Indicate if a storage class is default
  frontend/public/components/storage-class.tsx
Labels: lgtm, size/S

#416 Add `getBlob` function to LineBuffer component and use in ResourceLog for downloads
  frontend/public/components/utils/line-buffer.ts
  frontend/public/components/utils/resource-log.jsx
Labels: lgtm, size/S

#412 Bug 1617924 - Samples can't be tried and downloaded
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/sidebars/build-config-sidebar.jsx
  frontend/public/components/sidebars/network-policy-sidebar.jsx
  frontend/public/components/sidebars/role-sidebar.jsx
Labels: lgtm, size/M

#356 Add Service Instance, Service Binding list and details pages
  frontend/__tests__/features.spec.tsx
  frontend/public/components/_route.scss
  frontend/public/components/nav.jsx
  frontend/public/components/resource-pages.ts
  frontend/public/components/routes.tsx
  frontend/public/components/service-binding.tsx
  frontend/public/components/service-catalog-parameters.tsx
  frontend/public/components/service-instance.tsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/service-catalog-status.tsx
  frontend/public/features.ts
  frontend/public/style/_icons.scss
Labels: lgtm, size/L

#406 Allow type ahead on all resource dropdowns
  frontend/public/components/_dropdown.scss
  frontend/public/components/resource-dropdown.tsx
Labels: lgtm, size/S

#420 Adjust display of ContainerLinks in Pod Volumes table
  frontend/public/components/_resource.scss
  frontend/public/components/pod.jsx
Labels: lgtm, size/S

#414 Code Split Modals
  frontend/__tests__/components/cloud-services/spec-descriptors/resource-requirements.spec.tsx
  frontend/public/components/cloud-services/spec-descriptors/configure-size.tsx
  frontend/public/components/cloud-services/spec-descriptors/index.tsx
  frontend/public/components/cloud-services/spec-descriptors/resource-requirements.tsx
  frontend/public/components/factory/modal.tsx
  frontend/public/components/modals/configure-count-modal.jsx
  frontend/public/components/modals/disable-application-modal.tsx
  frontend/public/components/modals/index.ts
  frontend/public/components/modals/installplan-approval-modal.tsx
  frontend/public/components/modals/subscription-channel-modal.tsx
Labels: lgtm, size/L

#174 Drag&Drop for FileInput
  frontend/public/components/_secret.scss
  frontend/public/components/secrets/create-secret.tsx
  frontend/public/components/utils/_file-input.scss
  frontend/public/components/utils/drag-drop-context.tsx
  frontend/public/components/utils/file-input.tsx
  frontend/public/components/utils/index.tsx
  frontend/public/style.scss
Labels: lgtm, size/L

#421 Fixed style import statement
  frontend/public/style.scss
Labels: lgtm, size/XS

#357 Add Service Classes list and details pages
  frontend/package.json
  frontend/public/components/_cluster-service-class.scss
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/resource-pages.ts
  frontend/public/components/utils/vertnav.jsx
  frontend/public/module/k8s/index.ts
  frontend/public/module/k8s/service-class.ts
  frontend/public/style.scss
  frontend/yarn.lock
Labels: lgtm, size/L

#233 Pod Logs Fullscreen
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/modal-annotations.scenario.ts
  frontend/integration-tests/views/modal-annotations.view.ts
  frontend/package.json
  frontend/public/components/utils/_log-window.scss
  frontend/public/components/utils/_name-value-editor.scss
  frontend/public/components/utils/_resource-log.scss
  frontend/public/components/utils/log-window.jsx
  frontend/public/components/utils/name-value-editor.jsx
  frontend/public/components/utils/resource-log.jsx
  frontend/public/style.scss
  frontend/public/style/_common.scss
  frontend/yarn.lock
Labels: lgtm, size/L

#283 Update NodeLink component to use FLAGS.CAN_LIST_NODE
  frontend/public/components/events.jsx
  frontend/public/components/pod.jsx
  frontend/public/components/utils/resource-link.jsx
  frontend/public/models/index.ts
Labels: lgtm, size/S

#424 Make ClusterServiceClass link cluster scoped
  frontend/public/components/nav.jsx
Labels: lgtm, size/XS

#425 Add service class text filter
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/factory/list.tsx
Labels: lgtm, size/S

#428 Bug 1619156 - Project/Namespace page has a semicolon at the bottom-left corner of right panel
  frontend/public/components/namespace.jsx
Labels: lgtm, size/XS

#429 Unify resource sidebar component
  frontend/public/components/sidebars/build-config-sidebar.jsx
  frontend/public/components/sidebars/network-policy-sidebar.jsx
  frontend/public/components/sidebars/resource-sidebar.jsx
  frontend/public/components/sidebars/role-sidebar.jsx
Labels: lgtm, size/L

#423 Bug 1603091 - Don't use fuzzy filter on event messages
  frontend/public/components/events.jsx
Labels: lgtm, size/M

#427 Show `core` apiGroup in resource dropdown
  frontend/public/components/resource-dropdown.tsx
Labels: lgtm

#433 Show display name, not UID in service catalog table
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/factory/list.tsx
Labels: lgtm, size/M

#434 Cluster Service Broker: List & Detail pages
  frontend/public/components/cluster-service-broker.tsx
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/resource-pages.ts
  frontend/public/components/service-binding.tsx
  frontend/public/components/service-instance.tsx
  frontend/public/components/utils/service-catalog-status.tsx
  frontend/public/components/utils/vertnav.jsx
  frontend/public/models/yaml-templates.ts
  frontend/public/module/k8s/service-catalog.ts
Labels: lgtm, size/L

#225 (feature) add Limit Range list and details pages
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/public/components/limit-range.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/resource-pages.ts
  frontend/public/models/index.ts
  frontend/public/models/yaml-templates.ts
Labels: lgtm, size/L

#442 Look for "Prometheus Operator" in OLM tests
  frontend/integration-tests/tests/olm/catalog.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
Labels: lgtm, size/S

#205 Create/Edit image secret
  frontend/public/components/secret.jsx
  frontend/public/components/secrets/_create-secret.scss
  frontend/public/components/secrets/create-secret.tsx
  frontend/public/components/utils/file-input.tsx
  frontend/public/style.scss
Labels: lgtm, size/L

#438 Remove ellipses from edit secret action
  frontend/public/components/secret.jsx
Labels: lgtm, size/XS

#441 Match pod succeeded filter title to what appears in status column
  frontend/public/components/pod.jsx
Labels: lgtm, size/XS

#444 Restore service class header to previous position
  frontend/public/components/cluster-service-class.tsx
Labels: lgtm, size/XS

#445 Fix Operator Description Font
  frontend/public/components/cloud-services/markdown-view.tsx
Labels: lgtm, size/XS

#401 Fix bug where roles are not sorted in dropdown in create role bindin…
  frontend/public/components/RBAC/bindings.jsx
Labels: lgtm, size/XS

#355 Update Dropdown component to handle long strings of text
  frontend/public/components/RBAC/_rbac.scss
  frontend/public/components/_cluster-overview.scss
  frontend/public/components/_dropdown.scss
  frontend/public/components/_resource-dropdown.scss
  frontend/public/components/_resource.scss
  frontend/public/components/cluster-overview.jsx
  frontend/public/components/events.jsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/resource-dropdown.tsx
  frontend/public/components/search.jsx
  frontend/public/components/utils/_value-from-pair.scss
  frontend/public/components/utils/dropdown.jsx
  frontend/public/components/utils/resource-icon.tsx
  frontend/public/components/utils/value-from-pair.jsx
  frontend/public/style/_common.scss
Labels: lgtm, size/L

#439 Handle empty secrets and config maps
  frontend/public/components/configmap-and-secret-data.jsx
Labels: lgtm, size/S

#446 Bug 1620368 - Remove incorrect fields from cron job page
  frontend/public/components/cron-job.jsx
Labels: size/S

#447 integration tests: wait for test resource to be created before continuing
  frontend/integration-tests/tests/environment.scenario.ts
  frontend/integration-tests/tests/filter.scenario.ts
Labels: lgtm, size/XS

#435 Bug 1619535 - Link NetworkPolicy to proper docs on the details page
  frontend/public/components/network-policy.jsx
  frontend/public/components/utils/documentation.tsx
Labels: lgtm, size/M

#443 Fix RBAC for CatalogSource Views
  frontend/public/components/cloud-services/catalog-source.tsx
  frontend/public/components/cloud-services/clusterserviceversion.tsx
Labels: lgtm, size/XS

#451 Fix partial object metadata requests
  frontend/public/co-fetch.js
  frontend/public/module/k8s/resource.js
Labels: lgtm, size/XS

#453 Remove out of date CHANGES and MAINTAINERS files
  CHANGES.md
  MAINTAINERS
Labels: lgtm, size/S

#448 Fix node link in events stream
  frontend/public/components/events.jsx
Labels: lgtm, size/S

#454 Bug 1603091 - Break words on whitespace for events search
  frontend/public/components/events.jsx
Labels: lgtm, size/XS

#455 Bug 1609204 - Add namespace to service selector link
  frontend/public/components/service.jsx
Labels: lgtm, size/XS

#461 Bug 1622372 - Require CSRF token on all proxied requests
  auth/auth.go
  auth/auth_test.go
  cmd/bridge/main.go
  frontend/public/co-fetch.js
  frontend/public/module/ws-factory.js
  pkg/proxy/proxy.go
  server/middleware.go
  server/server.go
Labels: lgtm, size/M

#452 Service Plans List and Detail pages
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/cluster-service-plan.tsx
  frontend/public/components/resource-pages.ts
  frontend/public/components/utils/vertnav.jsx
Labels: lgtm, size/L

#456 Show sidebar only when creating resource
  frontend/public/components/sidebars/resource-sidebar.jsx
Labels: lgtm, size/XS

#462 Rename session cookie to `openshift-session-token`
  auth/auth_oidc.go
  auth/auth_openshift.go
  auth/session.go
Labels: lgtm, size/S

#457 Initial cut of create service instance
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/_cluster-service-class.scss
  frontend/public/components/_cluster-service-instance.scss
  frontend/public/components/app.jsx
  frontend/public/components/cluster-service-class-icon.tsx
  frontend/public/components/cluster-service-class-info.tsx
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/factory/details.tsx
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/components/utils/firehose.jsx
  frontend/public/components/utils/nav-title.tsx
  frontend/public/module/k8s/k8s-actions.ts
  frontend/public/style.scss
Labels: lgtm, size/L

#463 Add height for SVG images so SVGs without default size render correctly
  frontend/public/components/_cluster-service-class.scss
Labels: lgtm, size/XS

#467 Add co-break-word to conditions message to fix overflow bug
  frontend/public/components/conditions.tsx
Labels: lgtm, size/XS

#465 Bug 1622818 - Simplify dropdown
  frontend/public/components/namespace.jsx
  frontend/public/components/resource-dropdown.tsx
  frontend/public/components/utils/dropdown.jsx
Labels: lgtm, size/L

#469 Support Multiple CatalogSources in the Global OLM Namespace
  frontend/__tests__/components/cloud-services/clusterserviceversion.spec.tsx
  frontend/__tests__/components/cloud-services/subscription.spec.tsx
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/public/components/cloud-services/catalog-source.tsx
  frontend/public/components/cloud-services/clusterserviceversion.tsx
  frontend/public/components/cloud-services/index.tsx
  frontend/public/components/cloud-services/subscription.tsx
Labels: lgtm, size/M

#464 Fix https://jira.coreos.com/browse/CONSOLE-734
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/role.jsx
Labels: lgtm, size/M

#466 Add parameters to the service instance form
  frontend/package.json
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/yarn.lock
Labels: lgtm, size/L

#474 Remove noise from the console logs
  pkg/proxy/proxy.go
Labels: lgtm, size/XS

#475 Add custom field template to create instance form
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/style.scss
  frontend/public/style/_forms.scss
Labels: lgtm, size/S

#471 Remove unnecessary `poll` parameter
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/components/utils/firehose.jsx
  frontend/public/module/k8s/k8s-actions.ts
Labels: lgtm, size/S

#470 Initial cut of create binding form
  frontend/integration-tests/views/crud.view.ts
  frontend/public/components/_nav-title.scss
  frontend/public/components/app.jsx
  frontend/public/components/service-catalog/create-binding.tsx
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/components/service-instance.tsx
  frontend/public/components/utils/dropdown.jsx
  frontend/public/components/utils/nav-title.tsx
Labels: lgtm, size/L

#411 Add monitoring alerts list and details pages
  frontend/__tests__/module/monitoring.js
  frontend/public/components/_alert.scss
  frontend/public/components/_resource.scss
  frontend/public/components/alert.tsx
  frontend/public/components/app.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/row-filter.jsx
  frontend/public/components/utils/datetime.ts
  frontend/public/module/monitoring.js
  frontend/public/style.scss
  frontend/public/style/_common.scss
  frontend/public/style/_icons.scss
  frontend/public/style/_text.scss
  frontend/public/style/_vars.scss
  frontend/public/ui/ui-actions.js
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/XL

#479 Fix bug where .co-actions content misaligned
  frontend/public/components/_nav-title.scss
Labels: lgtm, size/XS

#480 Only display link to secret if status is ready
  frontend/public/components/service-binding.tsx
Labels: lgtm, size/S

#473 multistage builds for downstream
  Dockerfile.product
  Dockerfile.product.nodejs
Labels: lgtm, size/M

#484 Do not style "ContainerCreating", "ContainersNotReady" as error states
  frontend/public/components/pod.jsx
Labels: lgtm, size/XS

#478 ClusterServiceVersion Views Cleanup
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/__tests__/components/cloud-services/clusterserviceversion.spec.tsx
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/integration-tests/views/app-list.view.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/public/components/app.jsx
  frontend/public/components/cloud-services/_cloud-services.scss
  frontend/public/components/cloud-services/clusterserviceversion.tsx
  frontend/public/components/cloud-services/index.tsx
  frontend/public/components/cloud-services/k8s-resource.tsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/utils/nav-title.tsx
  frontend/public/imgs/apps-logo-active.svg
  frontend/public/imgs/apps-logo.svg
Labels: lgtm, size/XL

#468 Change Service Class and Plan names from UIDs to Display Names
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/cluster-service-plan.tsx
  frontend/public/components/factory/details.tsx
  frontend/public/components/utils/nav-title.tsx
  frontend/public/module/k8s/service-catalog.ts
Labels: lgtm, size/S
