Repository openshift/console, pull requests merged in 2018-10, with the labels that each got.

#593 Optimize bundling for overview and project-overview
  frontend/__tests__/components/factory/list-page.spec.tsx
  frontend/__tests__/components/utils/page-heading.spec.tsx
  frontend/public/components/alert.tsx
  frontend/public/components/catalog.jsx
  frontend/public/components/chargeback.tsx
  frontend/public/components/cluster-health.jsx
  frontend/public/components/cluster-overview.jsx
  frontend/public/components/cluster-settings/cluster-settings.jsx
  frontend/public/components/cluster-settings/ldap.jsx
  frontend/public/components/container.jsx
  frontend/public/components/daemon-set.jsx
  frontend/public/components/default-resource.jsx
  frontend/public/components/deploy-image.tsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.jsx
  frontend/public/components/error.tsx
  frontend/public/components/events.jsx
  frontend/public/components/factory/details.tsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/overview.jsx
  frontend/public/components/profile.jsx
  frontend/public/components/search.jsx
  frontend/public/components/service-catalog/create-binding.tsx
  frontend/public/components/service-catalog/create-instance.tsx
  frontend/public/components/stateful-set.jsx
  frontend/public/components/utils/headings.tsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/section-heading.tsx
Labels: lgtm, size/L

#608 Align chevron vertically on center
  frontend/public/components/_project-overview.scss
Labels: lgtm, size/XS

#594 Rename `masthead.scss` to `_masthead.scss` to match existing convention
  frontend/public/components/_masthead.scss
Labels: lgtm

#609 Rename graphs.scss to _graphs.scss
  frontend/public/components/graphs/_graphs.scss
Labels: lgtm, size/XS

#590 Better handling of overview groups with no label value
  frontend/public/components/overview.jsx
  frontend/public/components/project-overview.jsx
Labels: lgtm, size/S

#604 Upgrade patternfly-react-extensions and adjust catalog sidebar width
  frontend/package.json
  frontend/public/components/_catalog.scss
  frontend/yarn.lock
  sources
Labels: lgtm, size/L

#600 Changes to fix issue with React virtualized WindowScroller by assigning the scrollElement property to a specific id
  frontend/public/components/app.jsx
  frontend/public/components/events.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/style/_layout.scss
Labels: lgtm, size/S

#505 Service Catalog Integration Tests
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-binding.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-broker.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-catalog.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-class.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/integration-tests/views/service-catalog.view.ts
  frontend/integration-tests/views/sidenav.view.ts
  frontend/public/components/cluster-service-class.tsx
  jenkins.sh
  test-gui.sh
Labels: lgtm, size/L

#588 e2e test for source secret - basic & ssh auth
  frontend/integration-tests/tests/secrets.scenario.ts
  frontend/integration-tests/views/secrets.view.ts
  frontend/public/components/configmap-and-secret-data.jsx
Labels: lgtm, size/L

#595 Change 'Create' button labels to match Patternfly recommendation
  frontend/__tests__/components/modals/installplan-approval-modal.spec.tsx
  frontend/__tests__/components/modals/subscription-channel-modal.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.spec.tsx
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/edit-rule.jsx
  frontend/public/components/cluster-settings/cluster-monitoring.jsx
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/environment.jsx
  frontend/public/components/modals/configure-count-modal.jsx
  frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
  frontend/public/components/modals/configure-operator-channel-modal.jsx
  frontend/public/components/modals/configure-operator-modal.jsx
  frontend/public/components/modals/configure-update-strategy-modal.jsx
  frontend/public/components/modals/create-namespace-modal.jsx
  frontend/public/components/modals/installplan-approval-modal.tsx
  frontend/public/components/modals/labels-modal.jsx
  frontend/public/components/modals/subscription-channel-modal.tsx
  frontend/public/components/modals/tags.jsx
  frontend/public/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.tsx
  frontend/public/components/secrets/create-secret.tsx
Labels: lgtm, size/M

#564 Show revision link with resource name in overview row
  frontend/public/components/project-overview.jsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/replication-controller.jsx
Labels: lgtm, size/L

#611 Changes to sidebar to fix where classes inadvertently changed.
  frontend/public/components/utils/headings.tsx
Labels: lgtm, size/XS

#542 Add Init Container support to env editor
  frontend/public/components/daemon-set.jsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.jsx
  frontend/public/components/environment.jsx
  frontend/public/components/pod.jsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/replication-controller.jsx
  frontend/public/components/stateful-set.jsx
Labels: lgtm, size/L

#614 Show in progress rollouts on overview
  frontend/public/components/_project-overview.scss
  frontend/public/components/overview.jsx
  frontend/public/components/project-overview.jsx
Labels: lgtm, size/L

#615 Refact & Remove dups. from e2e test
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/integration-tests/views/login.view.ts
  frontend/integration-tests/views/secrets.view.ts
  frontend/integration-tests/views/source-to-image.view.ts
  frontend/integration-tests/views/yaml.view.ts
Labels: lgtm, size/M

#617 Adjust co-m-pane__heading margin
  frontend/public/style/_common.scss
Labels: lgtm, size/XS

#620 Add monitoring Silence edit and cancel actions
  frontend/public/components/alert.tsx
  frontend/public/components/app.jsx
  frontend/public/components/silence.tsx
  frontend/public/components/utils/link.jsx
Labels: lgtm, size/L

#540 Create import YAML page
  frontend/integration-tests/tests/olm/catalog.scenario.ts
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/integration-tests/views/yaml.view.ts
  frontend/public/components/_edit-yaml.scss
  frontend/public/components/_import-yaml.scss
  frontend/public/components/_nav.scss
  frontend/public/components/app.jsx
  frontend/public/components/create-yaml.tsx
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/import-yaml.tsx
  frontend/public/components/namespace.jsx
  frontend/public/style.scss
Labels: lgtm, size/L

#610 Use Dropdown component in the Create Namespace Modal
  frontend/public/components/modals/create-namespace-modal.jsx
Labels: lgtm, size/S

#619 Overview sidebar mobile enhancements
  frontend/public/components/_overview.scss
  frontend/public/components/overview.jsx
Labels: lgtm, size/M

#626 Upgrade Protractor
  frontend/integration-tests/protractor.conf.ts
  frontend/package.json
  frontend/yarn.lock
  sources
Labels: lgtm, size/L

#628 Secret e2e image + Image Secret form fix
  frontend/integration-tests/tests/secrets.scenario.ts
  frontend/integration-tests/views/secrets.view.ts
  frontend/public/components/secrets/create-secret.tsx
Labels: lgtm, size/L

#616 Add error alerts to overview rows
  frontend/public/components/_project-overview.scss
  frontend/public/components/overview.jsx
  frontend/public/components/project-overview.jsx
Labels: lgtm, size/L

#633 Webhook secret e2e flake
  frontend/integration-tests/tests/secrets.scenario.ts
Labels: lgtm, size/XS

#618 Add create form for Routes
  frontend/public/components/app.jsx
  frontend/public/components/routes.tsx
  frontend/public/components/routes/_create-route.scss
  frontend/public/components/routes/create-route.tsx
  frontend/public/style.scss
  frontend/public/style/_common.scss
Labels: lgtm, size/L

#635 Remove stray semicolon at bottom of import yaml view
  frontend/public/components/import-yaml.tsx
Labels: lgtm, size/XS

#603 Fix Re-Rendering Caused by API Discovery
  builder-run.sh
  frontend/__tests__/components/utils/firehose.spec.tsx
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/public/components/_dropdown.scss
  frontend/public/components/app.jsx
  frontend/public/components/namespace.jsx
  frontend/public/components/source-to-image.tsx
  frontend/public/components/utils/firehose.jsx
  frontend/public/components/utils/horizontal-nav.tsx
  frontend/public/components/utils/resource-link.jsx
  frontend/tsconfig.json
Labels: lgtm, size/L

#629 Change sidebar resource detail list into 2 column layout.
  frontend/public/components/_overview.scss
Labels: lgtm, size/M

#630 Increase default width of popover content
  frontend/public/style/_overrides.scss
Labels: lgtm, size/XS

#591 Catalog: Initial Filter Side Panel
  frontend/public/components/_catalog.scss
  frontend/public/components/catalog-items.jsx
  frontend/public/components/catalog.jsx
  frontend/public/components/utils/categorize-catalog-items.ts
Labels: lgtm, size/L

#607 New AMQ logo
  frontend/package.json
  frontend/public/imgs/logos/amq.svg
  frontend/yarn.lock
  sources
Labels: lgtm, size/S

#634 Fix deploy image search bugs
  frontend/public/components/deploy-image.tsx
Labels: lgtm, size/S

#601 frontend: Show dynamic height events
  frontend/public/components/_sysevent-stream.scss
  frontend/public/components/events.jsx
Labels: lgtm, size/M

#636 Change modal link right arrow icon to pencil icon
  frontend/public/style/coreos.css
Labels: lgtm, size/XS

#640 Don't show header on YAML tab for existing resources
  frontend/public/components/edit-yaml.jsx
Labels: lgtm, size/XS

#631 On alerts list page, show Prometheus alerts data rather than rule data
  frontend/__tests__/module/monitoring.js
  frontend/public/components/alert.tsx
  frontend/public/components/factory/list.tsx
  frontend/public/module/monitoring.js
Labels: lgtm, size/L

#641 Remove title attribute and help cursor from event rows
  frontend/public/components/_sysevent-stream.scss
  frontend/public/components/events.jsx
Labels: lgtm, size/XS

#627 Add memory and CPU metrics to overview
  frontend/public/components/_project-overview.scss
  frontend/public/components/overview.jsx
  frontend/public/components/project-overview.jsx
Labels: lgtm, size/L

#596 Kubernetes Marketplace - basic page
  frontend/__tests__/features.spec.tsx
  frontend/public/components/app.jsx
  frontend/public/components/marketplace/kubernetes-marketplace.jsx
  frontend/public/components/nav.jsx
  frontend/public/features.ts
Labels: lgtm, size/L

#644 Replace OLM ConfigMap Parsing with Packages API
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/__tests__/components/modals/subscription-channel-modal.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/catalog-source.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/package-manifest.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/subscription.spec.tsx
  frontend/integration-tests/tests/olm/catalog.scenario.ts
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/public/components/factory/details.tsx
  frontend/public/components/modals/subscription-channel-modal.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/operator-lifecycle-manager/catalog-source.tsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
  frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/components/resource-pages.ts
Labels: lgtm, size/XL

#646 Kubernetes Marketplace - disable nav button
  frontend/public/components/nav.jsx
Labels: lgtm, size/XS

#645 Rename NamespaceSelector to NamespaceBar and fix styling issues
  frontend/public/components/_dropdown.scss
  frontend/public/components/app.jsx
  frontend/public/components/namespace.jsx
Labels: lgtm, size/M

#648 Change "Import YAML" to "Add" dropdown in namespace bar
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/integration-tests/tests/deploy-image.scenario.ts
  frontend/integration-tests/tests/source-to-image.scenario.ts
  frontend/integration-tests/views/namespace.view.ts
  frontend/public/components/_dropdown.scss
  frontend/public/components/_import-yaml.scss
  frontend/public/components/deploy-image.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/source-to-image.tsx
  frontend/public/style.scss
Labels: lgtm, size/L

#649 Enable min-width on catalog and enable horizontal scrolling
  frontend/public/components/_catalog.scss
  frontend/public/style/_layout.scss
Labels: lgtm, size/XS

#651 Fix deploy image image stream tag trigger
  frontend/public/components/deploy-image.tsx
Labels: lgtm, size/XS

#653 Use Bootstrap styles for checkbox in delete modal
  frontend/public/components/modals/_modals.scss
  frontend/public/components/modals/delete-modal.jsx
Labels: lgtm, size/S

#625 Add Attach Storage form
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/app.jsx
  frontend/public/components/checkbox.tsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.jsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/stateful-set.jsx
  frontend/public/components/storage/attach-storage.tsx
  frontend/public/components/utils/cog.tsx
Labels: lgtm, size/L

#642 Catalog Fixes
  frontend/public/components/_catalog.scss
  frontend/public/components/catalog-items.jsx
Labels: lgtm, size/M

#659 Adjust overview__main-column width so safari scrollbar isn't positioned over sidebar details
  frontend/public/components/_overview.scss
  frontend/public/components/_project-overview.scss
Labels: lgtm, size/S

#658 Fix to only render correct catalog items
  frontend/package.json
  frontend/public/components/_catalog.scss
  frontend/public/components/catalog-items.jsx
  frontend/yarn.lock
  sources
Labels: lgtm, size/L

#632 Update environment drag and drop icon
  frontend/__tests__/components/utils/name-value-editor.spec.tsx
  frontend/public/components/utils/_name-value-editor.scss
  frontend/public/components/utils/name-value-editor.jsx
Labels: lgtm, size/M

#664 Fix to prevent reload on Enter in Catalog filter by name field
  frontend/public/components/catalog-items.jsx
Labels: lgtm, size/XS

#665 Fix to not reload the entire page on catalog item click
  frontend/public/components/catalog-items.jsx
Labels: lgtm, size/XS

#670 Service catalog fixes
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-broker.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-catalog.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-class.scenario.ts
  frontend/integration-tests/views/service-catalog.view.ts
  frontend/integration-tests/views/sidenav.view.ts
  frontend/public/components/catalog.jsx
  frontend/public/components/cluster-service-broker.tsx
Labels: lgtm, size/M

#662 Generate unique IDs for alerting rules
  frontend/package.json
  frontend/public/components/alert.tsx
  frontend/public/components/app.jsx
  frontend/yarn.lock
Labels: lgtm, size/M

#669 Fix text overflow on Catalog tiles w/ long names
  frontend/package.json
  frontend/yarn.lock
  sources
Labels: lgtm, size/M

#637 Add services and routes to overview details
  frontend/public/components/_horizontal-nav.scss
  frontend/public/components/_service.scss
  frontend/public/components/daemon-set.jsx
  frontend/public/components/default-resource.jsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.jsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/overview/_overview.scss
  frontend/public/components/overview/_project-overview.scss
  frontend/public/components/overview/daemon-set-overview.tsx
  frontend/public/components/overview/deployment-config-overview.tsx
  frontend/public/components/overview/deployment-overview.tsx
  frontend/public/components/overview/index.tsx
  frontend/public/components/overview/networking-overview.tsx
  frontend/public/components/overview/project-overview.tsx
  frontend/public/components/overview/resource-overview-details.tsx
  frontend/public/components/overview/resource-overview-page.tsx
  frontend/public/components/overview/resource-overview-pages.tsx
  frontend/public/components/overview/stateful-set-overview.tsx
  frontend/public/components/resource-list.tsx
  frontend/public/components/resource-pages.ts
  frontend/public/components/stateful-set.jsx
  frontend/public/components/utils/firehose.jsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/simple-tab-nav.tsx
  frontend/public/module/k8s/index.ts
  frontend/public/module/k8s/label-selector.js
  frontend/public/style.scss
  frontend/public/ui/ui-actions.js
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/XXL

#681 Bug 1641585 - Update service instance filters for status values
  frontend/public/components/service-instance.tsx
Labels: lgtm, size/XS

#668 Add 'co-require' class to create forms labels
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/secrets/create-secret.tsx
  frontend/public/components/source-to-image.tsx
  frontend/public/components/utils/file-input.tsx
Labels: lgtm, size/M

#675 Avoid runtime error when node image has no name
  frontend/public/components/node.tsx
Labels: lgtm, size/XS

#685 Highlight Catalog nav item for create flows
  frontend/public/components/app.jsx
  frontend/public/components/catalog.jsx
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/image-stream.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/service-catalog/create-instance.tsx
Labels: lgtm, size/S

#686 Bug 1641976 - Correctly set destination CA certificate in create route form
  frontend/public/components/routes/create-route.tsx
Labels: lgtm, size/S

#678 Improve Active Alerts display on narrow screens
  frontend/public/components/alert.tsx
Labels: lgtm, size/S

#680 Move Alertmanager link from sidebar to top of monitoring pages
  frontend/public/components/_monitoring.scss
  frontend/public/components/alert.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/silence.tsx
Labels: lgtm, size/S

#694 Integration Tests: Wait for etcd Create New button before trying to click
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
Labels: lgtm, size/XS

#687 Bug 1641906 - Correctly show overview alerts for deployment configs
  frontend/public/components/overview/index.tsx
Labels: lgtm, size/S

#689 Fix bug where targetPort state wasn't unset on change of service
  frontend/public/components/routes/create-route.tsx
Labels: lgtm, size/XS

#647 Visual tweaks to vertical navigation
  frontend/public/components/_dropdown.scss
  frontend/public/components/_nav.scss
  frontend/public/components/nav.jsx
  frontend/public/style/_vars.scss
Labels: lgtm, size/L

#667 Keep monitoring Active Alerts list ordered by description
  frontend/public/components/alert.tsx
Labels: lgtm, size/S

#656 More OLM Descriptor Components
  frontend/__tests__/components/operator-lifecycle-manager/descriptors/spec/index.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/descriptors/status/index.spec.tsx
  frontend/integration-tests/tests/olm/descriptors.scenario.ts
  frontend/public/components/operator-lifecycle-manager/_operator-lifecycle-manager.scss
  frontend/public/components/operator-lifecycle-manager/descriptors/spec/endpoint.tsx
  frontend/public/components/operator-lifecycle-manager/descriptors/spec/index.tsx
  frontend/public/components/operator-lifecycle-manager/descriptors/status/index.tsx
  frontend/public/components/operator-lifecycle-manager/descriptors/types.ts
  frontend/public/module/k8s/autocomplete.ts
  frontend/public/style.scss
  frontend/public/vendor.scss
Labels: lgtm, size/L

#673 Bug 1640461 - Clicking label link on expanded form will jump to search service page
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/public/components/utils/details-page.tsx
Labels: lgtm, size/S

#677 Add "View Alert Rule" action to monitoring alerts cog and refactoring
  frontend/public/components/alert.tsx
  frontend/public/components/factory/list.tsx
Labels: lgtm, size/M

#691 Add tooltip to overview row metrics
  frontend/public/components/overview/_project-overview.scss
  frontend/public/components/overview/project-overview.tsx
  frontend/public/components/utils/tooltip.tsx
Labels: lgtm, size/L

#695 Cache API discovery
  frontend/__tests__/components/utils/firehose.spec.tsx
  frontend/public/components/app.jsx
  frontend/public/components/search.jsx
  frontend/public/components/utils/firehose.jsx
  frontend/public/const.js
  frontend/public/module/k8s/get-resources.ts
  frontend/public/module/k8s/k8s-actions.ts
Labels: lgtm, size/L

#696 e2e test flake fix: wait for username input to render
  frontend/integration-tests/tests/secrets.scenario.ts
  frontend/integration-tests/views/secrets.view.ts
Labels: lgtm, size/XS

#698 Catalog: Filter by Keyword in title/name, description, and tags
  frontend/public/components/catalog-items.jsx
Labels: lgtm, size/M

#690 Better responsive behavior of metrics, status, alerts.
  frontend/public/components/overview/_project-overview.scss
Labels: lgtm, size/M

#693 Update Service Binding details page to enhance binding flow
  frontend/public/components/service-binding.tsx
  frontend/public/components/service-instance.tsx
Labels: lgtm, size/S

#676 Add the environment variables editor to Deploy Image creation
  frontend/public/components/deploy-image.tsx
  frontend/public/components/environment.jsx
  frontend/public/components/utils/name-value-editor.jsx
Labels: lgtm, size/L

#702 Make Cluster Status page's "Alerts Firing" link to new Monitoring UI
  frontend/public/components/cluster-overview.jsx
Labels: lgtm, size/XS

#701 Two small style fixes for the Monitoring UI
  frontend/public/components/_monitoring.scss
  frontend/public/components/alert.tsx
Labels: lgtm, size/XS

#699 Remove icon from readonly environment
  frontend/public/components/utils/name-value-editor.jsx
Labels: lgtm, size/S

#704 Bug 1642799 - Warn when a deleted instance has bindings
  frontend/public/components/_cluster-service-instance.scss
  frontend/public/components/service-instance.tsx
Labels: lgtm, size/M

#700 Some sidebar adjustments to more closely match latest design docs
  frontend/public/components/_horizontal-nav.scss
  frontend/public/components/overview/_overview.scss
  frontend/public/components/overview/networking-overview.tsx
  frontend/public/components/utils/headings.tsx
Labels: lgtm, size/L

#709 Change GroupVersionKind String Format to Work in URLs
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
  frontend/__tests__/module/k8s/k8s-models.spec.ts
  frontend/integration-tests/tests/olm/descriptors.scenario.ts
  frontend/integration-tests/tests/olm/etcd.scenario.ts
  frontend/integration-tests/tests/olm/prometheus.scenario.ts
  frontend/public/components/chargeback.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
  frontend/public/module/k8s/k8s.ts
Labels: lgtm, size/M

#708 Refactor start guide into HOC
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/catalog.jsx
  frontend/public/components/chargeback.tsx
  frontend/public/components/cluster-overview.jsx
  frontend/public/components/clusters.tsx
  frontend/public/components/events.jsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/overview/index.tsx
  frontend/public/components/resource-list.tsx
  frontend/public/components/search.jsx
  frontend/public/components/start-guide.jsx
  frontend/public/components/start-guide.tsx
  frontend/public/components/utils/_disabled.scss
Labels: lgtm, size/XL

#714 Bug 1643948 - Fix crashlooping pods query
  frontend/public/components/cluster-overview.jsx
Labels: lgtm, size/XS

#717 Fix link to the service bindings tab
  frontend/public/components/service-instance.tsx
Labels: lgtm, size/S

#692 Upgrade react-virtualized to v9.21.0
  frontend/yarn.lock
  sources
Labels: lgtm, size/S

#720 Monitoring nav fixes
  frontend/public/components/nav.jsx
Labels: lgtm, size/XS

#672 Add missing describe attributes for help-block elements
  frontend/integration-tests/tests/deploy-image.scenario.ts
  frontend/public/components/deploy-image.tsx
  frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
  frontend/public/components/modals/configure-update-strategy-modal.jsx
  frontend/public/components/routes/create-route.tsx
  frontend/public/components/source-to-image.tsx
  frontend/public/components/utils/dropdown.jsx
Labels: lgtm, size/M

#703 Order pods by usage in overview metrics tooltip
  frontend/public/components/overview/project-overview.tsx
Labels: lgtm, size/S

#715 Add "Silenced" state for Monitoring Alerts
  frontend/public/components/app.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/silence.tsx
  frontend/public/module/monitoring.js
  frontend/public/ui/ui-reducers.js
Labels: lgtm, size/XXL

#723 Only import patternfly-react* scss partials that are in use
  frontend/public/style.scss
  frontend/public/vendor.scss
Labels: lgtm, size/S
