Repository openshift/console, pull requests merged in 2019-05, with the labels that each got.

#1513 Bug 1702783: Fix Bugs with Operator CR View
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
  frontend/public/components/modals/delete-modal.jsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
  frontend/public/components/operator-lifecycle-manager/k8s-resource.tsx
Labels: approved, lgtm, size/M

#1511 Use a case-insensitive sort for OperatorHub and Developer Catalog
  frontend/__tests__/components/operator-hub/operator-hub.spec.tsx
  frontend/public/components/catalog/catalog-items.jsx
  frontend/public/components/operator-hub/operator-hub-items.tsx
  frontend/public/components/operator-hub/operator-hub-page.tsx
Labels: approved, lgtm, size/XS

#1514 New OpenShift logos
  frontend/public/imgs/openshift-dedicated-logo.svg
  frontend/public/imgs/openshift-logo.svg
  frontend/public/imgs/openshift-online-logo.svg
  frontend/public/imgs/openshift-platform-logo.svg
  frontend/public/imgs/pfbg_2000.jpg
  frontend/public/style/_overrides.scss
Labels: approved, lgtm, size/M

#1515 Use `global-operators` for installing in all namespaces
  frontend/public/components/operator-hub/operator-hub-subscribe.tsx
Labels: approved, lgtm, size/XS

#1517 Merge master into master-next
  frontend/__tests__/components/operator-hub/operator-hub.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
  frontend/public/components/_masthead.scss
  frontend/public/components/catalog/catalog-items.jsx
  frontend/public/components/cluster-settings/cluster-settings.tsx
  frontend/public/components/cluster-settings/cluster-version.tsx
  frontend/public/components/masthead-toolbar.jsx
  frontend/public/components/modals/delete-modal.jsx
  frontend/public/components/namespace.jsx
  frontend/public/components/operator-hub/operator-hub-items.tsx
  frontend/public/components/operator-hub/operator-hub-page.tsx
  frontend/public/components/operator-hub/operator-hub-subscribe.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
  frontend/public/components/operator-lifecycle-manager/k8s-resource.tsx
  frontend/public/components/resource-pages.ts
  frontend/public/imgs/openshift-dedicated-logo.svg
  frontend/public/imgs/openshift-logo.svg
  frontend/public/imgs/openshift-online-logo.svg
  frontend/public/imgs/openshift-platform-logo.svg
  frontend/public/imgs/pfbg_2000.jpg
  frontend/public/style/_overrides.scss
Labels: approved, lgtm, size/L

#1519 Add copy login command link to request token page
  auth/auth.go
  auth/auth_oidc.go
  auth/auth_openshift.go
  frontend/public/components/masthead-toolbar.jsx
  frontend/public/components/modals/command-line-tools-modal.tsx
  server/server.go
Labels: approved, lgtm, size/M

#1508 Remove unused cluster-health component
  frontend/public/components/app.jsx
  frontend/public/components/cluster-health.jsx
  frontend/public/components/graphs/graph-loader.jsx
  frontend/public/components/graphs/index.jsx
  frontend/public/components/graphs/scalar.jsx
Labels: approved, lgtm, size/L

#1520 Show node OS image on node details page
  frontend/public/components/node.tsx
Labels: approved, lgtm, size/XS

#1523 [OKD-Core] Check namespace before deleting it
  frontend/integration-tests/protractor.conf.ts
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1525 Allow users to cancel invalid cluster updates
  frontend/public/components/cluster-settings/cluster-settings.tsx
  frontend/public/module/k8s/cluster-settings.ts
  frontend/public/module/k8s/index.ts
Labels: approved, lgtm, size/M

#1529 Fix event links to custom resources
  frontend/public/components/events.jsx
Labels: approved, lgtm, size/XS

#1512 Add Remote Auth IDP Page
  frontend/public/components/app.jsx
  frontend/public/components/cluster-settings/basicauth-idp-form.tsx
  frontend/public/components/cluster-settings/oauth.tsx
Labels: approved, lgtm, size/L

#1526 Update cluster manager URL
  frontend/public/components/masthead-toolbar.jsx
Labels: approved, lgtm, size/XS

#1530 Fix OperatorHub test scenario
  frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts
  frontend/integration-tests/views/catalog-page.view.ts
  frontend/public/components/utils/tile-view-page.jsx
Labels: approved, lgtm, size/XS

#1527 Add dedicated Cluster Status nav item under Administration
  frontend/public/components/app.jsx
  frontend/public/components/nav.jsx
Labels: approved, lgtm, size/XS

#1524 Add keyboard shortcuts to overview and list page filter
  frontend/__tests__/components/factory/list-page.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
  frontend/integration-tests/views/crud.view.ts
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/custom-resource-definition.tsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/hpa.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/install-plan.tsx
  frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
  frontend/public/components/overview/_overview.scss
  frontend/public/components/overview/index.tsx
  frontend/public/components/overview/project-overview.tsx
  frontend/public/components/resource-quota.jsx
  frontend/public/components/service-binding.tsx
  frontend/public/components/service-instance.tsx
  frontend/public/const.js
  frontend/public/style/_base.scss
  frontend/public/style/_common.scss
  frontend/public/style/_overrides.scss
  frontend/public/style/_vars.scss
Labels: approved, lgtm, size/L

#1535 Position app launcher right like other masthead dropdowns
  frontend/public/components/masthead-toolbar.jsx
Labels: approved, lgtm, size/XS

#1534 Scroll overview items into view when selected by keyboard
  frontend/public/components/overview/project-overview.tsx
Labels: approved, lgtm, size/S

#1532 frontend: minor dependency bumps
  frontend/package.json
  frontend/yarn.lock
Labels: approved, lgtm, size/M

#1538 Bug 1706772 - Fix duplicate node selector on pod page
  frontend/public/components/pod.jsx
Labels: approved, lgtm, size/XS

#1531 Merge master into master-next
  auth/auth.go
  auth/auth_oidc.go
  auth/auth_openshift.go
  frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts
  frontend/integration-tests/views/catalog-page.view.ts
  frontend/public/components/app.jsx
  frontend/public/components/cluster-health.jsx
  frontend/public/components/cluster-settings/cluster-settings.tsx
  frontend/public/components/events.jsx
  frontend/public/components/graphs/graph-loader.jsx
  frontend/public/components/graphs/index.jsx
  frontend/public/components/graphs/scalar.jsx
  frontend/public/components/masthead-toolbar.jsx
  frontend/public/components/modals/command-line-tools-modal.tsx
  frontend/public/components/nav.jsx
  frontend/public/components/node.tsx
  frontend/public/components/pod.tsx
  frontend/public/components/utils/tile-view-page.jsx
  frontend/public/module/k8s/cluster-settings.ts
  frontend/public/module/k8s/index.ts
  server/server.go
Labels: approved, lgtm, size/L

#1540 login scenario: look for oauth-openshift hostname
  frontend/integration-tests/tests/login.scenario.ts
Labels: approved, lgtm, size/XS

#1541 Merge master into master-next
  frontend/integration-tests/tests/login.scenario.ts
Labels: approved, lgtm, size/XS

#1489 Move QuestionCircleIcon component in front of the help text
  frontend/public/components/routes.tsx
Labels: approved, lgtm, size/XS

#1537 Adding Basic Implementation for expand PVC
  frontend/public/components/modals/expand-pvc-modal.jsx
  frontend/public/components/modals/index.ts
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/utils/kebab.tsx
Labels: approved, lgtm, ok-to-test, size/M

#1448 Replace plotly line chart with pf-react area chart
  frontend/package.json
  frontend/public/components/app.jsx
  frontend/public/components/build.tsx
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/graphs/area.tsx
  frontend/public/components/graphs/graph-loader.jsx
  frontend/public/components/graphs/index.jsx
  frontend/public/components/graphs/prometheus-graph.tsx
  frontend/public/components/graphs/themes.tsx
  frontend/public/components/graphs/use-prometheus-poll.ts
  frontend/public/components/image-stream-tag.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/node.tsx
  frontend/public/components/pod.tsx
  frontend/public/components/utils/datetime.ts
  frontend/public/components/utils/units.js
  frontend/public/components/utils/use-ref-width.ts
  frontend/yarn.lock
Labels: approved, lgtm, size/XL

#1454 Fix dropdown usage in cluster update dialog
  frontend/public/components/modals/cluster-update-modal.tsx
Labels: approved, lgtm, size/M

#1516 Add machine autoscaler modal
  frontend/__tests__/features.spec.tsx
  frontend/public/components/machine-autoscaler.tsx
  frontend/public/components/machine-set.tsx
  frontend/public/components/modals/configure-machine-autoscaler-modal.tsx
  frontend/public/components/modals/index.ts
  frontend/public/components/nav.jsx
  frontend/public/components/resource-pages.ts
  frontend/public/components/utils/number-spinner.tsx
  frontend/public/features.ts
  frontend/public/models/index.ts
  frontend/public/models/yaml-templates.ts
  frontend/public/style/_text.scss
Labels: approved, lgtm, size/L

#1547 Improve Impersonation
  frontend/public/ui/ui-actions.js
Labels: approved, lgtm, size/XS

#1545 Bug 1691282: Relax RBAC checks for Operator Management nav
  frontend/public/components/nav.jsx
  frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
Labels: approved, lgtm, size/XS

#1550 Fix hot-loop issue with prometheus poll and ref width effects
  frontend/public/components/graphs/use-prometheus-poll.ts
  frontend/public/components/utils/use-ref-width.ts
Labels: approved, lgtm, size/S

#1391 Add option for custom branding
  cmd/bridge/config.go
  cmd/bridge/main.go
  frontend/public/components/about-modal.tsx
  frontend/public/components/masthead.jsx
  frontend/public/index.html
  frontend/public/style/_overrides.scss
  server/server.go
Labels: approved, lgtm, size/L

#1551 Add missing rel attribute to <ExternalLink>
  frontend/public/components/nav.jsx
Labels: approved, lgtm, size/XS

#1552 Convert link utils to TypeScript
  frontend/public/components/utils/link.tsx
Labels: approved, lgtm, size/S

#1518 Add status page icon for dedicated and online
  cmd/bridge/config.go
  cmd/bridge/main.go
  frontend/public/components/_masthead.scss
  frontend/public/components/masthead-toolbar.jsx
  frontend/public/style/_overrides.scss
  frontend/public/vendor.scss
  server/server.go
Labels: approved, lgtm, size/M

#1554 Convert selector components to TypeScript
  frontend/public/components/utils/selector.tsx
Labels: approved, lgtm, size/S

#1553 Remove dead container linux update code
  frontend/public/components/container-linux-update-operator/container-linux-update-details.jsx
  frontend/public/components/container-linux-update-operator/container-linux-updates.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/utils/container-linux-update-operator.js
  frontend/public/components/utils/index.tsx
Labels: approved, lgtm, size/L

#1491 Show example docker commands for pushing and pulling image stream tags
  frontend/public/components/_image-stream.scss
  frontend/public/components/image-stream.tsx
  frontend/public/style.scss
Labels: approved, lgtm, size/M

#1557 Bug 1708235: Monitoring: Fix graph controls layout on mobile
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/graphs/query-browser.jsx
Labels: approved, lgtm, size/M

#1556 Convert status box components to TypeScript
  frontend/public/components/utils/status-box.jsx
  frontend/public/components/utils/status-box.tsx
Labels: approved, lgtm, size/L

#1562 build-backend.sh: use SOURCE_GIT_TAG if available
  build-backend.sh
Labels: approved, lgtm, size/XS

#1555 Convert deployment components to TypeScript
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.tsx
  frontend/public/components/utils/kebab.tsx
Labels: approved, lgtm, size/M

#1546 Bump PatternFly to latest
  frontend/package.json
  frontend/public/components/nav.jsx
  frontend/public/style/_overrides.scss
  frontend/public/vendor.scss
  frontend/webpack.config.ts
  frontend/yarn.lock
Labels: approved, lgtm, size/L

#1568 Add Type Definition for Global `window`
  frontend/integration-tests/protractor.conf.ts
  frontend/public/actions/features.ts
  frontend/public/actions/ui.ts
  frontend/public/components/about-modal.tsx
  frontend/public/components/factory/modal.tsx
  frontend/public/components/modals/command-line-tools-modal.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/utils/documentation.tsx
  frontend/public/components/utils/link.tsx
  frontend/public/components/utils/router.ts
  frontend/public/components/utils/webhooks.tsx
  frontend/public/const.ts
  frontend/public/declarations.d.ts
  frontend/public/module/k8s/get-resources.ts
  frontend/public/module/k8s/k8s.ts
  frontend/public/reducers/features.ts
Labels: approved, lgtm, size/M

#1558 reduce unnecessary rendering from state changes
  frontend/public/components/app-contents.tsx
  frontend/public/components/app.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/masthead-toolbar.jsx
  frontend/public/components/masthead.jsx
  frontend/public/components/nav.jsx
  frontend/public/components/utils/firehose.jsx
  frontend/public/reducers/features.ts
  frontend/public/redux.ts
  frontend/yarn.lock
Labels: approved, lgtm, size/XL

#1566 add miss dot for activeTab
  frontend/integration-tests/views/horizontal-nav.view.ts
Labels: approved, lgtm, size/XS

#1573 fix: ui reducer sortList
  frontend/public/reducers/ui.ts
Labels: approved, lgtm, size/XS

#1569 Add skeleton screen for list view
  frontend/public/components/factory/list.tsx
  frontend/public/components/utils/_skeleton-screen.scss
  frontend/public/components/utils/status-box.tsx
  frontend/public/style.scss
Labels: approved, lgtm, size/M

#1576 Bug 1706868: Add node's status to node's details page
  frontend/public/components/node.tsx
Labels: approved, lgtm, size/XS

#1564 Add request header idp
  frontend/public/components/app-contents.tsx
  frontend/public/components/cluster-settings/idp-cafile-input.tsx
  frontend/public/components/cluster-settings/oauth.tsx
  frontend/public/components/cluster-settings/request-header-idp-form.tsx
Labels: approved, lgtm, size/L

#1560 Default SC
  frontend/public/components/storage-class.tsx
  frontend/public/style.scss
  frontend/public/style/_storage-class.scss
Labels: approved, lgtm, ok-to-test, size/S

#1559 Add RBAC checks to create buttons and action menus
  frontend/__tests__/components/factory/list-page.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/subscription.spec.tsx
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/integration-tests/tests/deploy-image.scenario.ts
  frontend/integration-tests/tests/environment.scenario.ts
  frontend/integration-tests/tests/filter.scenario.ts
  frontend/integration-tests/tests/modal-annotations.scenario.ts
  frontend/integration-tests/tests/monitoring.scenario.ts
  frontend/integration-tests/tests/olm/update-channel-approval.scenario.ts
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/integration-tests/views/monitoring.view.ts
  frontend/integration-tests/views/secrets.view.ts
  frontend/public/components/_dropdown.scss
  frontend/public/components/_edit-yaml.scss
  frontend/public/components/build-config.tsx
  frontend/public/components/build.tsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.tsx
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/job.jsx
  frontend/public/components/machine-config-pool.tsx
  frontend/public/components/machine-set.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/node.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/components/secret.jsx
  frontend/public/components/service-account.jsx
  frontend/public/components/service-instance.tsx
  frontend/public/components/utils/dropdown.jsx
  frontend/public/components/utils/headings.tsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/kebab.tsx
  frontend/public/components/utils/rbac.tsx
  frontend/public/module/k8s/index.ts
  frontend/public/reducers/ui.ts
Labels: approved, lgtm, size/XL

#1579 init overview state on mount to ensure resource lists are rendered
  frontend/public/components/overview/index.tsx
Labels: approved, lgtm, size/S

#1578 Fix runtime error when monitoring URLs aren't defined
  frontend/public/components/graphs/area.tsx
  frontend/public/components/graphs/prometheus-graph.tsx
Labels: approved, lgtm, size/S

#1574 Skip Auth Test Scenario for Vanilla Kubernetes
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/login.scenario.ts
Labels: approved, lgtm, size/L

#1583 Add Cancel Action to builds
  frontend/public/components/build.tsx
  frontend/public/components/factory/modal.tsx
  frontend/public/components/modals/confirm-modal.jsx
Labels: approved, lgtm, size/M

#1528 Add ModelFeatureFlag and improve plugin support
  frontend/__tests__/reducers/features.spec.tsx
  frontend/package.json
  frontend/packages/console-demo-plugin/src/plugin.ts
  frontend/packages/console-plugin-sdk/src/codegen/__tests__/index.spec.ts
  frontend/packages/console-plugin-sdk/src/codegen/index.ts
  frontend/packages/console-plugin-sdk/src/registry.ts
  frontend/packages/console-plugin-sdk/src/typings/features.ts
  frontend/packages/console-plugin-sdk/src/typings/index.ts
  frontend/packages/console-plugin-sdk/src/typings/nav.ts
  frontend/packages/console-plugin-sdk/src/typings/pages.ts
  frontend/public/actions/features.ts
  frontend/public/components/app.jsx
  frontend/public/plugins.ts
  frontend/public/reducers/features.ts
  frontend/webpack.config.ts
  frontend/yarn.lock
Labels: approved, lgtm, size/L

#1543 Added tests for normal user nav items
  frontend/integration-tests/tests/login.scenario.ts
Labels: approved, lgtm, size/S

#1585 Improve OperatorHub Scenarios
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/olm/catalog.scenario.ts
  frontend/integration-tests/tests/olm/global-installmode.scenario.ts
  frontend/integration-tests/tests/olm/single-installmode.scenario.ts
  frontend/integration-tests/tests/olm/update-channel-approval.scenario.ts
  frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts
  frontend/integration-tests/views/catalog-page.view.ts
  frontend/integration-tests/views/olm-catalog.view.ts
  frontend/integration-tests/views/operator-hub.view.ts
  frontend/public/components/operator-lifecycle-manager/index.tsx
Labels: approved, lgtm, size/L

#1533 auto integration test for envFrom editor
  frontend/integration-tests/tests/environment.scenario.ts
  frontend/integration-tests/views/environment.view.ts
  frontend/public/components/utils/name-value-editor.jsx
Labels: approved, lgtm, size/M

#1582 Add RBAC checks for role bindings
  frontend/public/components/RBAC/bindings.jsx
Labels: approved, lgtm, size/M

#1590 Showing pvc expansion status under conditions and Redirection to Details Page
  frontend/public/components/modals/expand-pvc-modal.jsx
  frontend/public/components/persistent-volume-claim.jsx
Labels: approved, lgtm, ok-to-test, size/M

#1584 Improve nav item extensions
  frontend/packages/console-demo-plugin/src/plugin.ts
  frontend/packages/console-plugin-sdk/src/typings/nav.ts
  frontend/public/components/nav/index.jsx
  frontend/public/components/nav/items.tsx
  frontend/public/components/nav/section.tsx
  frontend/public/declarations.d.ts
  frontend/public/redux.ts
Labels: approved, lgtm, size/XL

#1587 Add help and aria described by to list input component
  frontend/public/components/cluster-settings/github-idp-form.tsx
  frontend/public/components/cluster-settings/ldap-idp-form.tsx
  frontend/public/components/cluster-settings/openid-idp-form.tsx
  frontend/public/components/cluster-settings/request-header-idp-form.tsx
  frontend/public/components/utils/_list-input.scss
  frontend/public/components/utils/list-input.tsx
Labels: approved, lgtm, size/M

#1588 Add additional ClusterVersion detail to about dialog
  frontend/public/actions/features.ts
  frontend/public/actions/ui.ts
  frontend/public/components/about-modal.tsx
  frontend/public/reducers/ui.ts
Labels: approved, lgtm, size/M

#1261 Updated pv and pvc page with status and capacity metrics fields
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/persistent-volume.jsx
Labels: approved, lgtm, ok-to-test, size/M

#1593 Add example docker commands popover to imageStreamTag page
  frontend/public/components/image-stream-tag.tsx
  frontend/public/components/image-stream.tsx
Labels: approved, lgtm, size/S

#1595 fix: items startsWith helper
  frontend/public/components/nav/items.tsx
  frontend/public/components/nav/section.tsx
Labels: approved, lgtm, size/XS

#1594 backend: remove obsolete TectonicVersion and TectonicCACertFile
  cmd/bridge/main.go
  server/server.go
Labels: approved, lgtm, size/S

#1597 Tweak cluster operator details
  frontend/public/components/cluster-settings/cluster-operator.tsx
Labels: approved, lgtm, size/M

#1599 Fix envFrom e2e test script
  frontend/integration-tests/views/environment.view.ts
Labels: approved, lgtm, size/XS

#1600 kinds.ts: Fix connectToPlural() for plugin's models
  frontend/public/kinds.ts
Labels: approved, lgtm, ok-to-test, size/XS

#1601 Fix bad YAML indentation in network policy example
  frontend/public/models/yaml-templates.ts
Labels: approved, lgtm, size/XS

#1602 Bug 1709964: Add kind not found error to provided API page
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
Labels: approved, lgtm, size/S

#1571 Add build status to overview row alerts
  frontend/public/components/build.tsx
  frontend/public/components/container.tsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.tsx
  frontend/public/components/job.jsx
  frontend/public/components/namespace.jsx
  frontend/public/components/node.tsx
  frontend/public/components/overview/build-overview.tsx
  frontend/public/components/overview/index.tsx
  frontend/public/components/overview/project-overview.tsx
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/persistent-volume.jsx
  frontend/public/components/pod.tsx
  frontend/public/components/routes.tsx
  frontend/public/components/template-instance.tsx
  frontend/public/components/utils/service-catalog-status.tsx
  frontend/public/components/utils/status-icon.tsx
Labels: approved, lgtm, size/L

#1606 Set default sort for CRD list
  frontend/public/components/custom-resource-definition.tsx
Labels: approved, lgtm, size/XS

#1607 Bug 1713193: Break long node names in pod list table
  frontend/public/components/pod.tsx
Labels: approved, lgtm, size/XS

#1610 Bug 1713209: Redirect to RC after instantiating DC
  frontend/public/components/deployment-config.tsx
Labels: approved, lgtm, size/S

#1596 Make prometheus poll more generic, only handle one prometheus query
  frontend/public/components/build.tsx
  frontend/public/components/cluster-overview.jsx
  frontend/public/components/graphs/area.tsx
  frontend/public/components/graphs/base.jsx
  frontend/public/components/graphs/graph-loader.ts
  frontend/public/components/graphs/helpers.ts
  frontend/public/components/graphs/index.jsx
  frontend/public/components/graphs/prometheus-graph.tsx
  frontend/public/components/graphs/prometheus-poll-hook.ts
  frontend/public/components/graphs/status.jsx
  frontend/public/components/graphs/themes.ts
  frontend/public/components/graphs/use-prometheus-poll.ts
  frontend/public/components/namespace.jsx
  frontend/public/components/node.tsx
  frontend/public/components/overview/index.tsx
  frontend/public/components/pod.tsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/poll-hook.ts
  frontend/public/components/utils/ref-width-hook.ts
  frontend/public/components/utils/safe-fetch-hook.ts
Labels: approved, lgtm, size/XL

#1589 Add Explore Type sidebar to YAML editor
  frontend/package.json
  frontend/public/components/app.jsx
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/sidebars/explore-type-sidebar.tsx
  frontend/public/components/sidebars/resource-sidebar.jsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/link.tsx
  frontend/public/const.ts
  frontend/public/module/k8s/autocomplete.ts
  frontend/public/module/k8s/index.ts
  frontend/public/module/k8s/swagger.ts
  frontend/yarn.lock
Labels: approved, lgtm, size/L

#1612 Monitoring: Switch graphs from Plotly to Victory
  frontend/public/components/graphs/area.tsx
  frontend/public/components/graphs/graph-loader.ts
  frontend/public/components/graphs/helpers.ts
  frontend/public/components/graphs/index.jsx
  frontend/public/components/graphs/line.jsx
  frontend/public/components/graphs/prometheus-graph.tsx
  frontend/public/components/graphs/prometheus-poll-hook.ts
  frontend/public/components/graphs/query-browser.jsx
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/utils/poll-hook.ts
Labels: approved, lgtm, size/XL

#1614 Monitoring: Fix show / hide graph button
  frontend/public/actions/ui.ts
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/S

#1617 Query Browser: Display "{}" when a data series has no labels
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/XS

#1616 Monitoring: Display Prometheus API error message if available
  frontend/public/components/graphs/query-browser.tsx
Labels: approved, lgtm, size/XS

#1618 Query Browser: Add Run Queries button
  frontend/public/components/graphs/prometheus-poll-hook.ts
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/M

#1611 remove unnecessary intermediate DOM nodes
  frontend/integration-tests/views/crud.view.ts
  frontend/public/components/catalog/_catalog.scss
  frontend/public/components/catalog/catalog-page.jsx
  frontend/public/components/utils/details-page.tsx
  frontend/public/components/utils/firehose.jsx
  frontend/public/components/utils/status-box.tsx
Labels: approved, lgtm, size/M

#1586 Support models declared by plugins
  frontend/__tests__/module/k8s/k8s-models.spec.ts
  frontend/packages/console-demo-plugin/src/models.ts
  frontend/packages/console-demo-plugin/src/plugin.ts
  frontend/packages/console-plugin-sdk/src/codegen/__tests__/index.spec.ts
  frontend/packages/console-plugin-sdk/src/codegen/index.ts
  frontend/packages/console-plugin-sdk/src/registry.ts
  frontend/packages/console-plugin-sdk/src/typings/index.ts
  frontend/packages/console-plugin-sdk/src/typings/models.ts
  frontend/public/module/k8s/k8s-models.ts
  frontend/public/plugins.ts
  frontend/webpack.config.ts
Labels: approved, lgtm, size/L

#1620 Query browser: Better handle blank query and empty API response cases
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/L

#1622 Query Browser: Remove unnecessary use of PrometheusGraph
  frontend/public/components/graphs/prometheus-graph.tsx
  frontend/public/components/graphs/query-browser.tsx
Labels: approved, lgtm, size/S

#1308 Changes to PVC Overview
  frontend/public/components/persistent-volume-claim.jsx
Labels: approved, lgtm, ok-to-test, size/S

#1625 Query Browser: Add Hide Graph / Show Graph button
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/S

#1615 add Perspective extension and default admin perspective
  frontend/__tests__/actions/ui.spec.ts
  frontend/__tests__/reducers/ui.spec.ts
  frontend/packages/console-app/package.json
  frontend/packages/console-app/src/plugin.tsx
  frontend/packages/console-demo-plugin/package.json
  frontend/packages/console-demo-plugin/src/plugin.tsx
  frontend/packages/console-plugin-sdk/src/codegen/__tests__/index.spec.ts
  frontend/packages/console-plugin-sdk/src/codegen/index.ts
  frontend/packages/console-plugin-sdk/src/registry.ts
  frontend/packages/console-plugin-sdk/src/typings/index.ts
  frontend/packages/console-plugin-sdk/src/typings/perspective.ts
  frontend/public/actions/ui.ts
  frontend/public/components/masthead-toolbar.jsx
  frontend/public/const.ts
  frontend/public/reducers/ui.ts
Labels: approved, lgtm, size/L

#1608 Addition of skeleton screen for catalog and operatorhub tile views
  frontend/public/components/catalog/catalog-page.jsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/operator-hub/operator-hub-items.tsx
  frontend/public/components/operator-hub/operator-hub-page.tsx
  frontend/public/components/utils/_skeleton-screen.scss
  frontend/public/components/utils/status-box.tsx
  frontend/public/components/utils/tile-view-page.jsx
  frontend/public/style.scss
Labels: approved, lgtm, size/L

#1609 NavSection: allow plugins to define their position
  frontend/packages/console-plugin-sdk/src/typings/nav.ts
  frontend/public/components/nav/section.tsx
Labels: approved, lgtm, ok-to-test, size/M

#1634 Fix timeout prop type for Prometheus API poller
  frontend/public/components/graphs/area.tsx
  frontend/public/components/graphs/helpers.ts
  frontend/public/components/graphs/prometheus-poll-hook.ts
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/S

#1630 Fix `api-allow-http-and-https` NetworkPolicy sample
  frontend/public/models/yaml-templates.ts
Labels: approved, lgtm, size/S

#1632 Simplify oc-environment.sh
  contrib/oc-environment.sh
Labels: approved, lgtm, size/XS

#1638 Code fixups
  frontend/packages/console-plugin-sdk/src/typings/features.ts
  frontend/packages/console-plugin-sdk/src/typings/models.ts
  frontend/packages/console-plugin-sdk/src/typings/nav.ts
  frontend/packages/console-plugin-sdk/src/typings/pages.ts
  frontend/packages/console-plugin-sdk/src/typings/perspective.ts
  frontend/public/components/nav/section.tsx
Labels: approved, lgtm, size/M

#1635 Query Browser: Add a link to the Prometheus UI expression browser
  frontend/public/components/graphs/prometheus-graph.tsx
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/S

#1613 Add YAML template extension
  frontend/packages/console-demo-plugin/src/plugin.tsx
  frontend/packages/console-demo-plugin/src/yaml-templates.ts
  frontend/packages/console-plugin-sdk/src/registry.ts
  frontend/packages/console-plugin-sdk/src/typings/index.ts
  frontend/packages/console-plugin-sdk/src/typings/yaml-templates.ts
  frontend/public/models/yaml-templates.ts
Labels: approved, lgtm, size/M

#1642 Quarantine flakey tests
  frontend/integration-tests/tests/environment.scenario.ts
  frontend/integration-tests/tests/filter.scenario.ts
Labels: approved, lgtm, size/XS

#1644 Bump @patternfly/patternfly and @patternfly/react-core to latest
  frontend/package.json
  frontend/yarn.lock
Labels: approved, lgtm, size/L

#1646 Monitoring: Clean up page headings DOM
  frontend/integration-tests/views/monitoring.view.ts
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/S

#1626 The .co-actions-menu button within the <h1 co-resource-item> loads la…
  frontend/public/components/_nav-title.scss
Labels: approved, lgtm, size/S
