Repository openshift/console, pull requests merged in 2019-06, with the labels that each got.

#1581 Add RBAC checks to the env var editor
  frontend/__tests__/components/environment.spec.tsx
  frontend/public/components/environment.jsx
Labels: approved, lgtm, size/M

#1633 More README updates
  CONTRIBUTING.md
  README.md
  STYLEGUIDE.md
Labels: approved, lgtm, size/M

#1647 Keystone IDP: make domain required
  frontend/public/components/cluster-settings/keystone-idp-form.tsx
Labels: approved, lgtm, size/XS

#1628 separate perspective based navigation menus
  frontend/packages/console-demo-plugin/src/plugin.tsx
  frontend/packages/console-plugin-sdk/src/registry.ts
  frontend/packages/console-plugin-sdk/src/typings/nav.ts
  frontend/public/components/nav/admin-nav.tsx
  frontend/public/components/nav/index.jsx
  frontend/public/components/nav/index.tsx
  frontend/public/components/nav/items.tsx
  frontend/public/components/nav/perspective-nav.tsx
  frontend/public/components/nav/section.tsx
Labels: approved, lgtm, size/XL

#1643 Move filters and add category to OperatorHub
  frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts
  frontend/integration-tests/views/catalog-page.view.ts
  frontend/public/components/catalog/_catalog.scss
  frontend/public/components/operator-hub/operator-hub-items.tsx
  frontend/public/components/operator-hub/operator-hub-page.tsx
  frontend/public/components/utils/tile-view-page.jsx
Labels: approved, lgtm, size/L

#1650 integration tests: fix error setting up htpasswd IDP
  README.md
  frontend/integration-tests/data/htpasswd-idp.yaml
  frontend/integration-tests/data/htpasswd-secret.yaml
  frontend/integration-tests/data/patch-htpasswd.yaml
  test-prow-e2e.sh
Labels: approved, lgtm, priority/critical-urgent, queue/blocks-others, queue/critical-fix, size/M

#1649 Add OWNERS file to plugin SDK package
  frontend/packages/console-plugin-sdk/OWNERS
Labels: approved, lgtm, size/XS

#1621 Update README to include pushing custom image to OpenShift Cluster
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#1645 add eslint package to monorepo
  frontend/.eslintrc
  frontend/.vscode/settings.json
  frontend/package.json
  frontend/packages/.eslintrc
  frontend/packages/.eslintrc.js
  frontend/packages/console-app/src/plugin.tsx
  frontend/packages/console-demo-plugin/src/plugin.tsx
  frontend/packages/console-demo-plugin/src/yaml-templates.ts
  frontend/packages/console-plugin-sdk/src/codegen/__tests__/index.spec.ts
  frontend/packages/console-plugin-sdk/src/codegen/index.ts
  frontend/packages/console-plugin-sdk/src/registry.ts
  frontend/packages/console-plugin-sdk/src/typings/extension.ts
  frontend/packages/console-plugin-sdk/src/typings/features.ts
  frontend/packages/console-plugin-sdk/src/typings/index.ts
  frontend/packages/console-plugin-sdk/src/typings/models.ts
  frontend/packages/console-plugin-sdk/src/typings/nav.ts
  frontend/packages/console-plugin-sdk/src/typings/pages.ts
  frontend/packages/console-plugin-sdk/src/typings/perspective.ts
  frontend/packages/console-plugin-sdk/src/typings/yaml-templates.ts
  frontend/packages/eslint-plugin-console/.eslintrc
  frontend/packages/eslint-plugin-console/README.md
  frontend/packages/eslint-plugin-console/index.js
  frontend/packages/eslint-plugin-console/lib/config/base.js
  frontend/packages/eslint-plugin-console/lib/config/jest.js
  frontend/packages/eslint-plugin-console/lib/config/node.js
  frontend/packages/eslint-plugin-console/lib/config/prettier.js
  frontend/packages/eslint-plugin-console/lib/config/react.js
  frontend/packages/eslint-plugin-console/lib/config/rules/airbnb-base-overrides.js
  frontend/packages/eslint-plugin-console/lib/config/rules/jest.js
  frontend/packages/eslint-plugin-console/lib/config/rules/node.js
  frontend/packages/eslint-plugin-console/lib/config/rules/prettier-typescript.js
  frontend/packages/eslint-plugin-console/lib/config/rules/promise.js
  frontend/packages/eslint-plugin-console/lib/config/rules/react-hooks.js
  frontend/packages/eslint-plugin-console/lib/config/rules/react.js
  frontend/packages/eslint-plugin-console/lib/config/rules/sort-class-members.js
  frontend/packages/eslint-plugin-console/lib/config/rules/typescript.js
  frontend/packages/eslint-plugin-console/lib/config/typescript-parser.js
  frontend/packages/eslint-plugin-console/lib/config/typescript.js
  frontend/packages/eslint-plugin-console/package.json
  frontend/yarn.lock
Labels: approved, lgtm, size/XXL

#1624 Bug 1714897 - Change deployment status checks
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.tsx
Labels: approved, lgtm, size/S

#1654 temporarily disable formatOnSave vscode
  frontend/.vscode/settings.json
Labels: approved, lgtm, size/S

#1655 revert changes to status-box loading-box__loaded
  frontend/public/components/utils/status-box.tsx
Labels: approved, lgtm, size/XS

#1657 Adding providers with statuspageID
  cmd/bridge/config.go
  cmd/bridge/main.go
Labels: approved, lgtm, size/S

#1666 Fix overlapping text in Machine Configs table
  frontend/public/components/machine-config.tsx
Labels: approved, lgtm, size/XS

#1639 Updates to Custom Resource details view
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
  frontend/public/components/operator-lifecycle-manager/descriptors/status/index.tsx
  frontend/public/components/utils/status-icon.tsx
Labels: approved, lgtm, size/L

#1663 small UI changes to Create Operator Subscription
  frontend/public/components/operator-hub/operator-hub-subscribe.tsx
Labels: approved, lgtm, size/S

#1659 Align prettier printWidth configuration for .js and .ts files
  frontend/.prettierrc
  frontend/packages/eslint-plugin-console/lib/config/prettier.js
  frontend/packages/eslint-plugin-console/lib/config/react.js
  frontend/packages/eslint-plugin-console/lib/config/rules/airbnb-base-overrides.js
Labels: approved, lgtm, size/M

#1667 Temp fix to restore About modal opening
  frontend/public/components/masthead-toolbar.jsx
Labels: approved, lgtm, size/XS

#1669 Improve CatalogSource Check for OLM Tests
  frontend/integration-tests/tests/olm/catalog.scenario.ts
Labels: approved, lgtm, size/XS

#1672 initial dev-console plugin package
  frontend/packages/dev-console/OWNERS
  frontend/packages/dev-console/package.json
  frontend/public/extend/devconsole/README.md
Labels: approved, lgtm, size/S

#1664 Move "Deploying a Custom Image" to later in the README
  README.md
Labels: approved, lgtm, size/M

#1670 Add updates alert to about modal
  frontend/public/components/_about-modal.scss
  frontend/public/components/about-modal.tsx
Labels: approved, lgtm, size/M

#1652 Addition of overview (project status) skeleton screen
  frontend/public/components/overview/_overview.scss
  frontend/public/components/overview/index.tsx
  frontend/public/components/utils/_skeleton-screen.scss
Labels: approved, lgtm, size/M

#1668 add extension to contribute arbitrary pages
  frontend/__tests__/components/resource-pages.spec.tsx
  frontend/packages/console-demo-plugin/src/plugin.tsx
  frontend/packages/console-plugin-sdk/src/registry.ts
  frontend/packages/console-plugin-sdk/src/typings/pages.ts
  frontend/public/components/app-contents.tsx
  frontend/public/components/resource-list.tsx
  frontend/public/components/resource-pages.ts
Labels: approved, lgtm, queue/blocks-others, size/L

#1651 Add RBAC checks for creating roles and resource quotas
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/resource-quota.jsx
Labels: approved, lgtm, size/S

#1674 Include plugin nav items when getting active child in nav section
  frontend/public/components/nav/section.tsx
Labels: approved, lgtm, size/S

#1676 Improve API definition lookup for resources
  frontend/public/components/sidebars/explore-type-sidebar.tsx
  frontend/public/module/k8s/swagger.ts
Labels: approved, lgtm, size/S

#1675 Bug 1717533: Fix edge case evaluating services for deployment config
  frontend/public/components/overview/index.tsx
Labels: approved, lgtm, size/L

#1653 Convert bar chart component to @patternfly/react-charts bar chart
  frontend/package.json
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/graphs/area.tsx
  frontend/public/components/graphs/bar.jsx
  frontend/public/components/graphs/bar.tsx
  frontend/public/components/graphs/helpers.ts
  frontend/public/components/graphs/index.tsx
  frontend/public/components/graphs/prometheus-graph.tsx
  frontend/public/components/graphs/prometheus-poll-hook.ts
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/graphs/require-prometheus.tsx
  frontend/public/components/graphs/themes.ts
  frontend/public/components/namespace.jsx
  frontend/public/components/overview/project-overview.tsx
  frontend/public/components/utils/index.tsx
  frontend/public/components/utils/ref-width-hook.ts
  frontend/public/components/utils/truncate-middle.ts
  frontend/yarn.lock
Labels: approved, lgtm, size/XL

#1591 Add dashboards page with health card
  frontend/__tests__/actions/dashboards.spec.ts
  frontend/__tests__/reducers/dashboards.spec.ts
  frontend/packages/console-demo-plugin/src/dashboards/health.ts
  frontend/packages/console-demo-plugin/src/plugin.tsx
  frontend/packages/console-plugin-sdk/src/registry.ts
  frontend/packages/console-plugin-sdk/src/typings/dashboards.ts
  frontend/packages/console-plugin-sdk/src/typings/index.ts
  frontend/public/actions/dashboards.ts
  frontend/public/components/app-contents.tsx
  frontend/public/components/dashboard/dashboard-card/card-body.tsx
  frontend/public/components/dashboard/dashboard-card/card-header.tsx
  frontend/public/components/dashboard/dashboard-card/card-help.tsx
  frontend/public/components/dashboard/dashboard-card/card-see-all.tsx
  frontend/public/components/dashboard/dashboard-card/card-title.tsx
  frontend/public/components/dashboard/dashboard-card/card.scss
  frontend/public/components/dashboard/dashboard-card/card.tsx
  frontend/public/components/dashboard/dashboard-card/index.ts
  frontend/public/components/dashboard/dashboard.scss
  frontend/public/components/dashboard/dashboard.tsx
  frontend/public/components/dashboard/grid.tsx
  frontend/public/components/dashboard/health-card/health-body.tsx
  frontend/public/components/dashboard/health-card/health-card.scss
  frontend/public/components/dashboard/health-card/health-item.tsx
  frontend/public/components/dashboard/health-card/index.ts
  frontend/public/components/dashboard/health-card/states.ts
  frontend/public/components/dashboard/index.ts
  frontend/public/components/dashboards-page/dashboards.tsx
  frontend/public/components/dashboards-page/overview-dashboard/health-card.tsx
  frontend/public/components/dashboards-page/overview-dashboard/overview-dashboard.tsx
  frontend/public/components/dashboards-page/with-dashboard-resources.tsx
  frontend/public/reducers/dashboards.ts
  frontend/public/redux.ts
  frontend/public/style.scss
Labels: approved, lgtm, ok-to-test, size/XXL

#1539 Introduce Metal3 plugin for openshift console
  frontend/packages/console-shared/src/constants/index.ts
  frontend/packages/console-shared/src/index.ts
  frontend/packages/console-shared/src/selectors/index.ts
  frontend/packages/metal3-plugin/OWNERS
  frontend/packages/metal3-plugin/package.json
  frontend/packages/metal3-plugin/src/components/host.tsx
  frontend/packages/metal3-plugin/src/components/machine-cell.tsx
  frontend/packages/metal3-plugin/src/models.ts
  frontend/packages/metal3-plugin/src/plugin.ts
  frontend/packages/metal3-plugin/src/selectors/index.ts
Labels: approved, lgtm, size/L

#1677 Installed Operators UI updates
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
Labels: approved, lgtm, size/S

#1680 Fix OLM Create Subscription Namespace
  frontend/public/components/operator-lifecycle-manager/catalog-source.tsx
Labels: approved, lgtm, size/XS

#1592 Introduce kubevirt
  frontend/packages/kubevirt-plugin/OWNERS
  frontend/packages/kubevirt-plugin/package.json
  frontend/packages/kubevirt-plugin/src/components/vm.tsx
  frontend/packages/kubevirt-plugin/src/models.ts
  frontend/packages/kubevirt-plugin/src/plugin.ts
  frontend/packages/kubevirt-plugin/src/yaml-templates.ts
  frontend/yarn.lock
Labels: approved, lgtm, ok-to-test, size/XL

#1686 doc: update README for Go modules
  README.md
Labels: approved, lgtm, size/XS

#1684 Addition of skeleton screen for the resource detail views
  frontend/public/components/utils/_skeleton-screen.scss
  frontend/public/components/utils/horizontal-nav.tsx
Labels: approved, lgtm, size/L

#1627 Create Operator Subscription Improvements
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/__mocks__/operatorHubItemsMocks.ts
  frontend/__tests__/components/modals/disable-application-modal.spec.tsx
  frontend/__tests__/components/operator-hub/operator-hub.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/catalog-source.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/subscription.spec.tsx
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/olm/catalog.scenario.ts
  frontend/integration-tests/tests/olm/global-installmode.scenario.ts
  frontend/integration-tests/tests/olm/single-installmode.scenario.ts
  frontend/integration-tests/tests/olm/update-channel-approval.scenario.ts
  frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts
  frontend/integration-tests/views/olm-catalog.view.ts
  frontend/integration-tests/views/operator-hub.view.ts
  frontend/public/components/modals/disable-application-modal.tsx
  frontend/public/components/nav/admin-nav.tsx
  frontend/public/components/operator-hub/index.ts
  frontend/public/components/operator-hub/operator-hub-item-details.tsx
  frontend/public/components/operator-hub/operator-hub-items.tsx
  frontend/public/components/operator-hub/operator-hub-page.tsx
  frontend/public/components/operator-hub/operator-hub-subscribe.tsx
  frontend/public/components/operator-lifecycle-manager/catalog-source.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
  frontend/public/components/operator-lifecycle-manager/operator-group.tsx
  frontend/public/components/operator-lifecycle-manager/package-manifest.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/const.ts
Labels: approved, lgtm, size/XXL

#1683 Display binary data
  frontend/public/components/configmap-and-secret-data.tsx
  frontend/public/components/configmap.jsx
Labels: approved, lgtm, size/M

#1688 Query Browser: Support plotting multiple queries on the same graph
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/graphs/prometheus-graph.tsx
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/utils/safe-fetch-hook.ts
Labels: approved, lgtm, size/L

#1690 Fix Delete Subscription Redirect
  frontend/__tests__/components/modals/disable-application-modal.spec.tsx
  frontend/public/components/modals/disable-application-modal.tsx
  frontend/public/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.tsx
Labels: approved, lgtm, size/M

#1692 Query Browser: Switch from area chart to line chart
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/graphs/themes.ts
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/M

#1497 Reenable chargeback reports
  cmd/bridge/main.go
  frontend/public/components/chargeback.tsx
  frontend/public/components/factory/list.tsx
  frontend/public/components/nav/admin-nav.tsx
  frontend/public/declarations.d.ts
  frontend/public/models/index.ts
  frontend/public/models/yaml-templates.ts
  server/server.go
Labels: approved, lgtm, size/L

#1700 Restore loading skeletons to tables
  frontend/public/components/factory/table.tsx
  frontend/public/components/utils/_skeleton-screen.scss
Labels: approved, lgtm, size/XS

#1702 Bug 1719625: Add back `template-instance-status` filter
  frontend/public/components/factory/table.tsx
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1706 Change namespace bar Add actions to only Import YAML
  frontend/public/components/_dropdown.scss
  frontend/public/components/import-yaml.tsx
  frontend/public/components/namespace.jsx
Labels: approved, lgtm, size/M

#1703 Bug 1719624: Don't mark generated template parameters required
  frontend/public/components/instantiate-template.tsx
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1704 Move golang packages under /pkg as is convention
  build-backend.sh
  cmd/bridge/main.go
  pkg/auth/OWNERS
  pkg/auth/auth.go
  pkg/auth/auth_oidc.go
  pkg/auth/auth_openshift.go
  pkg/auth/auth_test.go
  pkg/auth/loginstate.go
  pkg/auth/loginstate_test.go
  pkg/auth/session.go
  pkg/auth/session_test.go
  pkg/auth/util.go
  pkg/server/certs.go
  pkg/server/certs_test.go
  pkg/server/middleware.go
  pkg/server/server.go
  pkg/version/version.go
  test-backend.sh
Labels: approved, lgtm, size/S

#1707 clean up grid classes
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/alert-manager.tsx
  frontend/public/components/build-config.tsx
  frontend/public/components/build.tsx
  frontend/public/components/chargeback.tsx
  frontend/public/components/cluster-service-broker.tsx
  frontend/public/components/cluster-service-class.tsx
  frontend/public/components/cluster-service-plan.tsx
  frontend/public/components/cluster-settings/cluster-operator.tsx
  frontend/public/components/configmap.jsx
  frontend/public/components/cron-job.jsx
  frontend/public/components/custom-resource-definition.tsx
  frontend/public/components/daemon-set.jsx
  frontend/public/components/default-resource.jsx
  frontend/public/components/hpa.tsx
  frontend/public/components/image-stream.tsx
  frontend/public/components/ingress.jsx
  frontend/public/components/job.jsx
  frontend/public/components/limit-range.tsx
  frontend/public/components/machine-autoscaler.tsx
  frontend/public/components/machine-config-pool.tsx
  frontend/public/components/machine-config.tsx
  frontend/public/components/machine-deployment.tsx
  frontend/public/components/machine-set.tsx
  frontend/public/components/machine.tsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/network-policy.jsx
  frontend/public/components/node.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/install-plan.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/components/persistent-volume-claim.jsx
  frontend/public/components/persistent-volume.jsx
  frontend/public/components/pod.tsx
  frontend/public/components/prometheus.jsx
  frontend/public/components/resource-quota.jsx
  frontend/public/components/routes.tsx
  frontend/public/components/secret.jsx
  frontend/public/components/service-account.jsx
  frontend/public/components/service-binding.tsx
  frontend/public/components/service-instance.tsx
  frontend/public/components/service-monitor.jsx
  frontend/public/components/service.jsx
  frontend/public/components/storage-class.tsx
  frontend/public/components/template-instance.tsx
  frontend/public/components/workload-table.tsx
  frontend/public/style/_overrides.scss
Labels: approved, lgtm, size/XL

#1705 Don't accept bin files in the yaml editor.
  frontend/public/components/droppable-edit-yaml.tsx
  frontend/public/components/edit-yaml.jsx
Labels: approved, lgtm, size/M

#1714 Tidy up table CSS post-PF4 table integration
  frontend/public/components/storage-class.tsx
  frontend/public/style.scss
  frontend/public/style/_base.scss
  frontend/public/style/_common.scss
  frontend/public/style/_overrides.scss
  frontend/public/style/_vars.scss
  frontend/public/vendor.scss
Labels: approved, lgtm, size/M

#1694 Remove Status and move view to Projects > Workloads
  frontend/integration-tests/tests/deploy-image.scenario.ts
  frontend/integration-tests/tests/overview/overview.scenario.ts
  frontend/integration-tests/tests/performance.scenario.ts
  frontend/package.json
  frontend/public/actions/ui.ts
  frontend/public/components/app-contents.tsx
  frontend/public/components/deploy-image.tsx
  frontend/public/components/modals/create-namespace-modal.jsx
  frontend/public/components/namespace.jsx
  frontend/public/components/nav/admin-nav.tsx
  frontend/public/components/overview/_overview.scss
  frontend/public/components/overview/_project-overview.scss
  frontend/public/components/overview/constants.ts
  frontend/public/components/overview/index.tsx
  frontend/public/components/overview/namespace-overview.tsx
  frontend/public/components/overview/project-overview.tsx
  frontend/public/components/source-to-image.tsx
  frontend/public/components/utils/horizontal-nav.tsx
  frontend/public/reducers/ui.ts
  frontend/yarn.lock
Labels: approved, lgtm, size/XL

#1717 Fix OLM InstallMode Logic
  frontend/__tests__/components/operator-lifecycle-manager/operator-group.spec.tsx
  frontend/integration-tests/tests/olm/single-installmode.scenario.ts
  frontend/integration-tests/views/operator-hub.view.ts
  frontend/public/components/operator-hub/operator-hub-subscribe.tsx
  frontend/public/components/operator-lifecycle-manager/operator-group.tsx
Labels: approved, lgtm, size/M

#1718 Remove "Edit Environment" from kebab/actions dropdowns
  frontend/public/components/build-config.tsx
  frontend/public/components/build.tsx
  frontend/public/components/daemon-set.jsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.tsx
  frontend/public/components/pod.tsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/stateful-set.jsx
  frontend/public/components/utils/kebab.tsx
Labels: approved, lgtm, size/M

#1711 Firehose: honor `optional` prop for watches on individual resources
  frontend/public/components/utils/firehose.jsx
Labels: approved, lgtm, ok-to-test, size/S, tide/merge-method-squash

#1715 Enable underline on hover of Import YAML
  frontend/public/components/_dropdown.scss
  frontend/public/components/namespace.jsx
Labels: approved, lgtm, size/XS

#1720 Add RBAC checks to dialog links
  frontend/public/components/machine-set.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/node.tsx
  frontend/public/components/utils/deployment-pod-counts.tsx
  frontend/public/components/utils/details-page.tsx
Labels: approved, lgtm, size/L

#1726 Bug 1720119: Tighten node IP query
  frontend/public/components/node.tsx
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1712 Dont link to ImageStreamTag if there is no tag in ImageStream status
  frontend/public/components/image-stream.tsx
Labels: approved, lgtm, size/S

#1727 Improve area and bar chart readability
  frontend/public/components/build.tsx
  frontend/public/components/graphs/area.tsx
  frontend/public/components/graphs/bar.tsx
  frontend/public/components/graphs/themes.ts
  frontend/public/components/namespace.jsx
  frontend/public/components/node.tsx
  frontend/public/components/pod.tsx
Labels: approved, lgtm, size/M

#1730 Fix broken ClusterServiceVersion instance links
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
Labels: approved, lgtm, size/S

#1734 Better OLM E2E Cleanup
  frontend/integration-tests/tests/olm/global-installmode.scenario.ts
  frontend/integration-tests/tests/olm/single-installmode.scenario.ts
Labels: approved, lgtm, size/XS

#1710 Query Browser: Make the Hide Graph button also hide the graph controls
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/M

#1733 Align <title> with <h1> for "Installed Operators"
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
Labels: approved, lgtm, size/XS

#1698 Use MultiListPage for BaremetalHostsPage
  frontend/packages/console-shared/src/selectors/common.ts
  frontend/packages/console-shared/src/selectors/index.ts
  frontend/packages/console-shared/src/selectors/machine.ts
  frontend/packages/eslint-plugin-console/lib/config/rules/react.js
  frontend/packages/metal3-plugin/src/components/host-role.tsx
  frontend/packages/metal3-plugin/src/components/host.tsx
  frontend/packages/metal3-plugin/src/components/machine-cell.tsx
  frontend/packages/metal3-plugin/src/models.ts
  frontend/packages/metal3-plugin/src/selectors/index.ts
  frontend/public/components/machine-deployment.tsx
  frontend/public/components/machine-set.tsx
  frontend/public/components/machine.tsx
Labels: approved, lgtm, size/L

#1701 Query Browser: Add page Actions menu and kebab menu for each query
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/L

#1735 Add support for custom table filters
  frontend/public/components/factory/list.tsx
  frontend/public/components/factory/table-filters.ts
  frontend/public/components/factory/table.tsx
Labels: approved, lgtm, size/XL

#1725 Add standard `Resource > Resource Details` breadcrumb to resource det…
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
  frontend/__tests__/components/pod.spec.tsx
  frontend/integration-tests/tests/olm/single-installmode.scenario.ts
  frontend/public/components/_nav-title.scss
  frontend/public/components/build.tsx
  frontend/public/components/container.tsx
  frontend/public/components/factory/details.tsx
  frontend/public/components/image-stream-tag.tsx
  frontend/public/components/machine-set.tsx
  frontend/public/components/machine.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/install-plan.tsx
  frontend/public/components/pod.tsx
  frontend/public/components/replicaset.jsx
  frontend/public/components/replication-controller.jsx
  frontend/public/components/resource-list.tsx
  frontend/public/components/utils/breadcrumbs.ts
  frontend/public/components/utils/headings.tsx
Labels: approved, lgtm, size/L

#1738 Upgrade kubevirt-web-ui-components to v0.1.35
  frontend/packages/kubevirt-plugin/package.json
  frontend/yarn.lock
Labels: approved, lgtm, ok-to-test, size/S

#1743 Jest config updates
  frontend/package.json
Labels: approved, lgtm, size/XS

#1744 Fix error in Table stateToProps
  frontend/public/components/factory/table.tsx
Labels: approved, lgtm, size/XS

#1544 Bug 1707631: Monitoring: Fix graph controls layout on mobile
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/graphs/query-browser.jsx
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1746 Bug 1721431: Fix bug where error occurred when clicking Update Channel Save withou…
  frontend/public/components/modals/cluster-channel-modal.tsx
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1747 Improve Feature Detection for OLM Nav Items
  frontend/public/components/nav/admin-nav.tsx
Labels: approved, lgtm, size/XS

#1745 Remove misleading route hostname message
  frontend/public/components/routes/create-route.tsx
Labels: approved, lgtm, size/XS

#1749 Limit alert height in modal editors
  frontend/public/components/utils/button-bar.jsx
Labels: approved, lgtm, size/XS

#1696 Add details card
  frontend/__tests__/components/utils/firehose.spec.tsx
  frontend/public/components/about-modal.tsx
  frontend/public/components/dashboard/details-card/detail-item.tsx
  frontend/public/components/dashboard/details-card/details-body.tsx
  frontend/public/components/dashboard/details-card/details-card.scss
  frontend/public/components/dashboard/details-card/index.ts
  frontend/public/components/dashboards-page/dashboards.tsx
  frontend/public/components/dashboards-page/overview-dashboard/details-card.tsx
  frontend/public/components/dashboards-page/overview-dashboard/health-card.tsx
  frontend/public/components/dashboards-page/overview-dashboard/overview-dashboard.tsx
  frontend/public/components/dashboards-page/with-dashboard-resources.tsx
  frontend/public/components/factory/details.tsx
  frontend/public/components/overview/index.tsx
  frontend/public/components/utils/index.tsx
  frontend/public/models/index.ts
  frontend/public/module/k8s/cluster-settings.ts
  frontend/public/style.scss
Labels: approved, lgtm, ok-to-test, size/L

#1748 Make cluster status default page for native k8s
  frontend/public/components/app-contents.tsx
Labels: approved, lgtm, size/XS

#1737 Add unit test for limitRange
  frontend/__tests__/components/limitrange.spec.tsx
  frontend/public/components/limit-range.tsx
Labels: approved, lgtm, size/M

#1708 Add plugin extension tests
  frontend/package.json
  frontend/packages/.eslintrc.js
  frontend/packages/console-app/package.json
  frontend/packages/console-app/src/__tests__/extension-checks/features.spec.ts
  frontend/packages/console-app/src/__tests__/extension-checks/models.spec.ts
  frontend/packages/console-app/src/__tests__/extension-checks/nav-items.spec.ts
  frontend/packages/console-app/src/__tests__/extension-checks/pages.spec.ts
  frontend/packages/console-app/src/__tests__/extension-checks/perspectives.spec.ts
  frontend/packages/console-app/src/__tests__/extension-checks/yaml-templates.spec.ts
  frontend/packages/console-app/src/__tests__/plugin-test-utils.ts
  frontend/packages/console-demo-plugin/src/components/test-icon.tsx
  frontend/packages/console-demo-plugin/src/components/test-pages.tsx
  frontend/packages/console-demo-plugin/src/plugin.tsx
  frontend/packages/console-demo-plugin/src/yaml-templates.ts
  frontend/packages/console-plugin-sdk/src/codegen/__tests__/active-plugins.spec.ts
  frontend/packages/console-plugin-sdk/src/codegen/__tests__/index.spec.ts
  frontend/packages/console-plugin-sdk/src/codegen/__tests__/plugin-resolver.spec.ts
  frontend/packages/console-plugin-sdk/src/codegen/__tests__/plugin-stats.spec.ts
  frontend/packages/console-plugin-sdk/src/codegen/active-plugins.ts
  frontend/packages/console-plugin-sdk/src/codegen/index.ts
  frontend/packages/console-plugin-sdk/src/codegen/plugin-resolver.ts
  frontend/packages/console-plugin-sdk/src/codegen/plugin-stats.ts
  frontend/packages/console-plugin-sdk/src/registry.ts
  frontend/packages/console-plugin-sdk/src/typings/index.ts
  frontend/packages/console-plugin-sdk/src/typings/nav-items.ts
  frontend/packages/console-plugin-sdk/src/typings/pages.ts
  frontend/packages/console-plugin-sdk/src/typings/perspectives.ts
  frontend/packages/console-plugin-sdk/src/typings/yaml-templates.ts
  frontend/packages/console-shared/src/selectors/common.ts
  frontend/packages/console-shared/src/selectors/machine.ts
  frontend/packages/kubevirt-plugin/src/plugin.ts
  frontend/packages/metal3-plugin/src/components/host.tsx
  frontend/packages/metal3-plugin/src/selectors/index.ts
  frontend/public/.eslintrc
  frontend/public/components/resource-pages.ts
  frontend/public/models/yaml-templates.ts
  frontend/public/module/k8s/k8s-models.ts
  frontend/public/plugins.ts
  frontend/public/reducers/features.ts
  frontend/tsconfig.json
  frontend/webpack.config.ts
  frontend/yarn.lock
Labels: approved, lgtm, size/XXL

#1728 Use plural instead of path
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
  frontend/packages/console-demo-plugin/src/models.ts
  frontend/packages/kubevirt-plugin/src/models.ts
  frontend/packages/metal3-plugin/src/models.ts
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/build-config.tsx
  frontend/public/components/build.tsx
  frontend/public/components/deployment-config.tsx
  frontend/public/components/deployment.tsx
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/environment.jsx
  frontend/public/components/job.jsx
  frontend/public/components/machine-config-pool.tsx
  frontend/public/components/machine-set.tsx
  frontend/public/components/modals/delete-namespace-modal.jsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/nav/admin-nav.tsx
  frontend/public/components/node.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion-resource.tsx
  frontend/public/components/operator-lifecycle-manager/k8s-resource.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
  frontend/public/components/secret.jsx
  frontend/public/components/service-account.jsx
  frontend/public/components/service-instance.tsx
  frontend/public/components/utils/deployment-pod-counts.tsx
  frontend/public/components/utils/details-page.tsx
  frontend/public/components/utils/kebab.tsx
  frontend/public/components/utils/rbac.tsx
  frontend/public/components/utils/resource-link.jsx
  frontend/public/models/index.ts
  frontend/public/module/k8s/index.ts
  frontend/public/module/k8s/resource.js
Labels: approved, lgtm, size/L, tide/merge-method-squash

#1753 Query Browser: Monitoring UI PatternFly tables fixes
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/M

#1756 Add a unit test for checking resourcequota usage icon
  frontend/__tests__/components/resource-quota.spec.tsx
  frontend/public/components/resource-quota.jsx
Labels: approved, lgtm, size/M

#1736 Query Browser: Add available metrics dropdown list
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/graphs/helpers.ts
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/L

#1759 Bump @patternfly/patternfly and @patternfly/react-core to latest (pre…
  frontend/package.json
  frontend/yarn.lock
Labels: approved, lgtm, size/M

#1755 Query Browser: Avoid unnecessary graph component renders
  frontend/public/components/graphs/query-browser.tsx
Labels: approved, lgtm, size/S

#1760 Fix bug where there is too much space between resource link and "- Default"
  frontend/public/components/_resource.scss
  frontend/public/components/storage-class.tsx
  frontend/public/components/utils/resource-link.jsx
  frontend/public/style.scss
  frontend/public/style/_storage-class.scss
Labels: approved, lgtm, size/M

#1719 Move cmd/bridge/config.go into pkg
  cmd/bridge/main.go
  pkg/bridge/validate.go
  pkg/serverconfig/config.go
  pkg/serverconfig/types.go
Labels: approved, lgtm, size/L

#1767 Query Browser: Add switch for toggling queries ON / OFF
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/L

#1682 Kubevirt VmDetails
  frontend/packages/kubevirt-plugin/src/components/vms/types.ts
  frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx
  frontend/packages/kubevirt-plugin/src/components/vms/vm-details.tsx
  frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
  frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
  frontend/packages/kubevirt-plugin/src/plugin.ts
  frontend/packages/kubevirt-plugin/src/style.scss
Labels: approved, lgtm, ok-to-test, size/L

#1771 Integrate routing advanced option in git import flow
  frontend/packages/dev-console/src/components/formik-fields/DroppableFileInputField.tsx
  frontend/packages/dev-console/src/components/formik-fields/field-types.ts
  frontend/packages/dev-console/src/components/formik-fields/index.ts
  frontend/packages/dev-console/src/components/import/GitImport.tsx
  frontend/packages/dev-console/src/components/import/GitImportForm.tsx
  frontend/packages/dev-console/src/components/import/__mocks__/import-validation-mock.ts
  frontend/packages/dev-console/src/components/import/__tests__/import-validation-utils.spec.ts
  frontend/packages/dev-console/src/components/import/builder/BuilderImageSelector.tsx
  frontend/packages/dev-console/src/components/import/git/GitSection.tsx
  frontend/packages/dev-console/src/components/import/import-submit-utils.ts
  frontend/packages/dev-console/src/components/import/import-types.ts
  frontend/packages/dev-console/src/components/import/import-validation-utils.ts
  frontend/packages/dev-console/src/components/import/route/CreateRoute.tsx
  frontend/packages/dev-console/src/components/import/route/RouteSection.tsx
  frontend/packages/dev-console/src/components/import/route/SecureRoute.tsx
  frontend/packages/dev-console/src/utils/__tests__/create-route-utils.spec.ts
  frontend/packages/dev-console/src/utils/create-route-utils.ts
Labels: approved, lgtm, size/L

#1739 VM Detail: add Events tab
  frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx
Labels: approved, lgtm, ok-to-test, size/XS

#1766 Fix errors due to Lodash module replacement
  frontend/webpack.config.ts
Labels: approved, lgtm, size/XS

#1769 Query Browser: Allow queries to contain newlines
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/S

#1778 feat(devconsole - pipeline) Make Pipeline/Run read-only and Fix Pipeline/Run List
  frontend/packages/dev-console/src/components/pipelineruns/PipelineRunDetailsPage.tsx
  frontend/packages/dev-console/src/components/pipelineruns/PipelineRunRow.tsx
  frontend/packages/dev-console/src/components/pipelines/PipelineDetailsPage.tsx
  frontend/packages/dev-console/src/components/pipelines/PipelineRow.tsx
  frontend/public/components/utils/status-icon.tsx
Labels: approved, lgtm, ok-to-test, size/S

#1777 Add script for plugin stats & simplify webpack config
  frontend/package.json
  frontend/plugin-stats.ts
  frontend/webpack.config.ts
Labels: approved, lgtm, size/M

#1781 Fix OLM E2E Test Cleanup
  frontend/integration-tests/tests/olm/global-installmode.scenario.ts
  frontend/integration-tests/tests/olm/single-installmode.scenario.ts
Labels: approved, lgtm, size/S

#1709 Initial PR for ceph plugin package
  frontend/packages/ceph-storage-plugin/OWNERS
  frontend/packages/ceph-storage-plugin/package.json
  frontend/packages/ceph-storage-plugin/src/models.ts
  frontend/packages/ceph-storage-plugin/src/plugin.ts
Labels: approved, lgtm, size/M

#1770 Add unit test for checking quota columns
  frontend/__tests__/components/limitrange.spec.tsx
  frontend/__tests__/components/resource-quota.spec.tsx
  frontend/public/components/resource-quota.jsx
Labels: approved, lgtm, size/S

#1775 Bug 1720045: Add polyfill for AbortController
  frontend/package.json
  frontend/public/components/utils/safe-fetch-hook.ts
  frontend/yarn.lock
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1779 expose build AccessReview functionality
  frontend/public/components/utils/kebab.tsx
  frontend/public/components/utils/rbac.tsx
Labels: approved, lgtm, ok-to-test, size/M

#1788 On Create s2i application form, selected version gets applied
  frontend/public/components/source-to-image.tsx
Labels: approved, lgtm, ok-to-test, size/XS

#1791 Remove invalid, orphaned CSS partial
  frontend/public/components/_users.scss
  frontend/public/style.scss
Labels: approved, lgtm, size/XS

#1796 fix(rowFilters): rowFilters scope fix
  frontend/public/components/factory/list.tsx
  frontend/public/components/factory/table.tsx
Labels: approved, lgtm, size/S

#1792 Query Browser: Remove tooltip from query enable/disable switch
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/XS

#1795 Refactor .co-m-pane__body styles so border is correctly added
  frontend/public/components/events.jsx
  frontend/public/components/service-account.jsx
  frontend/public/style/_common.scss
Labels: approved, lgtm, size/S

#1741 Add host detail page
  frontend/packages/metal3-plugin/src/components/host-detail.tsx
  frontend/packages/metal3-plugin/src/plugin.ts
  frontend/packages/metal3-plugin/src/selectors/index.ts
Labels: approved, lgtm, ok-to-test, size/L

#1805 Query Browser: Allow disabling individual series in the graph
  frontend/public/components/_monitoring.scss
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/L

#1768 Dry-run all resource creations in git import flow
  frontend/packages/dev-console/src/components/import/GitImport.tsx
  frontend/packages/dev-console/src/components/import/import-submit-utils.ts
Labels: approved, lgtm, size/M

#1807 Bug 1720045: Switch to WHATWG abort controller polyfill
  frontend/package.json
  frontend/public/components/app.jsx
  frontend/public/components/utils/safe-fetch-hook.ts
  frontend/yarn.lock
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1794 Prevent long unbroken resource names to cause horizontal scroll on modals that display resource name
  frontend/public/components/factory/modal.tsx
  frontend/public/components/modals/command-line-tools-modal.tsx
  frontend/public/components/modals/delete-modal.jsx
  frontend/public/components/modals/delete-namespace-modal.jsx
  frontend/public/components/modals/expand-pvc-modal.jsx
  frontend/public/components/operator-hub/operator-hub-community-provider-modal.tsx
  frontend/public/style/mixin/_break-word.scss
Labels: approved, lgtm, size/M

#1699 Add ExpandableAlert component
  frontend/public/components/image-stream.tsx
  frontend/public/components/utils/_alerts.scss
  frontend/public/components/utils/alerts.tsx
  frontend/public/components/utils/index.tsx
  frontend/public/style.scss
Labels: approved, lgtm, size/M

#1360 Add ConsoleLink CRD to enable custom links in help and user dropdowns
  frontend/public/actions/features.ts
  frontend/public/actions/ui.ts
  frontend/public/components/masthead-toolbar.jsx
  frontend/public/models/index.ts
  frontend/public/models/yaml-templates.ts
  frontend/public/reducers/ui.ts
Labels: approved, lgtm, size/M

#1812 Move alerts related styling
  frontend/public/components/utils/_alerts.scss
  frontend/public/style/_common.scss
Labels: approved, lgtm, size/S

#1797 Create Operand Form for OLM
  frontend/__mocks__/k8sResourcesMocks.ts
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion-resource.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/create-crd-yaml.spec.tsx
  frontend/__tests__/components/operator-lifecycle-manager/create-operand.spec.tsx
  frontend/integration-tests/tests/olm/global-installmode.scenario.ts
  frontend/integration-tests/tests/olm/single-installmode.scenario.ts
  frontend/public/components/app-contents.tsx
  frontend/public/components/create-yaml.tsx
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/modals/configure-count-modal.jsx
  frontend/public/components/modals/configure-count-modal.tsx
  frontend/public/components/operator-lifecycle-manager/_operator-lifecycle-manager.scss
  frontend/public/components/operator-lifecycle-manager/create-crd-yaml.tsx
  frontend/public/components/operator-lifecycle-manager/create-operand.tsx
  frontend/public/components/operator-lifecycle-manager/descriptors/README.md
  frontend/public/components/operator-lifecycle-manager/descriptors/spec/index.tsx
  frontend/public/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.tsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
  frontend/public/module/k8s/index.ts
  frontend/public/module/k8s/k8s.ts
Labels: approved, lgtm, size/XL

#1764 Initial PR for NooBaa plugin package
  frontend/packages/noobaa-storage-plugin/OWNERS
  frontend/packages/noobaa-storage-plugin/package.json
  frontend/packages/noobaa-storage-plugin/src/models.ts
  frontend/packages/noobaa-storage-plugin/src/plugin.ts
Labels: approved, lgtm, size/M

#1782 Remove extra space above <th> to restore spacing above table to what …
  frontend/public/style/_overrides.scss
Labels: approved, lgtm, size/XS

#1804 Use `tectonic-console-builder:v17` in Dockerfile
  Dockerfile
Labels: approved, lgtm, size/XS

#1808 Type-Check Test Files
  frontend/integration-tests/protractor.conf.ts
  frontend/tsconfig.json
Labels: approved, lgtm, size/S

#1441 Add ConsoleCLIDownload CRD extension
  frontend/__tests__/reducers/features.spec.tsx
  frontend/public/components/app-contents.tsx
  frontend/public/components/command-line-tools.tsx
  frontend/public/components/masthead-toolbar.jsx
  frontend/public/components/modals/command-line-tools-modal.tsx
  frontend/public/components/modals/index.ts
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/markdown-view.tsx
  frontend/public/const.ts
  frontend/public/models/index.ts
  frontend/public/models/yaml-templates.ts
  frontend/public/reducers/features.ts
Labels: approved, lgtm, size/L

#1757 TypeScript Enhancements
  frontend/packages/console-shared/src/selectors/common.ts
  frontend/packages/dev-console/src/utils/imagestream-utils.ts
  frontend/public/components/factory/table.tsx
  frontend/public/module/k8s/index.ts
Labels: approved, lgtm, ok-to-test, size/S

#1814 Fix display of empty probe on container details page
  frontend/public/components/container.tsx
Labels: approved, lgtm, size/XS

#1758 Kubevirt: port VM list to PF4 Table
  frontend/packages/kubevirt-plugin/src/components/vms/vm-details.tsx
  frontend/packages/kubevirt-plugin/src/components/vms/vm-resource.tsx
  frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
  frontend/packages/kubevirt-plugin/src/types/index.ts
  frontend/packages/kubevirt-plugin/src/types/vm/index.ts
Labels: approved, lgtm, ok-to-test, size/L

#1742 Add plugin infra for adding new dashboard tabs/cards
  frontend/packages/console-demo-plugin/src/dashboards/foo-card.tsx
  frontend/packages/console-demo-plugin/src/plugin.tsx
  frontend/packages/console-plugin-sdk/src/registry.ts
  frontend/packages/console-plugin-sdk/src/typings/dashboards.ts
  frontend/packages/console-plugin-sdk/src/typings/pages.ts
  frontend/packages/console-plugin-sdk/src/typings/types.ts
  frontend/public/components/app-contents.tsx
  frontend/public/components/dashboard/dashboard-card/card-body.tsx
  frontend/public/components/dashboard/grid.tsx
  frontend/public/components/dashboards-page/dashboards.tsx
  frontend/public/components/dashboards-page/overview-dashboard/overview-dashboard.tsx
  frontend/public/components/utils/horizontal-nav.tsx
Labels: approved, lgtm, ok-to-test, size/L

#1731 VirtualMachine details: add Disks tab
  frontend/packages/kubevirt-plugin/src/components/modals/delete-device-modal/delete-device-modal.tsx
  frontend/packages/kubevirt-plugin/src/components/modals/delete-device-modal/index.ts
  frontend/packages/kubevirt-plugin/src/components/vm-disks/_create-disk-row.scss
  frontend/packages/kubevirt-plugin/src/components/vm-disks/create-disk-row.tsx
  frontend/packages/kubevirt-plugin/src/components/vm-disks/disk-row.tsx
  frontend/packages/kubevirt-plugin/src/components/vm-disks/index.ts
  frontend/packages/kubevirt-plugin/src/components/vm-disks/types.ts
  frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
  frontend/packages/kubevirt-plugin/src/components/vms/vm-details-page.tsx
  frontend/packages/kubevirt-plugin/src/constants/vm/index.ts
  frontend/packages/kubevirt-plugin/src/k8s/patches/vm-template/index.ts
  frontend/packages/kubevirt-plugin/src/k8s/patches/vm/vm-disk-patches.ts
  frontend/packages/kubevirt-plugin/src/selectors/dv/selectors.ts
  frontend/packages/kubevirt-plugin/src/selectors/pvc/selectors.ts
  frontend/packages/kubevirt-plugin/src/selectors/selectors.ts
  frontend/packages/kubevirt-plugin/src/selectors/vm-template/selectors.ts
  frontend/packages/kubevirt-plugin/src/selectors/vm/disk.ts
  frontend/packages/kubevirt-plugin/src/selectors/vm/index.ts
  frontend/packages/kubevirt-plugin/src/selectors/vm/selectors.ts
  frontend/packages/kubevirt-plugin/src/selectors/vm/volume.ts
  frontend/packages/kubevirt-plugin/src/types/index.ts
  frontend/packages/kubevirt-plugin/src/types/types.ts
  frontend/packages/kubevirt-plugin/src/utils/index.ts
Labels: approved, lgtm, ok-to-test, size/XL

#1829 fix KebabOption type
  frontend/public/components/utils/kebab.tsx
Labels: approved, lgtm, size/XS

#1762 Add ImageStream and ImageStream history timeline
  frontend/public/components/_image-stream.scss
  frontend/public/components/image-stream-tag.tsx
  frontend/public/components/image-stream-timeline.tsx
  frontend/public/components/image-stream.tsx
  frontend/public/components/utils/horizontal-nav.tsx
Labels: approved, lgtm, size/L

#1817 Query Browser: Add <Query /> component
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/L

#1831 Revert PR-1782 as it introduces a bug where non-sortable col heads ha…
  frontend/public/style/_overrides.scss
Labels: approved, lgtm, size/XS

#1828 Upgrade kubevirt-web-ui-components to 0.1.36
  frontend/packages/kubevirt-plugin/package.json
  frontend/yarn.lock
Labels: approved, lgtm, size/S

#1833 Remove incorrect style for dashboard overview details card
  frontend/public/components/dashboard/details-card/details-card.scss
  frontend/public/components/dashboards-page/overview-dashboard/details-card.tsx
Labels: approved, lgtm, size/XS

#1783 Migrate Gauge component from Plotly to PatternFly 4
  frontend/package.json
  frontend/public/components/_cluster-overview.scss
  frontend/public/components/_quota.scss
  frontend/public/components/cluster-overview.jsx
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/graphs/area.tsx
  frontend/public/components/graphs/bar.tsx
  frontend/public/components/graphs/gauge.jsx
  frontend/public/components/graphs/gauge.tsx
  frontend/public/components/graphs/helpers.ts
  frontend/public/components/graphs/index.tsx
  frontend/public/components/graphs/prometheus-graph.tsx
  frontend/public/components/graphs/prometheus-poll-hook.ts
  frontend/public/components/graphs/status.jsx
  frontend/public/components/resource-quota.jsx
  frontend/public/components/utils/units.js
  frontend/yarn.lock
Labels: approved, lgtm, size/XL

#1798 Make ux updates to cluster settings pages
  frontend/public/components/cluster-settings/cluster-operator.tsx
  frontend/public/components/cluster-settings/cluster-settings.tsx
Labels: approved, lgtm, size/M

#1815 Installed Operator Subscription Tab
  frontend/__tests__/components/operator-lifecycle-manager/clusterserviceversion.spec.tsx
  frontend/public/components/nav/admin-nav.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/operator-lifecycle-manager/index.tsx
  frontend/public/components/operator-lifecycle-manager/subscription.tsx
Labels: approved, lgtm, size/L

#1834 Fix incorrect height of See All
  frontend/public/components/dashboard/dashboard-card/card-see-all.tsx
  frontend/public/components/dashboard/dashboard-card/card.scss
Labels: approved, lgtm, size/XS

#1837 Query Browser: Add a few more type definitions
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/S

#1835 Replace specific suite name with variable
  README.md
Labels: approved, lgtm, size/XS

#1763 Update alerts to PF4
  frontend/__tests__/components/environment.spec.tsx
  frontend/integration-tests/tests/olm/single-installmode.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/public/components/_about-modal.scss
  frontend/public/components/_environment.scss
  frontend/public/components/about-modal.tsx
  frontend/public/components/cluster-settings/global-config.tsx
  frontend/public/components/deploy-image.tsx
  frontend/public/components/edit-yaml.jsx
  frontend/public/components/environment.jsx
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/modals/configure-ns-pull-secret-modal.jsx
  frontend/public/components/monitoring.tsx
  frontend/public/components/operator-hub/operator-hub-subscribe.tsx
  frontend/public/components/operator-lifecycle-manager/clusterserviceversion.tsx
  frontend/public/components/routes/create-route.tsx
  frontend/public/components/service-binding.tsx
  frontend/public/components/service-instance.tsx
  frontend/public/components/utils/_alerts.scss
  frontend/public/components/utils/button-bar.jsx
  frontend/public/components/utils/download-button.tsx
  frontend/public/components/utils/list-dropdown.jsx
  frontend/public/components/utils/resource-log.jsx
  frontend/public/components/utils/status-box.tsx
  frontend/public/components/utils/workload-pause.tsx
Labels: approved, lgtm, size/L

#1673 Kubevirt VmTemplateList
  frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template.tsx
  frontend/packages/kubevirt-plugin/src/models.ts
  frontend/packages/kubevirt-plugin/src/plugin.ts
  frontend/packages/kubevirt-plugin/src/yaml-templates.ts
Labels: approved, lgtm, size/L

#1761 Kubevirt: add basic actions to VM list
  frontend/packages/kubevirt-plugin/src/components/modals/start-stop-vm-modal.tsx
  frontend/packages/kubevirt-plugin/src/components/vms/menu-actions.tsx
  frontend/packages/kubevirt-plugin/src/components/vms/vm.tsx
  frontend/packages/kubevirt-plugin/src/selectors/vm/selectors.ts
Labels: approved, lgtm, ok-to-test, size/L

#1838 Query Browser: Improve series button accessibility
  frontend/public/components/_monitoring.scss
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/S

#1830 update dev-console OWNERS
  frontend/packages/dev-console/OWNERS
Labels: approved, lgtm, size/XS

#1832 Add 'crd: true' accidentally removed when rebasing
  frontend/public/models/index.ts
Labels: approved, lgtm, size/XS

#1841 Replace NameValueEditor with SelectorInput for label field
  frontend/packages/dev-console/src/components/import/advanced/LabelSection.tsx
Labels: approved, lgtm, size/S

#1845 Add margin to prevent stacked action buttons from being too close
  frontend/public/components/_nav-title.scss
Labels: approved, lgtm, size/XS

#1751 Convert dropdowns and related inputs to pf4
  frontend/integration-tests/tests/crud.scenario.ts
  frontend/integration-tests/tests/developer-catalog.scenario.ts
  frontend/integration-tests/tests/olm/single-installmode.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-binding.scenario.ts
  frontend/integration-tests/tests/service-catalog/service-class.scenario.ts
  frontend/integration-tests/views/create-role-binding.view.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/integration-tests/views/environment.view.ts
  frontend/integration-tests/views/namespace.view.ts
  frontend/integration-tests/views/operator-hub.view.ts
  frontend/integration-tests/views/search.view.ts
  frontend/integration-tests/views/service-catalog.view.ts
  frontend/integration-tests/views/source-to-image.view.ts
  frontend/packages/dev-console/src/components/dropdown/ApplicationSelector.tsx
  frontend/public/components/_cluster-service-instance.scss
  frontend/public/components/_deploy-image.scss
  frontend/public/components/_dropdown.scss
  frontend/public/components/_resource-dropdown.scss
  frontend/public/components/_source-to-image.scss
  frontend/public/components/cluster-settings/_cluster-settings.scss
  frontend/public/components/factory/list-page.jsx
  frontend/public/components/graphs/query-browser.tsx
  frontend/public/components/namespace.jsx
  frontend/public/components/search.jsx
  frontend/public/components/utils/_label.scss
  frontend/public/components/utils/_name-value-editor.scss
  frontend/public/components/utils/_value-from-pair.scss
  frontend/public/components/utils/dropdown.jsx
  frontend/public/components/utils/headings.tsx
  frontend/public/components/utils/kebab.tsx
  frontend/public/components/utils/list-dropdown.jsx
  frontend/public/components/utils/name-value-editor.jsx
  frontend/public/components/utils/request-size-input.tsx
  frontend/public/components/utils/selector-input.jsx
  frontend/public/components/utils/storage-class-dropdown.tsx
  frontend/public/components/utils/value-from-pair.jsx
  frontend/public/style/_common.scss
  frontend/public/style/_forms.scss
  frontend/public/style/_overrides.scss
Labels: approved, lgtm, size/XXL

#1848 Remove cluster hostname from sidebar
  frontend/public/components/nav/nav-header.tsx
Labels: approved, lgtm, ok-to-test, size/S

#1849 Bug 1718309: bump js-yaml to 3.13.1
  frontend/package.json
  frontend/yarn.lock
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1772 Progressive Disclosure of advanced options
  frontend/packages/dev-console/src/components/import/GitImportForm.tsx
  frontend/packages/dev-console/src/components/import/advanced/AdvancedSection.tsx
  frontend/packages/dev-console/src/components/import/advanced/BuildConfigSection.tsx
  frontend/packages/dev-console/src/components/import/advanced/DeploymentConfigSection.tsx
  frontend/packages/dev-console/src/components/import/advanced/LabelSection.tsx
  frontend/packages/dev-console/src/components/import/advanced/ScalingSection.tsx
  frontend/packages/dev-console/src/components/import/route/RouteSection.tsx
  frontend/packages/dev-console/src/components/progressive-list/ProgressiveList.scss
  frontend/packages/dev-console/src/components/progressive-list/ProgressiveList.tsx
  frontend/packages/dev-console/src/components/progressive-list/ProgressiveListFooter.tsx
  frontend/packages/dev-console/src/components/progressive-list/ProgressiveListItem.tsx
  frontend/packages/dev-console/src/components/progressive-list/__tests__/ProgressiveList.spec.tsx
  frontend/packages/dev-console/src/components/progressive-list/__tests__/ProgressiveListFooter.spec.tsx
  frontend/packages/dev-console/src/components/progressive-list/__tests__/ProgressiveListItem.spec.tsx
Labels: approved, lgtm, size/L

#1827 fix(knative): adds utils to create knative resources
  frontend/packages/dev-console/src/models/index.ts
  frontend/packages/dev-console/src/models/knative.ts
  frontend/packages/dev-console/src/utils/create-knative-utils.ts
Labels: approved, lgtm, size/M

#1857 Query Browser: Expand / collapse button improvements
  frontend/public/components/graphs/_graphs.scss
  frontend/public/components/monitoring.tsx
Labels: approved, lgtm, size/S
