Repository openshift/console, pull requests merged in 2021-10, with the labels that each got.

#10110 Bug 2001575: Clicking on the perspective switcher shows a white page with loader
  frontend/public/components/nav/nav-header.tsx
Labels: approved, lgtm, bugzilla/valid-bug, component/core, bugzilla/severity-medium

#10004 Bug 2001804: Reload feature on Environment section in Build Config form does not work properly
  frontend/packages/console-shared/src/components/formik-fields/EnvironmentField.tsx
  frontend/public/components/utils/value-from-pair.jsx
Labels: approved, lgtm, bugzilla/valid-bug, component/shared, component/core, bugzilla/severity-low

#10166 Bug 2008612: HTTP method should be uppercased when proxying plugin request
  pkg/plugins/handlers.go
Labels: approved, lgtm, bugzilla/valid-bug, component/backend, bugzilla/severity-medium

#10104 Bug 2001577: Quick search placeholder is not displayed properly when the search string is removed
  frontend/packages/console-shared/src/components/quick-search/QuickSearchBar.tsx
Labels: approved, lgtm, bugzilla/valid-bug, component/shared, bugzilla/severity-low

#10160 Ownership update on network policies
  frontend/packages/console-app/locales/OWNERS
  frontend/packages/console-app/src/__tests__/network-policies/OWNERS
  frontend/packages/console-app/src/components/network-policies/OWNERS
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, kind/i18n

#10105 Netobserv-35 : network policy creation form - UX updates
  frontend/packages/console-app/locales/en/console-app.json
  frontend/packages/console-app/src/components/network-policies/network-policy-form.tsx
  frontend/packages/console-app/src/components/network-policies/network-policy-peer-ipblock.tsx
  frontend/packages/console-app/src/components/network-policies/network-policy-ports.tsx
  frontend/packages/console-app/src/components/network-policies/network-policy-rule-config.tsx
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, kind/i18n

#8803 Bug 2009420: Use live regions for alerts in modals
  frontend/public/components/utils/button-bar.jsx
Labels: lifecycle/rotten, approved, lgtm, bugzilla/valid-bug, component/core, bugzilla/severity-unspecified

#10173 Bug 2010342: Update fork-ts-checker-webpack-plugin and raise memory limit
  frontend/package.json
  frontend/webpack.config.ts
  frontend/yarn.lock
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#10060 Bug 2001817: Failed to load RoleBindings list that will lead to ‘Role name’ is not able to be selected on Create RoleBinding page as well
  frontend/public/components/RBAC/bindings.jsx
  frontend/public/components/namespace.jsx
Labels: approved, lgtm, bugzilla/valid-bug, component/core, bugzilla/severity-high

#10165 Bug 2009623: Query Browser: Fix pagination menu style to not show bullet points
  frontend/public/style/_overrides.scss
Labels: approved, lgtm, bugzilla/valid-bug, component/core, bugzilla/severity-low

#10141 Bug 2009131: kubevirt: add more test about vmi
  frontend/packages/kubevirt-plugin/integration-tests-cypress/support/index.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/action/clone.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/pvc-upload/pvc-upload.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/template/custom-template-support.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/template/source-image.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/vm/vmi.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/utils/const/string.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/views/selector.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/views/virtualization.ts
Labels: approved, lgtm, bugzilla/valid-bug, component/kubevirt, bugzilla/severity-low

#10021 convert topology application group side panel to use dynamic extensions
  frontend/packages/dev-console/console-extensions.json
  frontend/packages/dev-console/locales/en/devconsole.json
  frontend/packages/dev-console/src/actions/add-actions.tsx
  frontend/packages/dev-console/src/actions/providers.ts
  frontend/packages/dev-console/src/components/topology/observe-tab-section.tsx
  frontend/packages/knative-plugin/console-extensions.json
  frontend/packages/knative-plugin/src/actions/add-broker.tsx
  frontend/packages/knative-plugin/src/actions/add-channel.tsx
  frontend/packages/knative-plugin/src/actions/add-event-source.tsx
  frontend/packages/knative-plugin/src/actions/index.ts
  frontend/packages/knative-plugin/src/actions/providers.ts
  frontend/packages/topology/console-extensions.json
  frontend/packages/topology/package.json
  frontend/packages/topology/src/actions/TopologyActions.tsx
  frontend/packages/topology/src/actions/groupActions.ts
  frontend/packages/topology/src/actions/provider.ts
  frontend/packages/topology/src/components/application-panel/TopologyApplicationResources.tsx
  frontend/packages/topology/src/components/application-panel/application-resource-link.tsx
  frontend/packages/topology/src/components/application-panel/application-resource-tab-section.tsx
  frontend/packages/topology/src/components/application-panel/index.ts
  frontend/packages/topology/src/components/side-bar/getSelectedEntityDetails.tsx
  frontend/packages/topology/src/components/workload/CronJobSideBarDetails.tsx
  frontend/packages/topology/src/components/workload/DaemonSetSideBarDetails.tsx
  frontend/packages/topology/src/components/workload/DeploymentConfigSideBarDetails.tsx
  frontend/packages/topology/src/components/workload/DeploymentSideBarDetails.tsx
  frontend/packages/topology/src/components/workload/JobSideBarDetails.tsx
  frontend/packages/topology/src/components/workload/PodSideBarDetails.tsx
  frontend/packages/topology/src/components/workload/StatefulSetSideBarDetails.tsx
  frontend/packages/topology/src/components/workload/jobs-tab-section.tsx
  frontend/packages/topology/src/components/workload/resource-alert.tsx
  frontend/packages/topology/src/components/workload/utils.ts
Labels: approved, lgtm, component/dev-console, component/knative, docs-approved, qe-approved, px-approved, kind/i18n, component/topology

#10183 Revert "Bug 2010342: Update fork-ts-checker-webpack-plugin and raise memory limit"
  frontend/package.json
  frontend/webpack.config.ts
  frontend/yarn.lock
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#10079 Bug 2003145: Duplicate operand tab titles causes "two children with the same key" warning
  frontend/public/components/utils/horizontal-nav.tsx
Labels: approved, lgtm, bugzilla/valid-bug, component/core, bugzilla/severity-low

#10185 Bug 2008859: Fix generated dynamic plugin overridables
  frontend/dynamic-demo-plugin/package.json
  frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts
  frontend/packages/console-dynamic-plugin-sdk/src/coderefs/__tests__/coderef-resolver.spec.ts
  frontend/packages/console-dynamic-plugin-sdk/src/perspective/__tests__/perspective.data.ts
  frontend/packages/console-dynamic-plugin-sdk/src/runtime/__tests__/plugin-loader.spec.ts
  frontend/packages/console-dynamic-plugin-sdk/src/shared-modules.ts
  frontend/packages/console-dynamic-plugin-sdk/src/types.ts
  frontend/packages/console-dynamic-plugin-sdk/src/validation/ExtensionValidator.ts
  frontend/packages/console-dynamic-plugin-sdk/src/validation/__tests__/ExtensionValidator.spec.ts
  frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
Labels: approved, lgtm, bugzilla/valid-bug, component/sdk, bugzilla/severity-urgent

#9998 convert topology operator backed panel to use dynamic extensions
  frontend/packages/ceph-storage-plugin/console-extensions.json
  frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json
  frontend/packages/ceph-storage-plugin/package.json
  frontend/packages/ceph-storage-plugin/src/actions/actions.ts
  frontend/packages/ceph-storage-plugin/src/actions/csv-actions.ts
  frontend/packages/ceph-storage-plugin/src/actions/index.ts
  frontend/packages/operator-lifecycle-manager/console-extensions.json
  frontend/packages/operator-lifecycle-manager/locales/en/olm.json
  frontend/packages/operator-lifecycle-manager/package.json
  frontend/packages/operator-lifecycle-manager/src/actions/csv-actions-provider.ts
  frontend/packages/operator-lifecycle-manager/src/actions/csv-actions.ts
  frontend/packages/operator-lifecycle-manager/src/actions/index.ts
  frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
  frontend/packages/operator-lifecycle-manager/src/components/topology/sidebar/TopologyOperatorBackedResources.tsx
  frontend/packages/operator-lifecycle-manager/src/components/topology/sidebar/details-sections.tsx
  frontend/packages/operator-lifecycle-manager/src/components/topology/sidebar/index.ts
  frontend/packages/operator-lifecycle-manager/src/components/topology/sidebar/resource-link.tsx
  frontend/packages/operator-lifecycle-manager/src/components/topology/sidebar/resource-sections.tsx
  frontend/packages/operator-lifecycle-manager/src/components/topology/sidebar/types.ts
  frontend/packages/topology/locales/en/topology.json
  frontend/packages/topology/src/actions/TopologyActions.tsx
  frontend/packages/topology/src/components/side-bar/getSelectedEntityDetails.tsx
  frontend/packages/topology/src/operators/TopologyOperatorBackedPanel.tsx
Labels: approved, lgtm, component/ceph, component/olm, docs-approved, qe-approved, px-approved, kind/i18n, component/topology

#10357 Bug 2016438: adds feature flag for static extension for knative plugin
  frontend/packages/knative-plugin/src/plugin.tsx
Labels: approved, lgtm, bugzilla/valid-bug, component/knative, bugzilla/severity-medium

#10351 Bug 2005179: Pass pod toolbar filters to `useListPageFilter`
  frontend/public/components/pod.tsx
Labels: approved, lgtm, bugzilla/valid-bug, component/core, bugzilla/severity-medium

#10356 Bug 2002559: User preference for topology list view does not follow when a new namespace is created
  frontend/packages/topology/src/components/page/TopologyPage.tsx
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low, component/topology

#10135 (4.9 Backport) Bug 2008142: Allow web terminal to be installed in any namespace
  frontend/packages/console-app/src/components/cloud-shell/CloudShellTerminal.tsx
  frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellTerminal.spec.tsx
  frontend/packages/console-app/src/components/cloud-shell/__tests__/cloud-shell-utils.spec.ts
  frontend/packages/console-app/src/components/cloud-shell/cloud-shell-utils.ts
  frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellAdminSetup.tsx
  frontend/packages/console-app/src/components/cloud-shell/setup/CloudShellDeveloperSetup.tsx
  frontend/packages/console-app/src/components/cloud-shell/useCloudShellNamespace.ts
  frontend/packages/console-app/src/components/cloud-shell/useCloudShellWorkspace.ts
  pkg/server/server.go
  pkg/terminal/operator.go
  pkg/terminal/proxy.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, component/core, component/backend, bugzilla/severity-medium, backport-risk-assessed

#10361 Gherkin to pick from a list of pipelines in Add flow
  frontend/packages/pipelines-plugin/integration-tests/features/pipelines/create-from-add-options.feature
  frontend/packages/pipelines-plugin/integration-tests/testData/customNodeDeployment.yaml
  frontend/packages/pipelines-plugin/integration-tests/testData/customPythonDeploymentConfig.yaml
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, component/pipelines

#10325 make topology sidebar resizable
  frontend/packages/topology/src/__tests__/TopologySideBar.spec.tsx
  frontend/packages/topology/src/components/page/TopologyView.scss
  frontend/packages/topology/src/components/page/TopologyView.tsx
  frontend/packages/topology/src/components/side-bar/TopologySideBar.tsx
  frontend/packages/topology/src/const.ts
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, component/topology

#10355 Bug 2018446: move tests to different level
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/advanced-wizard.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/clone.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/console.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/create-template-from-wizard.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/custom-template-support.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/customize-source.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/dashboard.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/details.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/migration.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/snapshot.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/source-image.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-a/template-resource.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/cloud-init.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/create-vm-from-template.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/details-bootorder.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/details-resources-requirement.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/details-scheduling.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/empty-state.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/hotplug.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/ipv6.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/pvc-upload.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/ssh-advanced-wizard-testing.includes.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/ssh-secret-testing.includes.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/ssh-service-testing.includes.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/ssh-simple-wizard-test.includes.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/ssh-vm-details-page-testing.includes.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/ssh.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/sysprep.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/template-rhel9.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/template-support.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/validate-disk-preallocation.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/validate-nad-for-pxe.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/validate-rootdisk.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/validate-storage-profile.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/validate-virtio-win-image.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/vm-disk-nic.spec.ts
  frontend/packages/kubevirt-plugin/integration-tests-cypress/tests/tier1-b/vmi.spec.ts
Labels: approved, lgtm, bugzilla/valid-bug, component/kubevirt, bugzilla/severity-medium
