Repository openshift/console, pull requests merged in 2025-09, with the labels that each got.

#15441 [release-4.17]OCPBUGS-60441: Filtering nodes in OCP 4.16-17 shows all the nodes in the cluster
  frontend/packages/console-app/src/components/nodes/NodesPage.tsx
Labels: approved, lgtm, tide/merge-method-squash, component/core, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#15397 CONSOLE-4597: Migrate enzyme "__tests__/components/graphs" unit tests to React Testing Library
  frontend/__tests__/components/graphs/area.spec.tsx
  frontend/__tests__/components/graphs/bar.spec.tsx
  frontend/__tests__/components/graphs/gauge.spec.tsx
  frontend/__tests__/components/graphs/graph-empty.spec.tsx
  frontend/__tests__/components/graphs/prometheus-graph.spec.tsx
  frontend/public/components/graphs/__tests__/area.spec.tsx
  frontend/public/components/graphs/__tests__/bar.spec.tsx
  frontend/public/components/graphs/__tests__/gauge.spec.tsx
  frontend/public/components/graphs/__tests__/graph-empty.spec.tsx
  frontend/public/components/graphs/__tests__/helpers.spec.ts
  frontend/public/components/graphs/__tests__/prometheus-graph.spec.tsx
  frontend/public/components/graphs/__tests__/utils.spec.ts
  frontend/public/components/graphs/area.tsx
  frontend/public/components/graphs/bar.tsx
  frontend/public/components/graphs/gauge.tsx
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#15457 NO-JIRA: Update CHANGELOG in relation to 4.18 plugin SDK package publish
  frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md
  frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md
Labels: approved, lgtm, component/sdk, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#15456 NO-JIRA: Update CHANGELOG for latest 4.18 plugin SDK package publish
  frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md
  frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md
Labels: approved, lgtm, component/sdk, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#15437 NO-JIRA: Improve error message in vsphere-plugin
  frontend/packages/vsphere-plugin/locales/en/vsphere-plugin.json
  frontend/packages/vsphere-plugin/src/components/persist.ts
Labels: approved, lgtm, tide/merge-method-squash, docs-approved, qe-approved, px-approved, jira/valid-reference, verified

#15448 CONSOLE-4711: Replace confirmModal for useWarningModal
  frontend/packages/console-app/locales/en/console-app.json
  frontend/packages/console-app/src/actions/hooks/useReplicationControllerActions.ts
  frontend/packages/console-app/src/components/nav/PinnedResource.tsx
  frontend/packages/console-app/src/components/nav/confirmNavUnpinModal.tsx
  frontend/packages/console-app/src/components/nav/useConfirmNavUnpinModal.tsx
  frontend/packages/console-shared/src/hooks/useWarningModal.tsx
  frontend/packages/helm-plugin/integration-tests/support/pages/helm/upgrade-helm-release-page.ts
  frontend/packages/helm-plugin/src/components/details-page/history/HelmReleaseHistoryRow.tsx
  frontend/packages/helm-plugin/src/components/forms/install-upgrade/HelmChartVersionDropdown.tsx
  frontend/packages/integration-tests-cypress/tests/cluster-settings/alertmanager/alertmanager.cy.ts
  frontend/packages/integration-tests-cypress/views/warning-modal.ts
  frontend/packages/knative-plugin/src/actions/providers.ts
  frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx
  frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/modals/index.tsx
  frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/modals/remove-task.tsx
  frontend/packages/topology/locales/en/topology.json
  frontend/packages/topology/src/actions/edgeActions.ts
  frontend/packages/topology/src/actions/provider.ts
  frontend/packages/topology/src/utils/index.ts
  frontend/packages/topology/src/utils/removeConnection.tsx
  frontend/packages/topology/src/utils/topology-utils.ts
  frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/pages/web-terminal/webTerminal-page.ts
  frontend/public/components/RBAC/rules.jsx
  frontend/public/components/monitoring/alertmanager/alertmanager-config.tsx
  frontend/public/components/search.tsx
  frontend/public/locales/en/public.json
Labels: approved, lgtm, tide/merge-method-squash, component/shared, component/knative, component/monitoring, component/core, docs-approved, qe-approved, px-approved, kind/i18n, component/helm, component/topology, component/pipelines, kind/cypress, jira/valid-reference, verified

#15419 CONSOLE-4698: Enable SNC to true for frontend/console-app/components/volume-modes/snapshots and user preferences
  frontend/packages/console-app/src/components/user-preferences/UserPreferenceDropdownField.tsx
  frontend/packages/console-app/src/components/user-preferences/UserPreferenceForm.tsx
  frontend/packages/console-app/src/components/user-preferences/UserPreferencePage.tsx
  frontend/packages/console-app/src/components/user-preferences/__tests__/UserPreferenceCustomField.spec.tsx
  frontend/packages/console-app/src/components/user-preferences/__tests__/UserPreferenceField.spec.tsx
  frontend/packages/console-app/src/components/user-preferences/language/LanguageDropdown.tsx
  frontend/packages/console-app/src/components/user-preferences/language/usePreferredLanguage.ts
  frontend/packages/console-app/src/components/user-preferences/namespace/NamespaceDropdown.tsx
  frontend/packages/console-app/src/components/user-preferences/namespace/__tests__/NamespaceDropdown.spec.tsx
  frontend/packages/console-app/src/components/user-preferences/types.ts
  frontend/packages/console-app/src/components/volume-modes/volume-mode.tsx
  frontend/packages/console-app/src/components/volume-snapshot/create-volume-snapshot/create-volume-snapshot.tsx
  frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-class.tsx
  frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-content-details.tsx
  frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-content.tsx
  frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot-details.tsx
  frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
  frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts
  frontend/packages/console-dynamic-plugin-sdk/src/extensions/perspectives.ts
  frontend/packages/console-dynamic-plugin-sdk/src/extensions/user-preferences.ts
  frontend/packages/console-shared/src/components/datetime/__tests__/Timestamp.spec.tsx
  frontend/packages/dev-console/src/components/catalog/providers/useBuilderImageSamples.ts
  frontend/packages/dev-console/src/components/catalog/providers/useBuilderImages.tsx
  frontend/packages/gitops-plugin/src/components/details/TimestampWrapper.tsx
  frontend/packages/gitops-plugin/src/components/history/GitOpsDeploymentHistoryTableRow.tsx
  frontend/packages/insights-plugin/src/components/InsightsPopup/index.tsx
  frontend/packages/knative-plugin/src/catalog/useKameletsProvider.ts
  frontend/packages/knative-plugin/src/catalog/useKameletsSinkProvider.ts
  frontend/packages/pipelines-plugin/src/components/pipelineruns/hooks/usePipelineRuns.ts
  frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-overview/PipelineRunItem.tsx
  frontend/packages/topology/src/utils/usePodsForVM.ts
  frontend/packages/vsphere-plugin/src/components/ClusterOverview/VSphereStatus.tsx
  frontend/public/components/build-pipeline.tsx
  frontend/public/components/pod.tsx
  frontend/public/module/k8s/cluster-settings.ts
Labels: approved, lgtm, tide/merge-method-squash, component/shared, component/dev-console, component/knative, component/core, component/sdk, component/olm, docs-approved, qe-approved, px-approved, component/insights, component/topology, component/gitops, component/pipelines, jira/valid-reference, plugin-api-changed, plugin-api-approved, verified, verified-later

#15478 OCPBUGS-61458: fix MachineSet YAML template
  frontend/public/models/yaml-templates.ts
Labels: approved, lgtm, component/core, jira/valid-bug, jira/valid-reference, verified

#15472 CONSOLE-4756: Convert more files to TypeScript
  frontend/packages/console-app/src/components/tour/GuidedTourMastheadTrigger.tsx
  frontend/public/components/RBAC/index.ts
  frontend/public/components/app.tsx
  frontend/public/components/masthead/feedback-local.ts
  frontend/public/components/masthead/masthead-toolbar.tsx
  frontend/public/components/masthead/masthead.tsx
  frontend/public/components/modals/confirm-modal.tsx
  frontend/public/components/persistent-volume.tsx
  frontend/public/components/prometheus.tsx
  frontend/public/components/utils/inject.ts
  frontend/public/locales/en/public.json
  frontend/public/module/k8s/k8s-models.ts
  frontend/public/module/k8s/types.ts
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, kind/i18n, jira/valid-reference, verified

#15470 OCPBUGS-59972: Add validation and type guards on healthHandler calls to prevent errors
  frontend/public/components/dashboard/dashboards-page/cluster-dashboard/health-item.tsx
Labels: approved, lgtm, component/dashboard, component/core, jira/severity-critical, jira/valid-bug, jira/valid-reference, verified, verified-later

#15495 OCPBUGS-61519: Fix improper DescriptionList refactor
  frontend/packages/operator-lifecycle-manager/src/components/descriptors/index.tsx
  frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx
  frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Labels: approved, lgtm, component/olm, jira/valid-bug, jira/valid-reference, verified

#15460 OCPBUGS-61087: Updation of label from edit label doesn't work
  frontend/public/components/modals/labels-modal.tsx
  frontend/public/components/utils/selector-input.jsx
Labels: approved, lgtm, component/core, docs-approved, jira/valid-bug, jira/valid-reference, verified, verified-later

#15475 CONSOLE-4710: use useOverlay to launch ErrorModal
  frontend/packages/console-app/src/actions/hooks/useBuildsActions.ts
  frontend/packages/console-app/src/actions/hooks/useDeploymentActions.ts
  frontend/packages/console-app/src/actions/hooks/useRetryRolloutAction.ts
  frontend/packages/console-app/src/actions/providers/storageclass-provider.ts
  frontend/packages/console-app/src/components/nodes/status/SchedulableStatus.tsx
  frontend/packages/console-shared/src/components/formik-fields/EnvironmentField.tsx
  frontend/packages/knative-plugin/src/components/add/SecretKeySelector.tsx
  frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx
  frontend/packages/operator-lifecycle-manager/src/components/operator-install-page.tsx
  frontend/packages/pipelines-plugin/src/components/pipelines/modals/start-pipeline/StartPipelineModal.tsx
  frontend/packages/shipwright-plugin/src/actions/useBuildActions.ts
  frontend/packages/shipwright-plugin/src/actions/useBuildRunActions.ts
  frontend/packages/shipwright-plugin/src/components/build-tabsection/StartBuildButton.tsx
  frontend/packages/shipwright-plugin/src/components/build-tabsection/TriggerLastBuildButton.tsx
  frontend/packages/topology/src/components/workload/BuildOverview.tsx
  frontend/public/components/build-config.tsx
  frontend/public/components/cluster-settings/cluster-settings.tsx
  frontend/public/components/cluster-settings/cluster-status.tsx
  frontend/public/components/edit-yaml.tsx
  frontend/public/components/machine-config-pool.tsx
  frontend/public/components/modals/error-modal.tsx
  frontend/public/components/modals/index.ts
  frontend/public/components/utils/webhooks.tsx
  frontend/public/components/utils/workload-pause.tsx
Labels: approved, lgtm, component/shared, component/knative, component/core, component/olm, docs-approved, qe-approved, px-approved, component/topology, component/pipelines, jira/valid-reference, verified

#15497 [release-4.19] OCPBUGS-61781: Fix improper DescriptionList refactor
  frontend/packages/operator-lifecycle-manager/src/components/descriptors/index.tsx
  frontend/packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx
  frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
Labels: approved, lgtm, component/olm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#15505 NO-JIRA: chore(OWNERS): remove logonoff from reviewers
  frontend/OWNERS
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, jira/valid-reference, verified

#15482 NO-JIRA: Update README.md with instructions for logging out kube:admin in local
  README.md
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, jira/valid-reference, verified

#15501 OCPBUGS-59634: Fix the events search input width, and incorporate PF Toolbar component
  frontend/public/components/events.jsx
Labels: approved, lgtm, component/core, jira/valid-bug, jira/severity-moderate, jira/valid-reference, verified, verified-later

#15315 OCPBUGS-55401: PVC shows negative Available space in OpenShift Console on RHOCP 4
  frontend/__tests__/units.spec.js
  frontend/public/components/utils/units.js
Labels: approved, lgtm, component/core, jira/valid-bug, jira/severity-moderate, jira/valid-reference, verified, verified-later

#15503 [release-4.19] OCPBUGS-61821: Refactor PodConnect and Terminal to TypeScript
  frontend/packages/console-shared/src/hooks/fullscreen.ts
  frontend/packages/console-shared/src/hooks/index.ts
  frontend/packages/console-shared/src/hooks/useEventListener.ts
  frontend/packages/console-shared/src/hooks/useFullscreen.ts
  frontend/packages/console-shared/src/utils/index.ts
  frontend/packages/console-shared/src/utils/xterm-addon-fullscreen.scss
  frontend/packages/console-shared/src/utils/xterm-addon-fullscreen.ts
  frontend/packages/pipelines-plugin/src/components/pipelineruns/logs/LogsWrapperComponent.tsx
  frontend/packages/webterminal-plugin/src/components/cloud-shell/Terminal.tsx
  frontend/public/components/pod-connect.jsx
  frontend/public/components/pod-connect.tsx
  frontend/public/components/terminal.jsx
  frontend/public/components/terminal.tsx
  frontend/public/locales/en/public.json
  frontend/public/style/_common.scss
Labels: approved, lgtm, component/shared, component/core, kind/i18n, component/pipelines, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference, verified

#15509 CONSOLE-3769: Install `@openshift/dynamic-plugin-sdk`
  frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md
  frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md
  frontend/packages/console-dynamic-plugin-sdk/package.json
  frontend/packages/console-dynamic-plugin-sdk/src/types.ts
  frontend/packages/console-shared/src/hooks/useDetailsItemExtensionsForResource.ts
  frontend/yarn.lock
Labels: approved, lgtm, component/shared, component/sdk, docs-approved, qe-approved, px-approved, jira/valid-reference, verified

#15479 OCPBUGS-61569: Fix bug with Console provided PatternFly shared modules
  frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
Labels: approved, lgtm, component/sdk, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#15517 NO-JIRA: Update CHANGELOG based on 4.18 plugin SDK package release
  frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md
Labels: approved, lgtm, component/sdk, docs-approved, px-approved, backport-risk-assessed, jira/valid-reference, verified

#15477 CONSOLE-4764: Add tech preview feature flag support
  cmd/bridge/main.go
  pkg/serverconfig/config.go
  pkg/serverconfig/types.go
Labels: approved, lgtm, component/backend, docs-approved, qe-approved, px-approved, jira/valid-reference, verified

#15519 [release-4.20] OCPBUGS-62015: Help dropdown should be closed automatically after tour model opened
  frontend/packages/console-app/locales/en/console-app.json
  frontend/packages/console-app/src/components/tour/GuidedTourMastheadTrigger.tsx
  frontend/packages/console-app/src/components/tour/__tests__/GuidedTourMastheadTrigger.spec.tsx
  frontend/packages/console-app/src/components/tour/index.ts
  frontend/public/components/masthead-toolbar.jsx
  frontend/public/locales/en/public.json
Labels: approved, lgtm, component/core, kind/i18n, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference, verified, verified-later

#15518 CONSOLE-3769: Add @openshift/dynamic-plugin-sdk to core and internal pkg deps
  dynamic-demo-plugin/yarn.lock
  frontend/packages/console-dynamic-plugin-sdk/scripts/package-definitions.ts
Labels: approved, lgtm, component/sdk, docs-approved, px-approved, jira/valid-reference, verified

#15535 CONSOLE-4802: Migrate `KebabActions` to dynamic
  frontend/packages/console-app/src/components/oauth-config/OAuthConfigDetailsPage.tsx
  frontend/packages/console-plugin-sdk/src/typings/index.ts
  frontend/packages/console-plugin-sdk/src/typings/kebab-actions.ts
  frontend/packages/container-security/package.json
  frontend/packages/container-security/src/plugin.tsx
  frontend/packages/dev-console/src/components/deployments/__tests__/EditDeployment.spec.tsx
  frontend/packages/dev-console/src/plugin.tsx
  frontend/packages/gitops-plugin/package.json
  frontend/packages/gitops-plugin/src/plugin.tsx
  frontend/packages/knative-plugin/src/components/knatify/__tests__/CreateKnatifyPage.spec.tsx
  frontend/packages/knative-plugin/src/components/overview/__tests__/RevisionsOverviewList.spec.tsx
  frontend/packages/knative-plugin/src/plugin.tsx
  frontend/packages/knative-plugin/src/topology/topology-plugin.ts
  frontend/packages/metal3-plugin/src/plugin.tsx
  frontend/packages/operator-lifecycle-manager/src/components/install-plan.tsx
  frontend/packages/pipelines-plugin/package.json
  frontend/packages/pipelines-plugin/src/plugin.ts
  frontend/packages/pipelines-plugin/src/plugin.tsx
  frontend/packages/topology/src/actions/nodeActions.ts
  frontend/packages/topology/src/operators/operatorsTopologyPlugin.ts
  frontend/packages/topology/src/plugin.tsx
  frontend/public/components/RBAC/role.jsx
  frontend/public/components/build-config.tsx
  frontend/public/components/configmap.tsx
  frontend/public/components/control-plane-machine-set.tsx
  frontend/public/components/cron-job.tsx
  frontend/public/components/custom-resource-definition.tsx
  frontend/public/components/default-resource.tsx
  frontend/public/components/hpa.tsx
  frontend/public/components/image-stream-tag.tsx
  frontend/public/components/image-stream.tsx
  frontend/public/components/limit-range.tsx
  frontend/public/components/machine-autoscaler.tsx
  frontend/public/components/machine-config-pool.tsx
  frontend/public/components/machine-config.tsx
  frontend/public/components/machine-health-check.tsx
  frontend/public/components/machine-set.tsx
  frontend/public/components/machine.tsx
  frontend/public/components/persistent-volume.tsx
  frontend/public/components/pod.tsx
  frontend/public/components/resource-quota.jsx
  frontend/public/components/service-account.jsx
  frontend/public/components/utils/kebab.tsx
Labels: approved, lgtm, component/dev-console, component/knative, component/core, component/metal3, component/sdk, component/olm, docs-approved, qe-approved, px-approved, component/topology, component/gitops, component/pipelines, jira/valid-reference, verified

#15527 [release-4.19] OCPBUGS-62087: Help dropdown should be closed automatically after tour model opened
  frontend/packages/console-app/locales/en/console-app.json
  frontend/packages/console-app/src/components/tour/GuidedTourMastheadTrigger.tsx
  frontend/packages/console-app/src/components/tour/__tests__/GuidedTourMastheadTrigger.spec.tsx
  frontend/packages/console-app/src/components/tour/index.ts
  frontend/public/components/masthead-toolbar.jsx
  frontend/public/locales/en/public.json
Labels: approved, lgtm, component/core, qe-approved, kind/i18n, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference, verified

#15539 CONSOLE-4808: update resource-log.cy.ts
  frontend/packages/integration-tests-cypress/fixtures/pod-with-space.yaml
  frontend/packages/integration-tests-cypress/fixtures/pod-with-wrap-annotation.yaml
  frontend/packages/integration-tests-cypress/tests/app/resource-log.cy.ts
  frontend/packages/integration-tests-cypress/views/logs.ts
  frontend/public/components/utils/container-select.tsx
Labels: approved, lgtm, component/core, docs-approved, px-approved, kind/cypress, jira/valid-reference, verified

#15543 OCPBUGS-62313: Returning from any Secret Create page does not return to secret page
  frontend/public/components/factory/list-page.tsx
Labels: approved, lgtm, component/core, jira/valid-bug, jira/valid-reference, verified

#15513 CONSOLE-4332: Update the secrets forms to use PF components
  frontend/packages/dev-console/src/components/deployments/images/AdvancedImageOptions.tsx
  frontend/packages/dev-console/src/components/import/CreateSecretModal.tsx
  frontend/packages/dev-console/src/components/import/git/SourceSecretSelector.tsx
  frontend/packages/dev-console/src/components/import/image-search/ImageSearch.tsx
  frontend/packages/integration-tests-cypress/tests/crud/secrets/add-to-workload.cy.ts
  frontend/packages/integration-tests-cypress/tests/crud/secrets/image-pull.cy.ts
  frontend/packages/integration-tests-cypress/tests/crud/secrets/source.cy.ts
  frontend/packages/integration-tests-cypress/tests/events/events.cy.ts
  frontend/packages/integration-tests-cypress/views/secret.ts
  frontend/packages/shipwright-plugin/src/components/build-form/PushSecretSelector.tsx
  frontend/public/components/secrets/_create-secret.scss
  frontend/public/components/secrets/create-secret/AuthSecretForm.tsx
  frontend/public/components/secrets/create-secret/BasicAuthSubform.tsx
  frontend/public/components/secrets/create-secret/EditSecret.tsx
  frontend/public/components/secrets/create-secret/OpaqueSecretForm.tsx
  frontend/public/components/secrets/create-secret/OpaqueSecretFormEntry.tsx
  frontend/public/components/secrets/create-secret/PullSecretCredentialEntry.tsx
  frontend/public/components/secrets/create-secret/PullSecretCredentialsForm.tsx
  frontend/public/components/secrets/create-secret/PullSecretForm.tsx
  frontend/public/components/secrets/create-secret/PullSecretUploadForm.tsx
  frontend/public/components/secrets/create-secret/SSHAuthSubform.tsx
  frontend/public/components/secrets/create-secret/SecretFormWrapper.tsx
  frontend/public/components/secrets/create-secret/SecretSubForm.tsx
  frontend/public/components/secrets/create-secret/WebHookSecretForm.tsx
  frontend/public/components/secrets/create-secret/types.ts
  frontend/public/locales/en/public.json
  frontend/public/style.scss
  frontend/public/style/_forms.scss
Labels: approved, lgtm, component/dev-console, component/core, docs-approved, qe-approved, px-approved, kind/i18n, kind/cypress, jira/valid-reference, verified
