Repository openshift/console, pull requests merged in 2025-02, with the labels that each got.

#14710 OCPBUGS-46513: Add support for conditional CSP headers
  cmd/bridge/main.go
  pkg/server/server.go
  pkg/serverconfig/config.go
  pkg/serverconfig/types.go
Labels: approved, lgtm, component/backend, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#14694 OCPBUGS-48635: fix/remove broken codeRefs
  frontend/packages/console-app/console-extensions.json
  frontend/packages/console-app/src/components/storage/StorageClassProviders.ts
  frontend/packages/dev-console/console-extensions.json
Labels: approved, lgtm, component/dev-console, component/core, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#14706 OCPBUGS-49366: fix bug where Search filter dropdown label isn't i18n
  frontend/public/components/search-filter-dropdown.tsx
Labels: approved, lgtm, component/core, jira/valid-bug, jira/severity-low, jira/valid-reference, acknowledge-critical-fixes-only

#14719 OCPBUGS-49839: fix run time error when no completed version exists
  frontend/public/module/k8s/cluster-settings.ts
Labels: approved, lgtm, component/core, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#14712 NO-JIRA: Consolidate YAMLs Directory into yamls to Resolve macOS Case-Sensitivity Conflicts
  frontend/packages/dev-console/integration-tests/testData/yamls/monitoring/cluster-monitoring-config.yaml
  frontend/packages/dev-console/integration-tests/testData/yamls/monitoring/prometheous-example.yaml
  frontend/packages/dev-console/integration-tests/testData/yamls/monitoring/workload-monitoring-config.yaml
Labels: approved, lgtm, component/dev-console, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14722 OCPBUGS-49919: Catalog card label should be right aligned
  frontend/public/style/_overrides.scss
Labels: approved, lgtm, component/core, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#14708 OCPBUGS-49718: Fix Pipeline Repository overview page close button
  frontend/packages/pipelines-plugin/src/components/repository/RepositoryForm.tsx
Labels: approved, lgtm, component/pipelines, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#14656 OCPBUGS-47722: always show associated plugin name on CSV details page
  frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx
Labels: approved, lgtm, component/shared, component/olm, kind/i18n, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#14727 OCPBUGS-46513: Fix issue with bridge flag for conditional CSP features
  cmd/bridge/main.go
Labels: approved, lgtm, component/backend, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#14736 CONSOLE-4470: fix bug where Edit button is bold inside DetailsItem dt
  frontend/public/components/utils/_details-item.scss
  frontend/public/components/utils/details-item.tsx
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14737 CONSOLE-4471: fix bug where close button can overlap guided tour popo…
  frontend/packages/console-app/src/components/tour/steps/StepHeader.scss
  frontend/packages/console-app/src/components/tour/steps/StepHeader.tsx
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14738 CONSOLE-4472: fix QuickStart layout issues
  frontend/public/style/_overrides.scss
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14739 CONSOLE-4473: fix alignment issues with Bootstrap radio and checkbox …
  frontend/public/style/ancillary/_bootstrap-residual.scss
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14745 CONSOLE-4465: add workaround for menu scroll
  frontend/public/style/_overrides.scss
Labels: needs-ok-to-test, approved, lgtm, component/core, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14748 CONSOLE-4474: Unbold pf-v6 labels by default
  frontend/public/style/ancillary/_bootstrap-residual.scss
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14523 OCPBUGS-43061: update the Deployment pod on change in imageStream
  frontend/packages/dev-console/src/components/deployments/utils/deployment-utils.ts
  frontend/packages/dev-console/src/components/edit-application/edit-application-utils.ts
  frontend/packages/dev-console/src/components/import/__tests__/import-submit-utils.spec.ts
  frontend/packages/dev-console/src/components/import/__tests__/upload-jar-submit-utils.spec.ts
  frontend/packages/dev-console/src/utils/__tests__/resource-label-utils-data.ts
  frontend/packages/dev-console/src/utils/__tests__/resource-label-utils.spec.tsx
  frontend/packages/dev-console/src/utils/resource-label-utils.ts
Labels: approved, lgtm, component/dev-console, jira/valid-bug, jira/severity-low, jira/valid-reference, acknowledge-critical-fixes-only

#14734 CONSOLE-4469: improve layout and functionality of Edit upstream confi…
  frontend/public/components/modals/configure-cluster-upstream-modal.tsx
  frontend/public/locales/en/public.json
  frontend/public/style/_forms.scss
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, kind/i18n, jira/valid-reference, acknowledge-critical-fixes-only

#14751 CONSOLE-4475: fix QueryBrowser tooltip styles
  frontend/public/components/monitoring/_monitoring.scss
Labels: approved, lgtm, component/monitoring, component/core, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14742 OCPBUGS-49839: fix run time error when no completed version exists
  frontend/public/components/cluster-settings/cluster-settings.tsx
  frontend/public/module/k8s/cluster-settings.ts
Labels: approved, lgtm, component/core, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#14752 CONSOLE-4477: more token updates
  frontend/packages/knative-plugin/src/components/functions/GettingStartedSection.scss
  frontend/packages/pipelines-plugin/src/components/pipelineruns/PipelineRunDetailsPage.scss
  frontend/packages/pipelines-plugin/src/components/pipelineruns/list-page/PipelineRunList.scss
  frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationStepList.scss
  frontend/packages/pipelines-plugin/src/components/taskruns/TaskRunDetailsPage.scss
  frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsRow.scss
  frontend/packages/topology/src/components/graph-view/components/GraphComponent.scss
  frontend/packages/topology/src/components/graph-view/components/edges/ServiceBinding.scss
  frontend/packages/topology/src/components/graph-view/components/groups/GroupNode.scss
  frontend/packages/topology/src/components/page/TopologyView.scss
  frontend/packages/webterminal-plugin/src/components/cloud-shell/CloudShellTerminal.scss
  frontend/public/components/utils/_field-level-help.scss
Labels: approved, lgtm, ok-to-test, component/knative, component/core, docs-approved, qe-approved, px-approved, component/topology, component/pipelines, jira/valid-reference, acknowledge-critical-fixes-only

#14746 CONSOLE-4458: add workaround for dropdownitem tooltips
  frontend/public/components/QuickCreate.tsx
  frontend/public/locales/en/public.json
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash, component/core, docs-approved, qe-approved, px-approved, kind/i18n, jira/valid-reference, acknowledge-critical-fixes-only

#14704 OCPBUGS-46088: [Hypershift] Filter by Node type list is empty
  frontend/public/components/dashboard/dashboards-page/cluster-dashboard/utilization-card.tsx
Labels: approved, lgtm, component/dashboard, component/core, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#14709 OCPBUGS-48637: add support for "OpenShift Virtualization Engine" valid subscription filter on OperatorHub
  frontend/packages/operator-lifecycle-manager/src/components/operator-hub/index.ts
  frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-items.tsx
  frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-utils.spec.ts
  frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-utils.ts
Labels: approved, lgtm, component/backend, component/olm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#14750 CONSOLE-4464: bump PatternFly 6 to latest available versions
  frontend/package.json
  frontend/packages/pipelines-plugin/src/components/quicksearch/__tests__/PipelineQuicksearchDetails.spec.tsx
  frontend/yarn.lock
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, component/pipelines, jira/valid-reference, acknowledge-critical-fixes-only

#14691 OCPBUGS-48548: The secret created with Basic authentication has an incorrect type
  frontend/public/components/secrets/create-secret/SecretFormWrapper.tsx
  frontend/public/components/secrets/create-secret/utils.ts
Labels: approved, lgtm, component/core, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#14759 CONSOLE-4480: fix background color of Command Line Terminal tab
  frontend/packages/webterminal-plugin/src/components/cloud-shell/MultiTabbedTerminal.scss
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14747 OCPBUGS-49381: Workloads-DeploymentConfigs-Add storage: i18n misses
  frontend/public/components/container-selector.tsx
  frontend/public/locales/en/public.json
Labels: approved, lgtm, component/core, kind/i18n, jira/valid-bug, jira/severity-low, jira/valid-reference, acknowledge-critical-fixes-only

#14520 CONSOLE-4079,CONSOLE-4080: Address tech debt in GenericSecretForm and KeyValueEntryForm components
  frontend/public/components/secrets/create-secret/GenericSecretForm.tsx
  frontend/public/components/secrets/create-secret/KeyValueEntryForm.tsx
  frontend/public/components/secrets/create-secret/OpaqueSecretForm.tsx
  frontend/public/components/secrets/create-secret/OpaqueSecretFormEntry.tsx
  frontend/public/components/secrets/create-secret/SecretFormWrapper.tsx
  frontend/public/components/secrets/create-secret/SecretSubForm.tsx
  frontend/public/components/secrets/create-secret/index.tsx
  frontend/public/components/secrets/create-secret/types.ts
  frontend/public/components/secrets/create-secret/utils.ts
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14728 CONSOLE-4462: update dark theme specific styles
  frontend/packages/console-shared/src/components/getting-started/QuickStartGettingStartedCard.tsx
  frontend/packages/dev-console/src/components/add/AddCardItem.scss
  frontend/packages/knative-plugin/src/components/functions/QuickStartGettingStartedCard.tsx
  frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/create-local-volume-set.scss
  frontend/packages/service-binding-plugin/src/components/service-binding-utils/ServiceBindingAlerts.scss
  frontend/packages/service-binding-plugin/src/components/service-binding-utils/ServiceBindingAlerts.tsx
  frontend/public/style/_overrides.scss
  frontend/public/style/_theme-dark.scss
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash, component/shared, component/dev-console, component/knative, component/monitoring, component/core, component/lso, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14764 OCPBUGS-50665: fix bug where Demo Plugin tab url is always appended
  dynamic-demo-plugin/console-extensions.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#14684 ODC-7735: Edit ci tests to have step to enable developer perspective
  frontend/packages/dev-console/integration-tests/support/commands/hooks.ts
  frontend/packages/dev-console/integration-tests/support/pages/functions/checkDeveloperPerspective.ts
  frontend/packages/dev-console/integration-tests/support/pages/search-resources/search-page.ts
  frontend/packages/helm-plugin/integration-tests/features/helm-release.feature
  frontend/packages/helm-plugin/integration-tests/features/helm/helm-navigation.feature
  frontend/packages/helm-plugin/integration-tests/features/helm/helm-page-tabs.feature
  frontend/packages/helm-plugin/integration-tests/support/commands/hooks.ts
  frontend/packages/helm-plugin/integration-tests/support/step-definitions/common/common.ts
  frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-navigation.ts
  frontend/packages/helm-plugin/integration-tests/support/step-definitions/helm/helm-release.ts
  frontend/packages/integration-tests-cypress/tests/app/auth-multiuser-login.cy.ts
  frontend/packages/integration-tests-cypress/tests/crud/other-routes.cy.ts
  frontend/packages/integration-tests-cypress/views/nav.ts
  frontend/packages/knative-plugin/integration-tests/support/commands/hooks.ts
  frontend/packages/pipelines-plugin/integration-tests/features/e2e/pipeline-ci.feature
  frontend/packages/pipelines-plugin/integration-tests/support/commands/app.ts
  frontend/packages/pipelines-plugin/integration-tests/support/commands/hooks.ts
  frontend/packages/pipelines-plugin/integration-tests/support/commands/index.ts
  frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/common.ts
  frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/common/pipelines.ts
  frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/create-from-builder-page.ts
  frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-runs.ts
  frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipelines-secrets.ts
  frontend/packages/shipwright-plugin/integration-tests/support/commands/hooks.ts
  frontend/packages/topology/integration-tests/features/e2e/topology-ci.feature
  frontend/packages/topology/integration-tests/support/commands/hooks.ts
  frontend/packages/topology/integration-tests/support/step-definitions/common/topology.ts
  frontend/packages/webterminal-plugin/integration-tests/features/web-terminal/web-terminal-adminuser.feature
  frontend/packages/webterminal-plugin/integration-tests/support/commands/hooks.ts
  frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/common/webTerminal.ts
  frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/pages/web-terminal/initTerminal-page.ts
Labels: approved, lgtm, component/dev-console, component/knative, docs-approved, qe-approved, px-approved, component/helm, component/topology, component/pipelines, kind/cypress, jira/valid-reference, acknowledge-critical-fixes-only

#14768 NO-JIRA: Update Console dynamic plugin SDK doc and changelogs
  frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md
  frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md
  frontend/packages/console-dynamic-plugin-sdk/README.md
Labels: approved, lgtm, component/sdk, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14700 OCPBUGS-45141: Store Topology sidebar alert in the localStorage
  frontend/packages/console-shared/src/hooks/useGetUserSettingConfigMap.ts
  frontend/packages/topology/src/components/side-bar/components/SideBarAlerts.tsx
Labels: approved, lgtm, component/shared, component/topology, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#14767 CONSOLE-4467: replace html heading elements with PatternFly components
  dynamic-demo-plugin/src/components/ExampleNamespacedPage.tsx
  dynamic-demo-plugin/src/components/Nav.tsx
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14697 OCPBUGS-50693: Show Observe section without PROMETHEUS and MONITORING flags
  frontend/packages/console-app/console-extensions.json
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, jira/valid-bug, jira/valid-reference

#14713 OCPBUGS-49778: Linkify OLM operator uninstall message
  frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx
Labels: approved, lgtm, component/olm, jira/valid-bug, jira/valid-reference

#14732 OCPBUGS-49996: add missing contextId to be able to inject tabs from plugins
  frontend/packages/console-dynamic-plugin-sdk/src/extensions/console-types.ts
  frontend/public/components/utils/horizontal-nav.tsx
Labels: approved, lgtm, component/core, component/sdk, jira/valid-bug, jira/valid-reference

#14780 CONSOLE-4489: fix bug where dropdown menu can overflow
  frontend/packages/console-shared/src/components/multi-tab-list/MultiTabListPage.tsx
  frontend/packages/knative-plugin/src/components/functions/CreateActionDropdown.tsx
  frontend/packages/pipelines-plugin/src/components/ListPage.tsx
  frontend/public/components/_dropdown.scss
  frontend/public/components/factory/list-page.tsx
  frontend/public/components/utils/dropdown.jsx
Labels: approved, lgtm, component/shared, component/knative, component/core, docs-approved, qe-approved, px-approved, component/pipelines, jira/valid-reference, acknowledge-critical-fixes-only

#14779 NO-JIRA: Small demo plugin and plugin doc improvements
  dynamic-demo-plugin/package.json
  dynamic-demo-plugin/yarn.lock
  frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-core.md
  frontend/packages/console-dynamic-plugin-sdk/CHANGELOG-webpack.md
  frontend/packages/console-dynamic-plugin-sdk/README.md
  frontend/packages/console-plugin-shared/README.md
Labels: approved, lgtm, component/sdk, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14766 OCPBUGS-50670: fix bold text issues and missing underline on inline link buttons on safari and firefox.
  frontend/package.json
  frontend/packages/console-shared/src/components/dashboard/status-card/status-card.scss
  frontend/yarn.lock
Labels: approved, lgtm, component/shared, component/dashboard, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#14775 OCPBUGS-36786: Force async package upgrade.
  frontend/package.json
  frontend/yarn.lock
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#14782 CONSOLE-4486: decrease TertiaryHeading margins in Edit resource limit…
  frontend/packages/console-shared/src/components/heading/TertiaryHeading.tsx
  frontend/packages/dev-console/src/components/import/advanced/ResourceLimitSection.tsx
  frontend/public/components/routes.tsx
Labels: approved, lgtm, component/shared, component/dev-console, component/core, docs-approved, qe-approved, px-approved, jira/valid-reference, acknowledge-critical-fixes-only

#14695 OCPBUGS-48642: Check for unused modules in static plugins
  frontend/get-active-plugins.js
  frontend/packages/console-app/package.json
  frontend/packages/console-app/src/components/network-policies/NADsSelector.tsx
  frontend/packages/console-app/src/components/network-policies/multi-network-policy/multiNetworkFlag.ts
  frontend/packages/console-app/src/components/network-policies/types.ts
  frontend/packages/console-app/src/models/index.ts
  frontend/packages/console-dynamic-plugin-sdk/src/build-types.ts
  frontend/packages/console-dynamic-plugin-sdk/src/validation/ExtensionValidator.ts
  frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts
  frontend/packages/console-dynamic-plugin-sdk/src/webpack/ExtensionValidatorPlugin.ts
  frontend/packages/console-plugin-sdk/src/codegen/active-plugins.ts
  frontend/packages/console-plugin-sdk/src/index.ts
  frontend/packages/dev-console/console-extensions.json
  frontend/packages/dev-console/locales/en/devconsole.json
  frontend/packages/dev-console/src/components/catalog/CatalogCategoriesConfiguration.tsx
  frontend/packages/dev-console/src/components/catalog/index.ts
  frontend/packages/knative-plugin/package.json
  frontend/packages/knative-plugin/src/components/functions/index.ts
  frontend/packages/network-attachment-definition-plugin/OWNERS
  frontend/packages/network-attachment-definition-plugin/console-extensions.json
  frontend/packages/network-attachment-definition-plugin/locales/OWNERS
  frontend/packages/network-attachment-definition-plugin/locales/en/kubevirt-plugin.json
  frontend/packages/network-attachment-definition-plugin/locales/en/network-attachment-definition-plugin.json
  frontend/packages/network-attachment-definition-plugin/locales/es/kubevirt-plugin.json
  frontend/packages/network-attachment-definition-plugin/locales/es/network-attachment-definition-plugin.json
  frontend/packages/network-attachment-definition-plugin/locales/fr/kubevirt-plugin.json
  frontend/packages/network-attachment-definition-plugin/locales/fr/network-attachment-definition-plugin.json
  frontend/packages/network-attachment-definition-plugin/locales/ja/kubevirt-plugin.json
  frontend/packages/network-attachment-definition-plugin/locales/ja/network-attachment-definition-plugin.json
  frontend/packages/network-attachment-definition-plugin/locales/ko/kubevirt-plugin.json
  frontend/packages/network-attachment-definition-plugin/locales/ko/network-attachment-definition-plugin.json
  frontend/packages/network-attachment-definition-plugin/locales/zh/kubevirt-plugin.json
  frontend/packages/network-attachment-definition-plugin/locales/zh/network-attachment-definition-plugin.json
  frontend/packages/network-attachment-definition-plugin/package.json
  frontend/packages/network-attachment-definition-plugin/src/components/SubnetHelperText/SubnetHelperText.scss
  frontend/packages/network-attachment-definition-plugin/src/components/SubnetHelperText/SubnetHelperText.tsx
  frontend/packages/network-attachment-definition-plugin/src/components/TechPreview/TechPreview.scss
  frontend/packages/network-attachment-definition-plugin/src/components/TechPreview/TechPreview.tsx
  frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinition.scss
  frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinition.tsx
  frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionCreateYaml.tsx
  frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionDetails.tsx
  frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionDetailsPage.tsx
  frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkAttachmentDefinitionsForm.tsx
  frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/NetworkTypeOptions.tsx
  frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/index.ts
  frontend/packages/network-attachment-definition-plugin/src/components/network-attachment-definitions/types.ts
  frontend/packages/network-attachment-definition-plugin/src/constants/constants.tsx
  frontend/packages/network-attachment-definition-plugin/src/index.ts
  frontend/packages/network-attachment-definition-plugin/src/models/index.ts
  frontend/packages/network-attachment-definition-plugin/src/models/templates/index.ts
  frontend/packages/network-attachment-definition-plugin/src/plugin.ts
  frontend/packages/network-attachment-definition-plugin/src/selectors/index.ts
  frontend/packages/network-attachment-definition-plugin/src/types/index.ts
  frontend/packages/network-attachment-definition-plugin/src/types/types.ts
  frontend/packages/network-attachment-definition-plugin/src/utils/utils.ts
  frontend/webpack.circular-deps.ts
  frontend/webpack.config.ts
  frontend/yarn.lock
Labels: approved, lgtm, component/dev-console, component/knative, component/core, component/sdk, component/network-attachment-definition, kind/i18n, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#14760 CONSOLE-4484: Replace custom tabs with PF6 `Tabs` component
  frontend/packages/console-dynamic-plugin-sdk/README.md
  frontend/packages/dev-console/integration-tests/support/step-definitions/monitoring/dashboard-display.ts
  frontend/packages/dev-console/integration-tests/support/step-definitions/monitoring/topology-sidebar-actions.ts
  frontend/packages/helm-plugin/integration-tests/support/pages/helm/helm-details-page.ts
  frontend/packages/integration-tests-cypress/tests/cluster-settings/alertmanager/alertmanager.cy.ts
  frontend/packages/integration-tests-cypress/views/alertmanager.ts
  frontend/packages/integration-tests-cypress/views/details-page.ts
  frontend/packages/integration-tests-cypress/views/resource-sidebar.ts
  frontend/packages/knative-plugin/integration-tests/support/pageObjects/global-po.ts
  frontend/packages/pipelines-plugin/integration-tests/support/pages/pipelines/pipelines-page.ts
  frontend/packages/pipelines-plugin/integration-tests/support/step-definitions/pipelines/pipeline-navigation.ts
  frontend/packages/topology/integration-tests/support/page-objects/topology-po.ts
  frontend/packages/topology/integration-tests/support/pages/topology/topology-side-pane-page.ts
  frontend/packages/topology/src/components/side-bar/TopologyEdgePanel.tsx
  frontend/packages/topology/src/components/side-bar/components/SideBarBody.tsx
  frontend/public/components/_horizontal-nav.scss
  frontend/public/components/app-contents.tsx
  frontend/public/components/app.jsx
  frontend/public/components/global-telemetry-notifications.tsx
  frontend/public/components/monitoring/alertmanager/alertmanager-config.tsx
  frontend/public/components/monitoring/alertmanager/alertmanager-page.tsx
  frontend/public/components/monitoring/alertmanager/alertmanager-yaml-editor.tsx
  frontend/public/components/overview/resource-overview-details.tsx
  frontend/public/components/sidebars/resource-sidebar.tsx
  frontend/public/components/utils/horizontal-nav.tsx
  frontend/public/components/utils/simple-tab-nav.tsx
  frontend/public/style.scss
  frontend/public/style/_layout.scss
  frontend/public/style/_overrides.scss
Labels: approved, lgtm, component/dev-console, component/knative, component/monitoring, component/core, component/sdk, docs-approved, qe-approved, px-approved, component/helm, component/topology, component/pipelines, kind/cypress, jira/valid-reference, acknowledge-critical-fixes-only

#14643 OCPBUGS-46050: Determine if disabled a11y rules can be re-enabled
  frontend/packages/integration-tests-cypress/support/a11y.ts
Labels: approved, lgtm, kind/cypress, jira/valid-bug, jira/valid-reference

#14743 [release-4.18] OCPBUGS-49921: fix run time error when no completed version exists
  frontend/public/components/cluster-settings/cluster-settings.tsx
  frontend/public/module/k8s/cluster-settings.ts
Labels: approved, lgtm, cherry-pick-approved, component/core, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#14758 [release-4.18] OCPBUGS-50647: Enable web terminal tests
  frontend/integration-tests/test-cypress.sh
  frontend/packages/dev-console/integration-tests/.github/PULL_REQUEST_TEMPLATE/qe-automation-pr.md
  frontend/packages/dev-console/integration-tests/support/constants/global.ts
  frontend/packages/dev-console/integration-tests/support/pageObjects/web-terminal-po.ts
  frontend/packages/dev-console/integration-tests/support/pageObjects/webterminal-po.ts
  frontend/packages/dev-console/integration-tests/support/pages/app.ts
  frontend/packages/dev-console/integration-tests/support/pages/functions/addTerminalTabs.ts
  frontend/packages/dev-console/integration-tests/support/pages/functions/checkOperatorStatus.ts
  frontend/packages/dev-console/integration-tests/support/pages/functions/checkTerminalIcon.ts
  frontend/packages/dev-console/integration-tests/support/pages/functions/installOperatorOnClusterUsingCLI.ts
  frontend/packages/dev-console/integration-tests/support/pages/search-resources/search-page.ts
  frontend/packages/knative-plugin/integration-tests/README.md
  frontend/packages/webterminal-plugin/integration-tests/cypress.config.js
  frontend/packages/webterminal-plugin/integration-tests/features/web-terminal/web-teminal-basic.feature
  frontend/packages/webterminal-plugin/integration-tests/features/web-terminal/web-terminal-adminuser.feature
  frontend/packages/webterminal-plugin/integration-tests/support/commands/hooks.ts
  frontend/packages/webterminal-plugin/integration-tests/support/commands/index.ts
  frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/common/webTerminal.ts
  frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/pages/web-terminal/initTerminal-page.ts
  frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/pages/web-terminal/webTerminal-page.ts
  frontend/packages/webterminal-plugin/integration-tests/support/step-definitions/web-terminal/web-terminal-adminuser.ts
  frontend/packages/webterminal-plugin/integration-tests/testData/devworkspaceOperatorSubscription.yaml
Labels: approved, lgtm, cherry-pick-approved, component/dev-console, component/knative, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#14644 ODC-7725: Show perspective preferences option if more than one perspective are available
  frontend/packages/console-app/console-extensions.json
  frontend/packages/console-app/src/components/user-preferences/perspective/index.ts
  frontend/packages/console-app/src/components/user-preferences/perspective/usePerspectivesAvailable.ts
Labels: approved, lgtm, component/core, docs-approved, qe-approved, px-approved, jira/valid-reference

#14797 CONSOLE-4484: Reintroduce styling for tabs within a sidebar
  frontend/packages/topology/src/components/side-bar/TopologyEdgePanel.tsx
  frontend/packages/topology/src/components/side-bar/components/SideBarBody.tsx
  frontend/public/components/overview/resource-overview-details.tsx
  frontend/public/components/sidebars/resource-sidebar.tsx
  frontend/public/components/utils/simple-tab-nav.tsx
Labels: approved, lgtm, tide/merge-method-squash, component/core, docs-approved, qe-approved, px-approved, component/topology, jira/valid-reference

#14789 OCPBUGS-51180: Linkify OLM operator uninstall message
  frontend/packages/operator-lifecycle-manager/src/components/modals/uninstall-operator-modal.tsx
Labels: approved, lgtm, cherry-pick-approved, component/olm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#14792 ODC-7769: Add Getting started section in project Overview page
  frontend/packages/console-shared/src/constants/common.ts
  frontend/packages/dev-console/locales/en/devconsole.json
  frontend/packages/dev-console/src/components/add/AddPageLayout.tsx
  frontend/packages/dev-console/src/components/add/GettingStartedSection.scss
  frontend/packages/dev-console/src/components/add/constants.ts
  frontend/public/components/dashboard/dashboards-page/cluster-dashboard/getting-started/getting-started-section.scss
  frontend/public/components/dashboard/project-dashboard/getting-started/DeveloperFeaturesGettingStartedCard.tsx
  frontend/public/components/dashboard/project-dashboard/getting-started/GettingStartedSection.tsx
  frontend/public/components/dashboard/project-dashboard/getting-started/SampleGettingStartedCard.tsx
  frontend/public/components/dashboard/project-dashboard/getting-started/__tests__/DeveloperFeaturesGettingStartedCard.spec.tsx
  frontend/public/components/dashboard/project-dashboard/getting-started/__tests__/GettingStartedSection.spec.tsx
  frontend/public/components/dashboard/project-dashboard/getting-started/__tests__/SampleGettingStartedCard.data.ts
  frontend/public/components/dashboard/project-dashboard/getting-started/__tests__/SampleGettingStartedCard.spec.tsx
  frontend/public/components/dashboard/project-dashboard/project-dashboard.tsx
  frontend/public/locales/en/public.json
Labels: approved, lgtm, component/shared, component/dev-console, component/dashboard, component/core, docs-approved, qe-approved, px-approved, kind/i18n, jira/valid-reference

#14776 ODC-7724: Add guided tour in Admin perspective
  frontend/packages/console-app/console-extensions.json
  frontend/packages/console-app/locales/en/console-app.json
  frontend/packages/console-app/src/components/guided-tour/GuidedTourText.tsx
  frontend/packages/console-app/src/components/guided-tour/__tests__/GuidedTourText.spec.tsx
  frontend/packages/console-app/src/components/guided-tour/index.ts
  frontend/packages/console-app/src/components/tour/StepComponent.tsx
  frontend/packages/console-app/src/components/tour/TourStepComponent.tsx
  frontend/packages/console-app/src/components/tour/type.ts
  frontend/packages/console-app/src/plugin.tsx
  frontend/packages/console-shared/src/components/popover/Popover.scss
  frontend/packages/console-shared/src/components/spotlight/Spotlight.tsx
  frontend/packages/dev-console/console-extensions.json
  frontend/packages/dev-console/locales/en/devconsole.json
  frontend/packages/dev-console/src/components/guided-tour/GuidedTourText.tsx
  frontend/packages/dev-console/src/components/guided-tour/index.ts
  frontend/packages/helm-plugin/console-extensions.json
  frontend/packages/integration-tests-cypress/support/admin.ts
  frontend/packages/integration-tests-cypress/tests/app/admission-webhook-warning-notifications.cy.ts
Labels: approved, lgtm, component/shared, component/dev-console, component/core, docs-approved, qe-approved, px-approved, kind/i18n, component/helm, kind/cypress, jira/valid-reference
